### PR TITLE
FreeBSD: add functional routes.cpp, unblacklist modules

### PR DESCRIPTION
**Pull request by lxcode**
routes.cpp is Darwin's with minor modifications. Remove routes from the blacklist, as well as several others that work fine on FreeBSD.

### CODE REVIEW

**Comment by poppyseedplehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 440b0aa7c3ca6979ed2ad241edfdfab57172fe79 (Job results: [1444](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1444/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit d26efff77336c3d4172df37e01b8ec73fa28dfc4 (Job results: [1451](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1451/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit 7acda426c2896115f79b73a28abb651110aebde8 (Job results: [1452](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1452/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
test freebsd please

**Comment by osqueryer** [comment]
:-1: The commit 7acda426c2896115f79b73a28abb651110aebde8 (Job results: [6](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 7acda426c2896115f79b73a28abb651110aebde8 (Job results: [7](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7/)) failed one or more tests (**FreeBSD**).

**Pull request merged**
