### PR TITLE
Use octal when showing the 'mode' field in the 'process_events' table

### PR DESCRIPTION
**Pull request by alessandrogario**

### CODE REVIEW

**Comment by theopolis** [comment]
Wait, does this fix it, if so that's cool! Can I see a before and after?

**Comment by alessandrogario** [comment]
The AUDIT_PATH record already contains the mode in octal format (i.e.: 0100755). If you attempt to store it inside an INT or BIGINT column, the strtoul() function used to convert the string to number will notice it starts with a 0, converting it to decimal (33261).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 94be03a8d3501449d9b29c81cc38010726cdab27 (Job results: [2535](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2535/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 94be03a8d3501449d9b29c81cc38010726cdab27 (Job results: [1991](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1991/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 94be03a8d3501449d9b29c81cc38010726cdab27 (Job results: [1993](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1993/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 94be03a8d3501449d9b29c81cc38010726cdab27 (Job results: [5876](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5876/)) failed one or more tests (**Linux**).

**Pull request merged**
