### PR TITLE
Python bindings

### PR DESCRIPTION
**Pull request by marpaia**

### CODE REVIEW

**Comment by thepauleh** [comment]
Looks a lot simpler than doing it with swig -  just couldn't see how to import the third party libraries

**Comment by marpaia** [comment]
@thepauleh, there are a lot of dragons with python bindings apparently. for example, I worked on #687 a bit last week because some of our dependencies weren't being compiled with `-fPIC`, which didn't allow them to be linked into a Python dynamically linked library.

Boost::python also forces you to use the same version of Python to use bindings as was used to compile those bindings. So I assume we'd either have to compile against _every_ version of python, or punt on distributing them to people?

**Comment by marpaia** [comment]
Some simpler projects bundle a `setup.py` which compiles the C/C++ code for the project inline at install time, but it's a little trickier to have "pip install osquery" build osquery from source reliably.

**Comment by marpaia** [comment]
closing this for now as we're going to do this a little differently now

**Comment by theopolis** [comment]
```
$ sudo pip install thrift
$ make python-thrift
```

You could augment this: (adapted from extensions unit tests), to quietly subprocess an osqueryi using a known-tmp socket path.
```py
from thrift import Thrift
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol

sys.path.append("/build/darwin/generated/gen-py")
from osquery import *

class osqueryi:
    transport = None

    def __init__(self, path, uuid=None):
        self.path = path
        if uuid:
            self.path += ".%s" % str(uuid)
        transport = TSocket.TSocket(unix_socket=self.path)
        transport = TTransport.TBufferedTransport(transport)
        self.protocol = TBinaryProtocol.TBinaryProtocol(transport)
        self.transport = transport

    def close(self):
        if self.transport:
            self.transport.close()

    def open(self):
        try:
            self.transport.open()
        except:
            return False
        return True

    def getCore(self):
        return ExtensionManager.Client(self.protocol)

    def getExtension(self):
        return Extension.Client(self.protocol)
```

**Pull request closed without merging**
