### PR TITLE
Adding the ability to get addons in Ubuntu

### PR DESCRIPTION
**Pull request by jedi22**
I added a couple preprocessor macros so the table can be used under Ubuntu as well

### CODE REVIEW

**Comment by jedi22** [comment]
ok to test

**Comment by javuto** [comment]
@osqueryer, ok to test

**Comment by javuto** [comment]
@osqueryer, ok to test

**Comment by javuto** [comment]
@osqueryer, ok to test

**Comment by marpaia** [comment]
Is the spec not moved to `x` because this doesn't work on CentOS?

**Comment by javuto** [comment]
@osqueryer, ok to test

**Comment by javuto** [comment]
Nah, just CentOS 7 was freaking out. All is good :+1:

**Comment by theopolis** [comment]
As discussed earlier, the pre-processor conditionals should be an if/else, remove the duplicate spec, and move the implementation include into the general table target (out from darwin/ubuntu).

**Comment by javuto** [comment]
ok to test

**Pull request merged**
