### PR TITLE
Update example queries with correct columns

### PR DESCRIPTION
**Pull request by mtmcgrew**
Update example queries with correct columns

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 04c41cab82ddec96514a8544059921a7bd99d2b8 (Job results: [3463](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3463/)) failed one or more tests (**OS X/Linux**).

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 04c41cab82ddec96514a8544059921a7bd99d2b8 (Job results: [3466](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3466/)) failed one or more tests (**OS X/Linux**).

**Comment by mtmcgrew** [comment]
wat.

**Comment by mtmcgrew** [comment]
ok to test

**Pull request merged**
