### PR TITLE
Enable travis for osx and linux

### PR DESCRIPTION
**Pull request by fmanco**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 34106a350073a693c4afb3a6190a710bd06dfbf6 (Job results: [3636](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3636/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 34106a350073a693c4afb3a6190a710bd06dfbf6 (Job results: [3637](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3637/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 34106a350073a693c4afb3a6190a710bd06dfbf6 (Job results: [6741](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6741/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 34106a350073a693c4afb3a6190a710bd06dfbf6 (Job results: [6745](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6745/)) failed one or more tests (**Linux**).

**Comment by fmanco** [comment]
Let's close this for now since I'm not really working on it.

**Pull request closed without merging**
