### PR TITLE
debian: more portability in version detection

### PR DESCRIPTION
**Pull request by fanyeren**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
What is the expected output of `lsb_release -cs` vs the content in `/etc/debian_version`? Are they equivalent in most cases?

**Comment by theopolis** [comment]
Hi @fanyeren, have you had a change to sign the Facebook CLA: https://code.facebook.com/cla? Unfortunately we cannot merge changes from developers unless they agrees to the license agreement.

**Comment by theopolis** [comment]
We're just at a month with no CLA signed, unfortunately we'll need to close this out. Feel free to reopen! :D

**Pull request closed without merging**
