### PR TITLE
Force RocksDB to sync writes for non-event domains

### PR DESCRIPTION
**Pull request by theopolis**
RocksDB is the default "database" plugin. Writes are normally kept in an in-memory memtable. Writes that are not part of the event pubsub system can be forced to sync to disk.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/2228/merge (Job: 2844) failed :-1:

**Comment by zwass** [comment]
The RocksDB docs on this topic: https://github.com/facebook/rocksdb/wiki/Basic-Operations#synchronous-writes

My reading of this does not seem to indicate that the `options.sync` flag changes whether the `Put` writes to the disk, but that it just determines at what point during the write the `Put` returns.

I don't object to it if we are okay with the perf cost ("Asynchronous writes are often more than a thousand times as fast as synchronous writes") and it's surfacing useful errors.

**Comment by fuzzball5000** [comment]
"The sync flag can be turned on for a particular write" So... creating a frequent "heartbeat" write which we could force sync and would therefore throw an error on failure may work, rather than requiring sync for the actual data writes. All this would give us though is an early indication the underlying filesystem component had failed, and wouldn't give us any advantages as regards data integrity in such an event.

**Comment by theopolis** [comment]
@zwass you're reading correctly, but the period for which a async write lives in memory is abnormally large for osquery's persistent storage needs-- it's actually a factor of size (and/or compaction event). What I really want for most writes is a guarantee that `fdatasync` or some sort of `fsync` is called. The `.sync = true` provides us that guarantee.

**Comment by theopolis** [comment]
I reenabled the benchmarks and ran a before/after and there's a 10x measurable slowdown. This is what I expected, the only set of writes that makes use of the memtable is related to events and they remain async without measurable changes.

**Pull request merged**
