### PR TITLE
Removing old website and cleaning up the docs directory

### PR DESCRIPTION
**Pull request by marpaia**
This PR removes the old osquery website from the `docs/` directory of the repo.

### CODE REVIEW

**Comment by marpaia** [comment]
@osqueryer, test this please

**Comment by muffins** [comment]
ok to test

**Comment by theopolis** [comment]
Let's not be hasty in removing. I'd prefer if we let the new site bake for a while, keeping this content here for reference. How about 2 weeks and then we can remove if all is well.

**Comment by marpaia** [comment]
@theopolis @muffins any update on merging this? it's been about a month and the new site has baked nicely.

**Pull request merged**
