### PR TITLE
[Fix #1690] Update SQLite 3.12.0 pre-release: 721ae51e

### LINKED ISSUE #1690: Users, preferences, file JOIN inconsistencies
There is an inconsistency when adding a benign `limit` to a subquery. When the limit exists, the query behaves as expected, when it is missing the query appears to hang and does not return results.

**Update Feb 21st: Updating queries for SQLite version 3.11 support**

This works:
```sql
SELECT username, key, subkey, value, p.path FROM
  (SELECT u.username, file.path FROM
    (SELECT username, directory FROM users WHERE directory LIKE '/Users/%') u,
    file WHERE file.path LIKE u.directory || '/Library/Preferences/%loginwindow.%' LIMIT 999) f,
  preferences p
  WHERE p.path = f.path;
```

This does not:
```sql
SELECT username, key, subkey, value, p.path FROM
  (SELECT u.username, file.path FROM
    (SELECT username, directory FROM users WHERE directory LIKE '/Users/%') u,
    file WHERE file.path LIKE u.directory || '/Library/Preferences/%loginwindow.%') f,
  preferences p
  WHERE p.path = f.path;
```

### PR DESCRIPTION
**Pull request by theopolis**
Bump the SQLite version in third-party.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/1906/merge (Job: 2445) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
I keep forgetting to push the third-party commits. :(

**Comment by osqueryer** [comment]
Build origin/pr/1906/merge (Job: 2446) is good! :+1:

**Pull request merged**
