### PR TITLE
fix smc celsius -> fahrenheit calc

### PR DESCRIPTION
**Pull request by kaizensoze**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Since there's been a bit of thrashing on values and conversions within the new SMC-related tables, I think it's time for a unit test or two! @kaizensoze, would you mind adding a new file for `smc_tests.cpp` here: https://github.com/kaizensoze/osquery/tree/fix-smc-temp-celsius-to-fahrenheit/osquery/tables/system/darwin/tests and selecting from these tables or refactoring `genTemperature` slightly to pull the conversions into a mock/testable method?

And `getConvertedValue` would be a good target for a test or two!

**Comment by kaizensoze** [comment]
I was going to add tests for genTemperature, genVoltage, and genCurrent after this and the add-currents-table PR were merged. Would that work or do you want a temperature-related test included in this PR?

**Comment by theopolis** [comment]
If you don't mind, let's get some tests for the existing tables before moving forward. :D I hope it doesn't add too much more work or rebasing :(

**Comment by kaizensoze** [comment]
Ok will do!

**Comment by kaizensoze** [comment]
Added smc tests and refactored the gen functions to take a Row param.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1852/merge (Job: 2385) is good! :+1:

**Pull request merged**
