### PR TITLE
[Fix #991] Use separate targets for opt/debug builds

### LINKED ISSUE #991: Separate debug/opt build profiles into targets
To avoid rebuilding when `make` or `make debug` is alternated `make debug` should append a "_debug" to the end if the `./build/sys` name/target output directory.

### PR DESCRIPTION
**Pull request by theopolis**
I'm also a fan of "debug_sys" as it's more tab completion friendly, thoughts?

### CODE REVIEW

**Comment by marpaia** [comment]
you wasted no time on this one. looks awesome.

**Comment by theopolis** [comment]
This: https://github.com/facebook/osquery/pull/988/files#diff-b6279c0a9f35ce4cd4f20aaba77282e9R5

Is the other part of our speed-up discussion, it got caught in the parser PR, ha!

**Comment by marpaia** [comment]
I noticed that, nice work tracking down those variables.

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
