### PR TITLE
Update index.md to mention support for FreeBSD.

### PR DESCRIPTION
**Pull request by yonas**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
FreeBSD support is a bit of a tease. We don't have unit tests for FreeBSD and cannot guarantee osquery still builds/runs. I'm not sure if it's appropriate to include in the documentation.

**Comment by yonas** [comment]
@theopolis If osquery stops working on FreeBSD, the port maintainer will create a patch that will sit in the FreeBSD ports tree. If/when the port maintainer submits the patch upstream here, then the patch will be removed from the FreeBSD ports tree. This is the usual way FreeBSD assures compatibility in situations like this.

Also, when you install the FreeBSD port, the following warning message is displayed:

> This is the initial release of the FreeBSD port for osquery.
>
> We aren't anywhere near 100% feature parity when compared to
> Linux, however, we are actively working to get there.
> 
> osqueryd does not yet have the required functionality to run,
> however, osqueryi (the interactive CLI version) can perform
> basic tasks.
>
> Please submit patches as pull requests here:
> https://github.com/facebook/osquery

Because of this, unless the FreeBSD community reports that osquery is completely broken on FreeBSD, I don't see any reason not to include FreeBSD in the documentation as I've done in this patch.

Like you mentioned, the long term goal is to have unit tests for FreeBSD, and assure that osquery builds and runs on FreeBSD.

**Comment by theopolis** [comment]
Perfect, thanks for that!

**Pull request merged**
