### PR TITLE
Add saved UIDs and GIDs to process table

### PR DESCRIPTION
**Pull request by cdown**
Not tested locally since I have no Mac machine, I put my faith in Jenkins.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by cdown** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by cdown** [comment]
Failure is:

```
======================================================================
ERROR: test_utility_queries (__main__.ExampleQueryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/rhel7/tools/tests/test_example_queries.py", line 34, in test_utility_queries
    self._execute_set(PLATFORM_EXAMPLES["utility"])
  File "/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/rhel7/tools/tests/test_base.py", line 551, in _execute_set
    result = self._execute(example)
  File "/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/rhel7/tools/tests/test_base.py", line 546, in _execute
    raise e
TApplicationException: boost::filesystem::status: Permission denied: "/etc/grub2.cfg"
```

That seems like a flaky test, right?

**Comment by theopolis** [comment]
It's actually a good test, and it found a bug, but it's not with your code. ;)

**Pull request merged**
