### PR TITLE
Add path to error message when config file not found

### PR DESCRIPTION
**Pull request by zwass**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Nice, if we append the path to the end of the status it's easier to grep/match/aggregate on the prefix. The way it stands within this PR works too, but it's a bit less intuitive.

**Comment by zwass** [comment]
Here's how it looks now:
```
$ sudo ./build/darwin/osquery/osqueryd --allow_unsafe --config_path
/foo/bar
W0310 13:34:40.473743 1955008512 init.cpp:506] Error reading config:
config file does not exist: /foo/bar
```

**Comment by theopolis** [comment]
I like it, what do you think?

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1912/merge (Job: 2458) is good! :+1:

**Comment by zwass** [comment]
It's a simple, and more helpful message now IMO.

**Pull request merged**
