### PR TITLE
Fix potential leak

### PR DESCRIPTION
**Pull request by sharvilshah**
1. Fix potential leak in `disk_encryption` when grabbing user UUID.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Ahh! You found it! The leak checker also says safari_extensions has one. But that's my fault.

**Comment by theopolis** [comment]
ok to test

**Comment by sharvilshah** [comment]
It didn't catch the `safari_extensions` one for me, are you on clang bleeding edge? I am default one shipped with devtools (I believe it's 3.7).

**Comment by theopolis** [comment]
I think so, not 100%. Also ignore Jenkins right now, we haven't brought the nodes back online since patching yesterday morning.

**Comment by osqueryer** [comment]
Build origin/pr/1876/merge (Job: 2415) is good! :+1:

**Pull request merged**
