### PR TITLE
Fix for Issue #2262

### PR DESCRIPTION
**Pull request by texereda**
Quick fix for Issue 2262 under OS X, please bear with me, it's my first time using git and GitHub (and I'm not even a devel).

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit e7a058f41ea75d4b3ff84fb2704611f2f910bd7d (Job results: [2986](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2986/)) failed one or more tests.

**Pull request merged**
