### PR TITLE
Adding a WiFi survey table

### PR DESCRIPTION
**Pull request by jedi22**
After FriedButter made a comment about being able to detect rogue APs, I figured that only being able to detect it when someone was actually connected was a little restrictive. This introduced a table to return a scan of all wifi networks on all available wireless interfaces.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 4f4f6d12ce190dff89a873f6918a3c423490f87d (Job results: [770](https://jenkins.osquery.io/job/osqueryPullRequestAudit/770/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
I would call the table wifi_survey, instead of scan.

**Comment by friedbutter** [comment]
broadcast_wifi ?

**Comment by friedbutter** [comment]
Can you add a mock test for this table for unittest?

**Comment by theopolis** [comment]
This isn't really worth testing. @friedbutter what logic are you concerned with breaking?

**Comment by friedbutter** [comment]
I was concerning about APIs don't exist in older version, but. The CI, you mentioned, will take care of that. Mocking test is not necessary.

**Pull request merged**
