### PR TITLE
Add support for generating ctags and cscope

### PR DESCRIPTION
**Pull request by fmanco**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 53b00c111f1f14e12653358147a2d3e65a76d974 (Job results: [3635](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3635/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 53b00c111f1f14e12653358147a2d3e65a76d974 (Job results: [6740](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6740/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 53b00c111f1f14e12653358147a2d3e65a76d974 (Job results: [6743](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6743/)) failed one or more tests (**Linux**).

**Comment by fmanco** [comment]
ok to test

**Comment by fmanco** [comment]
I'm not expert either but this is pretty standard from what I found looking around and generate useful tags to use in vim. It's also pretty low risk so I'll just merge this.

**Pull request merged**
