### PR TITLE
modified osqueryctl for flags based deploys

### PR DESCRIPTION
**Pull request by sroberts**
Honestly I got so frustrated with trying to squash #1754 that I decided to cut a new PR.

> As someone working on osquery with remote configuration I've been trying to use osqueryctl and hit a number of snags. This adds the ability to use osqueryctl if a valid osquery.flags file is found.

All in one commit even!

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: 

@osqueryer, test this please

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Comment by sroberts** [comment]
@theopolis Pretty sure it wasn't me?

**Comment by theopolis** [comment]
Definitely not you!

**Comment by sroberts** [comment]
At first I was like:

MRW contestants on The Biggest Loser are forced to eat fast food

But then I was like: 

MRW the lady beside me at the coffee shop uses real cream and sugar in her coffee.

Thanks @theopolis.

**Pull request merged**
