### PR TITLE
fix the cpu id displayed in core column

### PR DESCRIPTION
**Pull request by friedbutter**
We assume the first word starts with 'cpu' and we split the string and get the cpu id. 

This should address #2025

### CODE REVIEW

**Comment by theopolis** [comment]
LGTM!

**Comment by osqueryer** [comment]
Build origin/pr/2038/merge (Job: 2601) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/2038/merge (Job: 2602) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/2038/merge (Job: 2603) failed :-1:

**Comment by friedbutter** [comment]
4-space bother me, so I also format the code.

**Comment by theopolis** [comment]
Looks ok, but let's hold off on merging until the tests are back online tomorrow morning. :)

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2038/merge (Job: 2605) is good! :+1:

**Pull request merged**
