### PR TITLE
Update osx-attacks.conf

### PR DESCRIPTION
**Pull request by echeng622**
Update "SearchInstUpdater" VT link in the description with the latest analysis, which has more hits in VT.

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [3611](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3611/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [3612](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3612/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [6721](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6721/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [6722](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6722/)) failed one or more tests (**Linux**).

**Comment by muffins** [comment]
ok to test

**Comment by muffins** [comment]
Once the linux audit jobs pass this we'll land. Sorry about that :)

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [1236](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1236/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:no_good: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [3285](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3285/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [6771](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6771/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [2799](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2799/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 91b8d3b58532899d7ef14ef6bb5b574bdc2197ed (Job results: [3666](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3666/)) failed one or more tests (**Windows**).

**Comment by muffins** [comment]
This is fine, pulled down and tested locally.

**Pull request merged**
