### PR TITLE
[Fix #877] Removing an extra escape

### LINKED ISSUE #877: path formatting in JSON output
Currently in the JSON output paths have \\\ added before /, which results in ugly output.  These should be removed when converting to JSON.

Example:
```
{"name":"processes_netconn","hostIdentifier":"mbp.keeleysam.com","calendarTime":"Wed Mar 18 04:26:20 2015","unixTime":"1426677980","columns":{"cmdline":"\\u0001 \\\/Applications\\\/Safari.app\\\/Contents\\\/MacOS\\\/Safari","local_address":"172.16.0.12","local_port":"64518","name":"Safari","on_disk":"1","parent":"1","path":"\\\/Applications\\\/Safari.app\\\/Contents\\\/MacOS\\\/Safari","pid":"26755","remote_address":"74.125.224.100","remote_port":"443","start_time":"343643044339550","uid":"501"},"action":"added"}
```

### PR DESCRIPTION
**Pull request by jedi22**
I believe the cause of the problem was that an extraneous escape was happening
in the `addNewResults` function in query.cpp.

I believe this can be safely removed because it's purpose is only to make things
JSON safe. However, I don't think this function is ever called with out a JSON
serialization later, making this unnecessary.

### CODE REVIEW

**Comment by marpaia** [comment]
@jedi22 can you write some tests for this to make sure it doesn't regress? Also, are you sure it's ok to remove that escaping? We added that as a bug-fix long ago. Will we regress on that?

**Comment by jedi22** [comment]
For peoples comments and general informations, this is what the output looks like when an application called `しかたがない.app` is moved, in and out of the `/Applications` folder with the query:

```SQL
select name, path, bundle_version, minimum_system_version, applescript_enabled, bundle_executable from apps;
```

running every second.

```JSON
{  
   "name":"installed_applications_test",
   "hostIdentifier":"obelisk-mbp5.local",
   "calendarTime":"Fri Mar 20 13:46:36 2015",
   "unixTime":"1426884396",
   "columns":{  
      "applescript_enabled":"",
      "bundle_executable":"uTorrent",
      "bundle_version":"37979",
      "minimum_system_version":"10.5",
      "name":"\\xE3\\x81\\x97\\xE3\\x81\\x8B\\xE3\\x81\\x9F\\xE3\\x81\\x8B\\xE3\\x82\\x99\\xE3\\x81\\xAA\\xE3\\x81\\x84.app",
      "path":"\/Applications\/\\xE3\\x81\\x97\\xE3\\x81\\x8B\\xE3\\x81\\x9F\\xE3\\x81\\x8B\\xE3\\x82\\x99\\xE3\\x81\\xAA\\xE3\\x81\\x84.app"
   },
   "action":"added"
}
```
```JSON
{  
   "name":"installed_applications_test",
   "hostIdentifier":"obelisk-mbp5.local",
   "calendarTime":"Fri Mar 20 13:46:44 2015",
   "unixTime":"1426884404",
   "columns":{  
      "applescript_enabled":"",
      "bundle_executable":"uTorrent",
      "bundle_version":"37979",
      "minimum_system_version":"10.5",
      "name":"\\xE3\\x81\\x97\\xE3\\x81\\x8B\\xE3\\x81\\x9F\\xE3\\x81\\x8B\\xE3\\x82\\x99\\xE3\\x81\\xAA\\xE3\\x81\\x84.app",
      "path":"\/Applications\/\\xE3\\x81\\x97\\xE3\\x81\\x8B\\xE3\\x81\\x9F\\xE3\\x81\\x8B\\xE3\\x82\\x99\\xE3\\x81\\xAA\\xE3\\x81\\x84.app"
   },
   "action":"removed"
}
```

**Comment by marpaia** [comment]
@jedi22 nice! can you include a few tests for this method? as well as an obligatory clang-format.

**Comment by jedi22** [comment]
ok to test

**Comment by jedi22** [comment]
It is important to note!
=
Due to the nature of this bug fix, all rocksDB entries that contain the old bugged slashes will be invalidated and thus new logs will be generated and pass the diff, even though they are the same file.

For example if you are querying for applications, you will see lots of these entries:
```JSON
{  
   "name":"installed_applications",
   "hostIdentifier":"host",
   "calendarTime":"Fri Mar 20 10:15:07 2015",
   "unixTime":"1426871707",
   "columns":{  
      "applescript_enabled":"1",
      "bundle_executable":"TextEdit",
      "bundle_version":"319",
      "minimum_system_version":"10.10",
      "name":"TextEdit.app",
      "path":"\\\/Applications\\\/TextEdit.app"
   },
   "action":"removed"
}
```
```JSON
{  
   "name":"installed_applications",
   "hostIdentifier":"host",
   "calendarTime":"Fri Mar 20 10:15:07 2015",
   "unixTime":"1426871707",
   "columns":{  
      "applescript_enabled":"1",
      "bundle_executable":"TextEdit",
      "bundle_version":"319",
      "minimum_system_version":"10.10",
      "name":"TextEdit.app",
      "path":"\/Applications\/TextEdit.app"
   },
   "action":"added"
}
```

**Comment by theopolis** [comment]
still need clang format, then looks gtg!

**Pull request merged**
