### PR TITLE
Introduce a PLATFORM_MASK and isPlatform

### PR DESCRIPTION
**Pull request by theopolis**
Along with the platform defines and platform string defines provided by CMake to the build, add a `PLATFORM_MASK` define.

Use this define as a platform-type mask with the `PlatformType` enum.

### Additional changes

1. Change the `WIN32` variable in CMake to `WINDOWS`, this reads and follows more clearly with our other supported platforms. 
2. Move the `GTEST_FLAGS` before the library discovery for a cleaner CMake cache population.
3. Add documentation in `./include/osquery/core.h` about the required preprocessor defines. Add some `#error` notes if those defines are not supplied by the build.
4. Change `ToolType` to a scoped enum.
5. Move `beginRegistryAndPluginInit` and related functions to the registry folder/include.
6. Install all build-from-source and default-build dependency tools when running `make deps`.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 8466d5e77557fc1a17e1be0c2abe01b03137393b (Job results: [2992](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2992/)) failed one or more tests.

**Comment by osqueryer** [comment]
:-1: The commit 9e941283170b3f277e3f7a3a2c1eaa692f7b76f1 (Job results: [2993](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2993/)) failed one or more tests.

**Comment by osqueryer** [comment]
:no_good: The commit ea262d49f516ec7b7e68f38370dd9d83c7480838 (Job results: [7](https://jenkins.osquery.io/job/osqueryPullRequestAudit/7/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit ea262d49f516ec7b7e68f38370dd9d83c7480838 (Job results: [2994](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2994/)) failed one or more tests.

**Comment by osqueryer** [comment]
:-1: The commit 5f0c7cf7ab7c29c1076e57e16f02e23e0cde4b28 (Job results: [2995](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2995/)) failed one or more tests.

**Comment by osqueryer** [comment]
:-1: The commit a324e5a51cef144f4a6a9c76c9646f2fc91713ef (Job results: [2996](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2996/)) failed one or more tests.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit a324e5a51cef144f4a6a9c76c9646f2fc91713ef (Job results: [2997](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2997/)) failed one or more tests.

**Comment by osqueryer** [comment]
:-1: The commit 09188dd0b1fd0d0835d442ebc6e113bb895ff609 (Job results: [2998](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2998/)) failed one or more tests.

**Comment by theopolis** [comment]
Fighting through tons of test errors.

**Pull request merged**
