### PR TITLE
Remove time-override for events add API

### PR DESCRIPTION
**Pull request by theopolis**
This will remove the use of current time for `syslog.time` and introduce a new column called `datetime`.

Events now uses an `optimize_id` alongside `optimize` to prevent returning colliding events added within the same second as the previous `genTable` call.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 7d992c96ecb4908e0368efe1e278a25f6f232110 (Job results: [298](https://jenkins.osquery.io/job/osqueryPullRequestAudit/298/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 7d992c96ecb4908e0368efe1e278a25f6f232110 (Job results: [3315](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3315/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-4** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2508/files/7d992c96ecb4908e0368efe1e278a25f6f232110..e72736fae06b4bfd374d87329232378688bd1229)

**Comment by facebook-github-bot-1** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2508/files/e72736fae06b4bfd374d87329232378688bd1229..44d9187455b28abe448cc8eed0d7a36f7a1dc2e6)

**Comment by osqueryer** [comment]
:-1: The commit 44d9187455b28abe448cc8eed0d7a36f7a1dc2e6 (Job results: [3322](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3322/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-9** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2508/files/44d9187455b28abe448cc8eed0d7a36f7a1dc2e6..2fd8dba6911cd5601fe576aa92c457052189a22e)

**Comment by osqueryer** [comment]
:no_good: The commit 2fd8dba6911cd5601fe576aa92c457052189a22e (Job results: [307](https://jenkins.osquery.io/job/osqueryPullRequestAudit/307/)) failed the code audit.

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
