### PR TITLE
kernel: Disable kernel support by default

### PR DESCRIPTION
**Pull request by theopolis**
NB: Newer versions of macOS will disable support for our kernel extension experience. The previous use has now been replicated in user space using BSM (for `process_events`).

This disables building support for the outdated osquery kernel extension. Most importantly it disables building and linking the kernel tests and benchmarks. It will reduce the binary size and build time.

The decision to disable the build and let the code atrophy was made vs removing all of the code examples. This allows folks to continue to discover the implementation and for fast-revival if we end up needing it again.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [2420](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2420/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [683](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/683/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [5753](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5753/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [1859](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1859/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [2639](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2639/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [5754](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5754/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [1860](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1860/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [2640](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2640/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 313a942b536d4359c98d26e79ac89f26e16d77b8 (Job results: [684](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/684/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 75ccb94946ac18a1ffdd92b2e201a78547fbeb00 (Job results: [1861](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1861/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 75ccb94946ac18a1ffdd92b2e201a78547fbeb00 (Job results: [1862](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1862/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit ce13863c0c8fef24e40d406c0f43b628b1b311e3 (Job results: [2422](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2422/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit ce13863c0c8fef24e40d406c0f43b628b1b311e3 (Job results: [1863](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1863/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit ce13863c0c8fef24e40d406c0f43b628b1b311e3 (Job results: [1864](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1864/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit e17a05d47c77bee7b74368cd236e6aff26d98825 (Job results: [2424](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2424/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit e17a05d47c77bee7b74368cd236e6aff26d98825 (Job results: [5758](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5758/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e17a05d47c77bee7b74368cd236e6aff26d98825 (Job results: [1866](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1866/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
Note that this is moving `process_file_events` into an unused (legacy) `kernel/` specs category. It is possible to keep this table using Audit and OpenBSM integrations in the future.

**Pull request merged**
