### PR TITLE
add powers table

### PR DESCRIPTION
**Pull request by kaizensoze**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1860/merge (Job: 2391) failed :-1:

**Comment by theopolis** [comment]
The Jenkins failures on Linux machines is my fault :)

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1860/merge (Job: 2393) is good! :+1:

**Pull request merged**
