### PR TITLE
[#1702] Add config and database dumping to stdout

### PR DESCRIPTION
**Pull request by theopolis**
From #1702:

This provides (1) and (3). The second bullet is skipped since it takes a bit more work and is not straight forward that it should even exist beyond a method for debugging. If a config fetch fails the daemon stops.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Comment by theopolis** [comment]
Nailed it! I'll leave this up for review for a bit: looking for opinions on the flow of writing config content to stdout when --config_check is used. Another option is to add an option called --config_dump.

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Pull request merged**
