### PR TITLE
deps: Rebuild the world, static and hidden

### PR DESCRIPTION
**Pull request by theopolis**
This commit will bump almost every dependency. They are now rebuilt with some changes to the osquery abstract, the new version of LLVM, and new default symbol visibility settings.

The dependency set has not been rebuilt in its entirety in almost a year. It is possible hard-to-spot regressions and new bugs have been introduced. Usually a change to a dependency will involve a tweak to the _abstract_, which controls compiler and linking flags for all dependencies. Those changes should be caught by a nightly world-rebuild Jenkins job: https://jenkins.osquery.io/job/osqueryMasterDependenciesLinux/ This job is subject to flakiness. For example, it has been erroring because a dependency tarball no longer exists on a mirror.

All of the dependent libraries now include `-fvisibility=default` allowing us more optimization power and shaving about 2M from Linux and 1M from Darwin (final stripped binary size). This change increases the need for debug builds, we will try to provide `-dbg` and `-debug` packages on osquery.io going forward.

### CODE REVIEW

**Comment by theopolis** [comment]
test freebsd please

**Comment by osqueryer** [comment]
:-1: The commit f4dfce5caae081fd9063b76d51be342ce262164d (Job results: [4741](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4741/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit f4dfce5caae081fd9063b76d51be342ce262164d (Job results: [4742](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4742/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 7f4e7689798eb15358a65cda116d6eb6b8c53818 (Job results: [4743](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4743/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 7f4e7689798eb15358a65cda116d6eb6b8c53818 (Job results: [1616](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1616/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 7f4e7689798eb15358a65cda116d6eb6b8c53818 (Job results: [1617](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1617/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 7f4e7689798eb15358a65cda116d6eb6b8c53818 (Job results: [885](https://jenkins.osquery.io/job/osqueryPullRequestOSX/885/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 7f4e7689798eb15358a65cda116d6eb6b8c53818 (Job results: [886](https://jenkins.osquery.io/job/osqueryPullRequestOSX/886/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 7f4e7689798eb15358a65cda116d6eb6b8c53818 (Job results: [4744](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4744/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d77c2b2d66c927bd4c52d27cfb7badff5d454130 (Job results: [4745](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4745/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d77c2b2d66c927bd4c52d27cfb7badff5d454130 (Job results: [4746](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4746/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d77c2b2d66c927bd4c52d27cfb7badff5d454130 (Job results: [1618](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1618/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d77c2b2d66c927bd4c52d27cfb7badff5d454130 (Job results: [1619](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1619/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit db065fb7c1679b8d30cfb616c81ddd3e0aa09223 (Job results: [1620](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1620/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit db065fb7c1679b8d30cfb616c81ddd3e0aa09223 (Job results: [1621](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1621/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit db065fb7c1679b8d30cfb616c81ddd3e0aa09223 (Job results: [4747](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4747/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit db065fb7c1679b8d30cfb616c81ddd3e0aa09223 (Job results: [888](https://jenkins.osquery.io/job/osqueryPullRequestOSX/888/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit db065fb7c1679b8d30cfb616c81ddd3e0aa09223 (Job results: [889](https://jenkins.osquery.io/job/osqueryPullRequestOSX/889/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit db065fb7c1679b8d30cfb616c81ddd3e0aa09223 (Job results: [4748](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4748/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 0a9ddfab41f04037b7804f5d27a7834f47bba289 (Job results: [890](https://jenkins.osquery.io/job/osqueryPullRequestOSX/890/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 5dc4f133b9231bc5f78d222a195248c0943f50e7 (Job results: [4750](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4750/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5dc4f133b9231bc5f78d222a195248c0943f50e7 (Job results: [4751](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4751/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
test freebsd please

**Comment by osqueryer** [comment]
:-1: The commit b2f64840f0471f3c22ea1d619d548da1fd16f6b4 (Job results: [4752](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4752/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit b2f64840f0471f3c22ea1d619d548da1fd16f6b4 (Job results: [4753](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4753/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit b2f64840f0471f3c22ea1d619d548da1fd16f6b4 (Job results: [28](https://jenkins.osquery.io/job/osqueryPullRequestLinux/28/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
test freebsd please

**Pull request merged**
