### PR TITLE
fixed error when wrong directory separator was used for parent_directory function

### PR DESCRIPTION
**Pull request by mkareta**
Before this PR getParentDirectory was using wrong separation symbol :(

### CODE REVIEW

**Comment by akindyakov** [comment]
Looks good 👍

**Comment by theopolis** [comment]
I think these path separators are also defined in boost (or maybe osquery)?

**Comment by theopolis** [comment]
I’d also recommend using the osquery file system wrappers (maybe in another commit). Boost APIs will throw exceptions when there’s an error and there are several error states with filesystem APIs; if the CWD becomes unreadable what do you expect these methods to do? Right now they will throw exceptions, caught at the table-execution layer, which may be fine, just an FYI

**Comment by mkareta** [comment]
filesystem interactions are most expensive part in that part of code, using osquery::filesystem will hurt performance a lot, because its not exposing file status and I will need to do 2x more IO for same result

**Pull request merged**
