### PR TITLE
windows: Fixing INFO verbosity in drivers table and various resharper lints

### PR DESCRIPTION
**Pull request by poppyseedplehzr**
This fixes numerous resharper lint issues, but most importantly the `drivers` table was spewing the following message on query due to an incorrect return value check:
```
...
I0524 21:48:42.050192  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.054209  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.058182  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.062187  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.066190  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.072209  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.079238  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.087190  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.091190  4468 drivers.cpp:60] QueryServiceConfig failed (122)
...
```

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit bf215fc5aa8ea9a6cab28a398ceef2023959726e (Job results: [957](https://jenkins.osquery.io/job/osqueryPullRequestOSX/957/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit bf215fc5aa8ea9a6cab28a398ceef2023959726e (Job results: [958](https://jenkins.osquery.io/job/osqueryPullRequestOSX/958/)) failed one or more tests (**macOS/OS X**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit bf215fc5aa8ea9a6cab28a398ceef2023959726e (Job results: [959](https://jenkins.osquery.io/job/osqueryPullRequestOSX/959/)) failed one or more tests (**macOS/OS X**).

**Pull request merged**
