### PR TITLE
Add bitlocker_info to Windows

### PR DESCRIPTION
**Pull request by jjerger**
I've written a query and table spec to allow querying of some basic bitlocker info.

First pull request so please let me know if any formatting/styling is needed. I plan to add more going forward once I can confirm I'm following the right guidelines.

### CODE REVIEW

**Comment by muffins** [comment]
@jjerger thanks for contributing! Looks like although your org has signed the CLA you might need to also sign the individual? @theopolis do you know if CLAs signed by orgs can work for the individuals?

**Comment by theopolis** [comment]
@jjerger is not part of the Google GitHub organization. The CLA will need to be signed individually, or you can email me at reed@fb.com and I can manually verify.

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit f94e20d371d4d8532d6885f2eafdcba39259a017 (Job results: [3071](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3071/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit 10672d1dd135ecbd1b70a378302fc43349279369 (Job results: [3073](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3073/)) failed the code audit or documentation test.

**Comment by jjerger** [comment]
Made requested changes. I'll email Teddy for verification of the organization as well.

**Comment by muffins** [comment]
Looks like your code also needs a `clang-format` run. It should be in your path if you've provisioned, you can run `clang-format -i osquery/tables/system/windows/bitlocker_info.cpp`

**Comment by jjerger** [comment]
Ignore that last - I was fixing a broken git config and pushed to this on accident.

**Comment by osqueryer** [comment]
:no_good: The commit 34819dbf4a6b07c6ff22b0d65b9628fbf2e9304c (Job results: [3074](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3074/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 34819dbf4a6b07c6ff22b0d65b9628fbf2e9304c (Job results: [3375](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3375/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 34819dbf4a6b07c6ff22b0d65b9628fbf2e9304c (Job results: [3376](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3376/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:no_good: The commit 930e54a37062a7fc7b0b900b62c5eb68994be1d8 (Job results: [3075](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3075/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit ee2a6f274ef795afeafbe5568618a489faa22485 (Job results: [3076](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3076/)) failed the code audit or documentation test.

**Comment by obelisk** [comment]
Almost there: https://jenkins.osquery.io/job/osqueryPullRequestAudit/3076/TargetSystem=aws-ubuntu-16.04/console

**Comment by osqueryer** [comment]
:no_good: The commit 68821b15514aeb593b8ddddecc13e0e7e8b39725 (Job results: [3079](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3079/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 68821b15514aeb593b8ddddecc13e0e7e8b39725 (Job results: [6499](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6499/)) failed one or more tests (**Linux**).

**Comment by obelisk** [comment]
```
[+] clang-format (/usr/local/osquery/bin/clang-format) version: clang-format version 5.0.1 (tags/RELEASE_501/final)
changed files:
    osquery/tables/system/windows/bitlocker_info.cpp
diff --git a/osquery/tables/system/windows/bitlocker_info.cpp b/osquery/tables/system/windows/bitlocker_info.cpp
index 5a289fa..1fac65f 100644
--- a/osquery/tables/system/windows/bitlocker_info.cpp
+++ b/osquery/tables/system/windows/bitlocker_info.cpp
@@ -44,5 +44,5 @@ QueryData genBitlockerInfo(QueryContext& context) {
   results.push_back(r);
   return results;
 }
-} //namespace tables
-} //namespace osquery
+} // namespace tables
+} // namespace osquery
```

**Pull request merged**
