### PR TITLE
RPM packages now follow the form name-version-rev.platform.arch.rpm

### LINKED ISSUE #2547: packages: The CentOS 6/7 package names should be name-version-rev.platform.arch.rpm
Problem: we produce package names using `make packages` for CentOS with the form:
```
osquery-1.8.2-150-g123457.rpm
```

These should be:
```
osquery-1.8.2_150_g123457-1.el6.x86_64.rpm
```
Or `el7` if building on CentOS7. The only difference between the two builds is EL7 is packaged with a systemd service and EL6 is packaged with an init-script.

The good news is that the package metadata is already correct. :)

CMake logic: https://github.com/facebook/osquery/blob/master/CMake/Packages.cmake
Package build script for Linux: https://github.com/facebook/osquery/blob/master/tools/deployment/make_linux_package.sh

### PR DESCRIPTION
**Pull request by rogeliodh**
Fixes #2547 

Example package names:

osquery-1.8.2-166-gb895c6a-1.el7.x86_64.rpm  
osquery-debuginfo-1.8.2-166-gb895c6a-1.el7.x86_64.rpm
osquery_1.8.2-166-gb895c6a_amd64.deb  
osquery-dbg_1.8.2-166-gb895c6a_amd64.deb

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by mtmcgrew** [comment]
ok to test

**Pull request merged**
