### PR TITLE
Windows Daemon/Shell: Install and link to new prerequisites

### PR DESCRIPTION
**Pull request by artemdinaburg**
Update the Windows provision script to install new required packages on Windows (cpp-netlib and linenoise-ng), and update CMakeLists to link to them ( #2007 ).

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2183/merge (Job: 2769) failed :-1:

**Comment by PoppySeedPlehzr** [comment]
I built and veified testing on Centos 6.5 x64. Looks like somethings flaky.

**Comment by marpaia** [comment]
@PoppySeedPlehzr you can always say "ok to test" again if the tests fail and it will re-run the tests

**Pull request merged**
