### PR TITLE
Enable CircleCI builds

### PR DESCRIPTION
**Pull request by fmanco**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 4e3fbc149405106dffdb10e8c42b2ed2408aad7b (Job results: [3651](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3651/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 4e3fbc149405106dffdb10e8c42b2ed2408aad7b (Job results: [3652](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3652/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 4e3fbc149405106dffdb10e8c42b2ed2408aad7b (Job results: [6758](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6758/)) failed one or more tests (**Linux**).

**Comment by fmanco** [comment]
Let's close this for now since I'm not really working on it.

**Pull request closed without merging**
