### PR TITLE
[#2544] Fix sign-compare warnings in tests

### LINKED ISSUE #2544: Fix sign-compare warnings in tests: osquery/registry/tests/registry_tests.cpp:245
The following compiler warning is generated during most builds:
```
In file included from /home/teddy/git/osquery/osquery/registry/tests/registry_tests.cpp:11:
/home/teddy/git/osquery/third-party/gtest-1.7.0/include/gtest/gtest.h:1448:16: warning: comparison of integers of different signs: 'const unsigned long' and 'const int' [-Wsign-compare]
  if (expected == actual) {
      ~~~~~~~~ ^  ~~~~~~
/home/teddy/git/osquery/third-party/gtest-1.7.0/include/gtest/gtest.h:1484:12: note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<unsigned long, int>' requested here
    return CmpHelperEQ(expected_expression, actual_expression, expected,
           ^
/home/teddy/git/osquery/osquery/registry/tests/registry_tests.cpp:245:3: note: in instantiation of function template specialization 'testing::internal::EqHelper<false>::Compare<unsigned long, int>' requested here
  EXPECT_EQ(RegistryFactory::getModule(), 0);
  ^
/home/teddy/git/osquery/third-party/gtest-1.7.0/include/gtest/gtest.h:1979:53: note: expanded from macro 'EXPECT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                                                  ^
1 warning generated.
```

These warnings should be treated as errors, but we should at least fix this comparison.

Something like:
```cpp
EXPECT_EQ(0U, RegistryFactory::getModule());
```
will do the trick!

If you've never compiled/tested osquery before start here: http://osquery.readthedocs.io/en/stable/development/building/

### PR DESCRIPTION
**Pull request by xinan**
Fixes #2544

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by theopolis** [comment]
ok to test

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by theopolis** [comment]
Thanks @xinan!

**Pull request merged**
