### PR TITLE
C++ conformance fixes (MSVC /permissive-)

### PR DESCRIPTION
**Pull request by Rastaban**
We (the MSVC compiler team) use the OSQuery project as part of our
"Real world code" tests.  I noticed a few places in your windows
specific code where your build would fail if you used the
/permissive- switch because of language conformance issues.
for more information on /permissive- see our blogpost:
https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/
I have not added/modified any tests because this does not change
behavior.

There are two types of language conformance issues fixed in this:

1) Strict string conversion (this is also covered by the /Zc:strictStrings flag)
The 'const' is not implicitly dropped by string literals, which means the following is not allowed:

    //BSTR is a wchar_t*
    BSTR str = L"const string literal"; //error: cannot convert a 'const wchar_t*' to a 'wchar_t*'

I preserved your current behavior by adding a cast to BSTR.  A better fix
would probably be to use SysAllocString (see the documentation for BSTR on MSDN).
I did not make that change because of my limited testing capabilities.

2)Fully qualified inline declarations members inside class

    struct A {
        void A::f() { } // Error: illegal qualified name in member declaration, remove redundant 'A::' to fix
    };

### CODE REVIEW

**Comment by theopolis** [comment]
Thanks @Rastaban! This is really helpful. Perhaps we should add those compiler flags/switches to the CMake logic too: https://github.com/facebook/osquery/blob/master/osquery/CMakeLists.txt#L23?

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 69825d981fa35ab986f0d1c754b00507a4f5be9b (Job results: [863](https://jenkins.osquery.io/job/osqueryPullRequestAudit/863/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
The **Code Audit** job is asking for two style changes:
```
[+] Running: make format
[+] clang-format (/usr/local/osquery/bin/clang-format) version: clang-format version 3.8.1 (tags/RELEASE_381/final)
changed files:
    osquery/core/windows/wmi.h
    osquery/tables/networking/windows/win_sockets.h
diff --git a/osquery/core/windows/wmi.h b/osquery/core/windows/wmi.h
index 7590913..91ab2d2 100644
--- a/osquery/core/windows/wmi.h
+++ b/osquery/core/windows/wmi.h
@@ -160,7 +160,8 @@ class WmiResultItem {
 */
 class WmiRequest {
  public:
-  explicit WmiRequest(const std::string& query, BSTR nspace = (BSTR)L"ROOT\\CIMV2");
+  explicit WmiRequest(const std::string& query,
+                      BSTR nspace = (BSTR)L"ROOT\\CIMV2");
   WmiRequest(WmiRequest&& src);
   ~WmiRequest();
 
diff --git a/osquery/tables/networking/windows/win_sockets.h b/osquery/tables/networking/windows/win_sockets.h
index 6e5af65..2a917a3 100644
--- a/osquery/tables/networking/windows/win_sockets.h
+++ b/osquery/tables/networking/windows/win_sockets.h
@@ -47,8 +47,7 @@ class WinSockets : private boost::noncopyable {
   MIB_UDP6TABLE_OWNER_PID* udp6Table_ = nullptr;
 
   /// Helper function to allocate a table based off of family and protocol
-  void* allocateSocketTable(unsigned long protocol,
-                            unsigned long family);
+  void* allocateSocketTable(unsigned long protocol, unsigned long family);
 };
 }
 }
```

**Comment by osqueryer** [comment]
:no_good: The commit e38ccc005245cd213c9d7d53772d1cf911ba8c43 (Job results: [872](https://jenkins.osquery.io/job/osqueryPullRequestAudit/872/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit e38ccc005245cd213c9d7d53772d1cf911ba8c43 (Job results: [3903](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3903/)) failed one or more tests (**Linux**).

**Comment by Rastaban** [comment]
@theopolis  am working with Boost and the Windows SDK team to fix similar issues in code that your project depends on.  You may want to wait for them before you add /permissive- to your build.

**Comment by Rastaban** [comment]
The code audit failure and the Linux test failure look like an issue with git checkout

   > git checkout -f 51d3e8501abc75259a043d030dba1c006e6ed492
    FATAL: Could not checkout 51d3e8501abc75259a043d030dba1c006e6ed492

See both console output logs:
 https://jenkins.osquery.io/job/osqueryPullRequestAudit/872/TargetSystem=aws-ubuntu-16.04/console
 https://jenkins.osquery.io/job/osqueryPullRequestLinux/3903/TargetSystem=aws-centos-6/console
Can I get someone to take a look at that and let me know what I need to do?

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Jenkins likes to stir things up sometimes. ;)

**Pull request merged**
