### PR TITLE
Use safeStrtoll instead of strtol

### PR DESCRIPTION
**Pull request by jkeljo**
Addressing a late comment on #4204, fixing the data type while I'm at it.

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [3561](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3561/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [6664](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6664/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [3562](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3562/)) failed one or more tests (**Windows**).

**Comment by jkeljo** [comment]
Test failures look spurious to me, but I'm new here...

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [3570](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3570/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [3571](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3571/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [6679](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6679/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [6681](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6681/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [1239](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1239/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [2802](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2802/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit d29c550da6d10561128d016990e1ba63421e952d (Job results: [3288](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3288/)) failed the code audit or documentation test.

**Pull request merged**
