### PR TITLE
Refactor legacy runtime

### PR DESCRIPTION
**Pull request by theopolis**
This added zlib-legacy and reorganizes the legacy runtime directory to handle any formula install. As part of this we move xz and libgpg-error after the GCC install.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 83d9d52844ead7b33156432d5dd5c53fdd0b2551 (Job results: [3256](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3256/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit af882192e092181c76e5cf73a04fc309e90c3a1d (Job results: [3257](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3257/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-1** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/af882192e092181c76e5cf73a04fc309e90c3a1d..54d6f6826d7117c00f0f9b55a45b2053fe73b307)

**Comment by osqueryer** [comment]
:-1: The commit 54d6f6826d7117c00f0f9b55a45b2053fe73b307 (Job results: [3259](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3259/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by facebook-github-bot-7** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/54d6f6826d7117c00f0f9b55a45b2053fe73b307..88fc7b22ec90dc3a7fd7ff6174883032466c8c84)

**Comment by facebook-github-bot-1** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/88fc7b22ec90dc3a7fd7ff6174883032466c8c84..87f2437a04b061f51d08304b83b19a50bd52c543)

**Comment by osqueryer** [comment]
:-1: The commit 87f2437a04b061f51d08304b83b19a50bd52c543 (Job results: [3262](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3262/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 87f2437a04b061f51d08304b83b19a50bd52c543 (Job results: [3264](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3264/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-7** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/87f2437a04b061f51d08304b83b19a50bd52c543..749edbd71ef5e1b9a2aa975cc219e7672edf7efe)

**Comment by osqueryer** [comment]
:-1: The commit 749edbd71ef5e1b9a2aa975cc219e7672edf7efe (Job results: [3265](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3265/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by facebook-github-bot-6** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/749edbd71ef5e1b9a2aa975cc219e7672edf7efe..30cafc1ab37dcfb13d2145059d1724be3c45653e)

**Comment by facebook-github-bot-5** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/30cafc1ab37dcfb13d2145059d1724be3c45653e..97df4fbb84bb1c49bd7489761d64f6e8d99f1084)

**Comment by facebook-github-bot-2** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/97df4fbb84bb1c49bd7489761d64f6e8d99f1084..d20f7b1ee89e2b3617188026f517bf9ca99b2536)

**Comment by osqueryer** [comment]
:-1: The commit d20f7b1ee89e2b3617188026f517bf9ca99b2536 (Job results: [3269](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3269/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-3** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/d20f7b1ee89e2b3617188026f517bf9ca99b2536..c977cfaf75bfd0a45fa18965db1288d526369c20)

**Comment by theopolis** [comment]
Ok, finally tracked this down to a `brew` inconsistency(??) the `link` and `unlink` commands do not like path arguments. We use the full formula path for our local formulas to assure no conflicts with similarly-named upstream formulas.

I am making an exception for our `*-legacy` formulas since there is low probability of conflict. We are already introducing an edge-case for unlinking/link to handle backwards compatibility due to an oversight on my part.

**Comment by osqueryer** [comment]
:-1: The commit c977cfaf75bfd0a45fa18965db1288d526369c20 (Job results: [3271](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3271/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit c977cfaf75bfd0a45fa18965db1288d526369c20 (Job results: [3272](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3272/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-3** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/c977cfaf75bfd0a45fa18965db1288d526369c20..70ed94075c7f2b2803907a11de59ffad94d1704e)

**Comment by facebook-github-bot-0** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2473/files/70ed94075c7f2b2803907a11de59ffad94d1704e..57f55e060f728ea78f46f82e42edf92eb964350e)

**Comment by theopolis** [comment]
Ok, I have confidence this will work for those upgrading and for those just installing.

**Pull request merged**
