### PR TITLE
rocksDB simplify

### PR DESCRIPTION
**Pull request by guliashvili**
unnecessary private variables moved to functions.
Find method replaced by std::find

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [7371](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7371/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [3329](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3329/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [4276](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4276/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [4280](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4280/)) failed one or more tests (**Windows**).

**Comment by guliashvili** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [4287](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4287/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [4288](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4288/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [3335](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3335/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [7378](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7378/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 84e03b83164dabf6fa0f21c55ed070abf6061308 (Job results: [3336](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3336/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 5a7a99ae57684c675855db9b7e3c96524f842237 (Job results: [4291](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4291/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5a7a99ae57684c675855db9b7e3c96524f842237 (Job results: [4292](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4292/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5a7a99ae57684c675855db9b7e3c96524f842237 (Job results: [7380](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7380/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5a7a99ae57684c675855db9b7e3c96524f842237 (Job results: [7381](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7381/)) failed one or more tests (**Linux**).

**Comment by guliashvili** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 5a7a99ae57684c675855db9b7e3c96524f842237 (Job results: [4293](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4293/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5a7a99ae57684c675855db9b7e3c96524f842237 (Job results: [4294](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4294/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 79a7369016ada440e08707a139d39438c40c7653 (Job results: [4301](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4301/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 79a7369016ada440e08707a139d39438c40c7653 (Job results: [4302](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4302/)) failed one or more tests (**Windows**).

**Comment by guliashvili** [comment]
Ok to test

**Pull request merged**
