### PR TITLE
Fix commented out code on impl_fbthrift

### PR DESCRIPTION
**Pull request by fmanco**

### CODE REVIEW

**Comment by fmanco** [comment]
@theopolis I'm actually not sure what to do here. This was of course making the process crash if compiled with `fbthrift` but I'm not sure why it was commented out in the first place or whether this is the right solution.

**Comment by osqueryer** [comment]
:-1: The commit b2a51f6d9347f47c8ba39c4804770e59e32d09fa (Job results: [3850](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3850/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
@fmanco, this was left over from a 2-step port (1) get the code building with fbthrift, (2) make sure we have test and feature parity. Step 1 was placed in Github and 2 was in fbcode to move fast. Now with #4312 this is solved. "syncing" into fbcode should be straightforward now.

**Comment by theopolis** [comment]
^ my bad :'(

**Pull request closed without merging**
