### PR TITLE
Adding warning text if the system is not configured

### PR DESCRIPTION
**Pull request by marpaia**
See #785 for context. If you don't have a properly configured system,
osqueryd will print a convenient warning with instructions.

### CODE REVIEW

**Comment by marpaia** [comment]
image

**Comment by marpaia** [comment]
screen shot 2015-02-24 at 1 22 09 pm

**Comment by r3doubt** [comment]
I didn't see this warning appear with that error.  Also changing the path for pidfile doesn't seem to work.  You have to just create the expected /var/osquery path.  This is an issue with Brew installs of 3.1.0.

**Comment by diego898** [comment]
I also didnt see an error/warning when installing with homebrew. After installing, what file do I need to create, where, and with what content? Is there a sample somewhere?

**Pull request merged**
