### PR TITLE
Add ability to provision Arch Linux

### PR DESCRIPTION
**Pull request by tonylambiris**
This will install the necessary packages. I had issues compiling which I was able to get around with the following diff (not included in the pull request):

```
00:20:17 tenforward (arch-linux-provisioner) ~/Documents/Git/osquery $ git diff
diff --git a/osquery/remote/transports/tls.cpp b/osquery/remote/transports/tls.cpp
index 4273293..f181af9 100644
--- a/osquery/remote/transports/tls.cpp
+++ b/osquery/remote/transports/tls.cpp
@@ -30,12 +30,12 @@ SSL_CTX* TLSv1_2_method(void) { return nullptr; }
 SSL_CTX* TLSv1_2_server_method(void) { return nullptr; }
 #endif
 #if defined(NO_SSL_TXT_SSLV3)
-SSL_METHOD* SSLv3_server_method(void) { return nullptr; }
-SSL_METHOD* SSLv3_client_method(void) { return nullptr; }
-SSL_METHOD* SSLv3_method(void) { return nullptr; }
-SSL_METHOD* SSLv2_server_method(void) { return nullptr; }
-SSL_METHOD* SSLv2_client_method(void) { return nullptr; }
-SSL_METHOD* SSLv2_method(void) { return nullptr; }
+const SSL_METHOD* SSLv3_server_method(void) { return nullptr; }
+const SSL_METHOD* SSLv3_client_method(void) { return nullptr; }
+const SSL_METHOD* SSLv3_method(void) { return nullptr; }
+const SSL_METHOD* SSLv2_server_method(void) { return nullptr; }
+const SSL_METHOD* SSLv2_client_method(void) { return nullptr; }
+const SSL_METHOD* SSLv2_method(void) { return nullptr; }
 #endif
 #endif
 }
diff --git a/osquery/remote/transports/tls.h b/osquery/remote/transports/tls.h
index 751c416..55038dc 100644
--- a/osquery/remote/transports/tls.h
+++ b/osquery/remote/transports/tls.h
@@ -27,9 +27,9 @@
 /// Newer versions of LibreSSL will lack SSL methods.
 extern "C" {
 #if defined(NO_SSL_TXT_SSLV3)
-SSL_METHOD* SSLv3_server_method(void);
-SSL_METHOD* SSLv3_client_method(void);
-SSL_METHOD* SSLv3_method(void);
+const SSL_METHOD* SSLv3_server_method(void);
+const SSL_METHOD* SSLv3_client_method(void);
+const SSL_METHOD* SSLv3_method(void);
 #endif
 void ERR_remove_state(unsigned long);
 }

```

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by theopolis** [comment]
Hi @tonylambiris! Thanks for this, we'll need to have the Facebook CLA signed before we can test or merge.

For the diff about OpenSSL symbol defines, I'm starting to hit that more often too. There's a dependency build redesign in the works that should clear it up. :)

**Comment by tonylambiris** [comment]
@theopolis I definitely signed the SLA almost right after creating the pull request, is my username not showing up?

**Comment by theopolis** [comment]
Sorry about that, seems everything is in working order by the Facebook Github bots are labeling this PR correctly.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2215/merge (Job: 2840) is good! :+1:

**Pull request merged**
