### PR TITLE
Remove `safeStrtoll` from conversions.h and change all use cases to `tryTo<>`

### PR DESCRIPTION
**Pull request by akindyakov**
Also, I've used a throwing `std::stoll` in tests. Because the tests should not be exception safety and must fail if something goes wrong.

### CODE REVIEW

**Comment by jkeljo** [comment]
Why not `to<>` in tests, just for the sake of consistency?

**Comment by akindyakov** [comment]
@jkeljo , that's a good question! As far as osquery has no exceptions we have created a class `Expected` to return value-or-error from every function which can fail. For that reason, we've reimplemented conversion functions from `safeStrto*` to `tryTo`. But we haven't implemented `to<>` generic for throwing conversions. So, to be consistent we don't have a proper generic. And I'm not sure that we need it only for the tests. Does it make sense?

**Comment by akindyakov** [comment]
@muffins , eventually I think yes. I am going to clean up a bit `conversion.h` file.

**Comment by akindyakov** [comment]
Thank you for the review!

**Pull request merged**
