### PR TITLE
osquery python module

### PR DESCRIPTION
**Pull request by marpaia**
Extreme work in progress.

# TODO

- [ ] figure out some tomfoolery with thrift autogenerating and merging thrift code
- [ ] write a correct setup.py
- [ ] write proper unit tests
- [ ] add a de-register API
- [ ] example plugin/python-extension code

# notes

If you want to try this, run the following from the root of the repo to generate the thrift, at least until the TODO of figuring that out properly in setup.py / cmake is complete.

```
thrift -gen py -out /tmp osquery.thrift
cp -r /tmp/osquery/extensions python/osquery
```

### CODE REVIEW

**Comment by marpaia** [comment]
From @theopolis in #876:

> Looks great!

> A couple of default assumptions:

> - We should be able to call register_plugin, and a similar deregister_plugin at anytime during the extension's execution.
> - start_extension blocks until the process ends.
> - There's quite a bit of python code required to manage the call API in the extension interface.

**Comment by marpaia** [comment]
@theopolis 

- WRT to deregister, good call. I can add an api call for that.
- Yes, the start_extension() call will block, I debated on this a bit. I could also add a `start_extension_background()`? Or would that be something better left for the user to control?

**Comment by Jonty** [comment]
Initial feedback:
* Too much is happening in start_extension() - I'd like to be able to use a Thrift server of my choosing so I can swap in a Twisted/Gevent/Tornado compatible version.
* I'd like to be able to use anonymous functions & function references when setting up plugins at runtime, e.g.
````
table_ref = osquery.register_table(
    name='time', 
    columns=[osquery.TableColumn(name="now", type=osquery.INTEGER)],
    lambda context: return [int(time.time())]
)
````
* Similarly, I'd like to be able to unregister them
````
osquery.unregister_table(table_ref)
````

Going to play with this now, will get back to you with more feedback (and possibly pull requests :P).

Thanks so much for publishing this, I was going to end up writing it myself otherwise!

**Comment by Jonty** [comment]
Quick followup:
* Had to fix a minor error - ExtensionStatus doesn't have a "status" field on line 93 of __init__.py, it should be "message".
* I am receiving pings, but I can't see my registered table in osqueryi.
* The extension is listed in the osquery_extensions table though.

**Comment by marpaia** [comment]
@Jonty thanks for all of the feedback. WRT to osqueryi, that's a KP, we're working on it: #1018

WRT to substituting a different server, I feel like we should definitely support a little more flexibility here.

**Comment by marpaia** [comment]
@jonty, can you elaborate more on the lambda tomfoolery from above:

```python
table_ref = osquery.register_table(
    name='time', 
    columns=[osquery.TableColumn(name="now", type=osquery.INTEGER)],
    lambda context: return [int(time.time())]
)
```

So `lambda context: return [int(time.time())]` is implementing the time table right? If so, it would have to be something more like `[{"unix_time": time.time()}]` since the data must match `osquery::QueryData` (a list of dictionaries).

Are there significant advantages to being able to write tables this way? At a cursory glance, it seems like lambdas wouldn't be usable for anything other than toy tables, but I could be totally wrong there (I generally never use lambdas in python (or c++ for that matter) so I really don't know how powerful they are / if they would be useful here). Any additional context would be awesome.

**Comment by Jonty** [comment]
@marpaia Sure!

My specific use cases for being able to pass in a function reference is to hot-load tables for previously unknown sources, or being able to wrap hot-loaded functions to map their data to something osquery-friendly.

That said its also possible to do this by having a wrapper class populated with the function/data at runtime, then passed to osquery.register_plugin, and if you wanted that to be the only method for registering tables at runtime I don't think I'd have a huge problem with it.

One of the first projects I'm playing with is making a bridge that presents [Diamond](https://github.com/BrightcoveOS/Diamond) collectors as osquery tables, so I'm toying with the best approach.

**Comment by marpaia** [comment]
After thinking about it a bit and chatting with the team, we're not going to support users running their own servers here. The only way to use the extensions API is with a very specific thrift setup and we don't allow changing it in C++, so we shouldn't here either.

**Comment by theopolis** [comment]
Can someone fill me in on what submitting to a different server (I assume service thread responding to the ping, call, query, registerExtension APIs) would mean? And what advantage something other than a Thrift service thread provides?

I'd be happy to explore what it would take, but thrift + UNIX domain socket for extensions is a very safe mechanism. Extending the osquery processes capabilities otherwise seems dangerous and might involve some sort of intermediate brokering integration. Maybe I'm thinking too hard about this or I'm going down the wrong direction. :P

**Comment by marpaia** [comment]
We're making moves. The new repo is up, final development is going to occur there. Check out the new PR for more info: https://github.com/osquery/python/pull/1/

**Pull request closed without merging**
