### PR TITLE
deps: Patch to resolve rack aliases on Linux

### PR DESCRIPTION
**Pull request by theopolis**
This resolves https://github.com/Linuxbrew/brew/issues/315

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 3c85afe45228dda1a3bb49ab52c80cdb4989e09a (Job results: [1251](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1251/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 3c85afe45228dda1a3bb49ab52c80cdb4989e09a (Job results: [4342](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4342/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 3c85afe45228dda1a3bb49ab52c80cdb4989e09a (Job results: [551](https://jenkins.osquery.io/job/osqueryPullRequestOSX/551/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 3c85afe45228dda1a3bb49ab52c80cdb4989e09a (Job results: [1252](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1252/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 3c85afe45228dda1a3bb49ab52c80cdb4989e09a (Job results: [4343](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4343/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 3c85afe45228dda1a3bb49ab52c80cdb4989e09a (Job results: [4344](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4344/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d4fae7b7f185ab436a629a8552e1504290aeedc5 (Job results: [1271](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1271/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d4fae7b7f185ab436a629a8552e1504290aeedc5 (Job results: [1272](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1272/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:no_good: The commit d4fae7b7f185ab436a629a8552e1504290aeedc5 (Job results: [1253](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1253/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit d4fae7b7f185ab436a629a8552e1504290aeedc5 (Job results: [4345](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4345/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d4fae7b7f185ab436a629a8552e1504290aeedc5 (Job results: [4346](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4346/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d4fae7b7f185ab436a629a8552e1504290aeedc5 (Job results: [553](https://jenkins.osquery.io/job/osqueryPullRequestOSX/553/)) failed one or more tests (**macOS/OS X**).

**Pull request merged**
