### PR TITLE
add recovery behavior to osqueryd Windows service

### PR DESCRIPTION
**Pull request by jcai1**
Addresses #4200

After `osqueryd --install` the results look as expected: https://i.imgur.com/Q8TAo0D.png

### CODE REVIEW

**Comment by akindyakov** [comment]
ok to test

**Comment by muffins** [comment]
jenkins test windows

**Comment by muffins** [comment]
jenkins test windows

**Comment by muffins** [comment]
jenkins test windows

**Comment by muffins** [comment]
ok to test

**Comment by muffins** [comment]
ok to test

**Comment by muffins** [comment]
Still trying to sort out how to get the Windows builds reporting, I haven't been able to see the build in the jenkins history, @jcai1 apologies for all of the spam :( Going to try closing and re-opening

**Comment by muffins** [comment]
@jcai1 would you mind rebasing your commit off of master and pushing? `git pull --rebase upstream master; git push -f origin master`?

**Comment by jcai1** [comment]
@muffins I've done as you asked.

**Comment by muffins** [comment]
jenkins test windows

**Comment by muffins** [comment]
jenkins test linux

**Comment by muffins** [comment]
ok to test

**Comment by muffins** [comment]
jenkins test windows

**Pull request merged**
