### PR TITLE
Adding content_caching to sharing_preferences

### LINKED ISSUE #4698: sharing_preferences table is missing content_caching
### What version of `osquery` are you using? What operating system. Be specific.
```
osquery_version = 3.2.6
     os_version = 10.13.6
       os_build = 17G65
    os_platform = darwin
```

### What did you see?
```
     screen_sharing = 0
       file_sharing = 0
    printer_sharing = 0
       remote_login = 1
  remote_management = 1
remote_apple_events = 0
   internet_sharing = 0
  bluetooth_sharing = 0
       disc_sharing = 0
```
### What did you expect to see?
Add 
```
content_caching = [0|1]
```

### PR DESCRIPTION
**Pull request by n8felton**
Fixes #4698

### CODE REVIEW

**Comment by groob** [comment]
@n8felton do you know what the minimum os version is that has content caching? 

Do we need to do any branching to protect against the preference file missing?

**Comment by mkareta** [comment]
ok to test

**Comment by cwhits** [comment]
@groob, output from 10.12.6 (which doesn't have content caching)

```
osquery> select * from sharing_preferences;
     screen_sharing = 0
       file_sharing = 0
    printer_sharing = 0
       remote_login = 1
  remote_management = 0
remote_apple_events = 0
   internet_sharing = 0
  bluetooth_sharing = 0
       disc_sharing = 0
    content_caching = 0
```

**Comment by n8felton** [comment]
@groob Content caching was moved out of Server.app and into macOS starting with 10.13. The function should default to returning 0 if the plist for content caching doesn't exist (which i've tested). @cwhits was kind enough to test on 10.12.6 for me, and I've also tested on a 10.11 VM successfully.

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
