### PR TITLE
Introduce table aliases

### PR DESCRIPTION
**Pull request by theopolis**
Aliases (both column and table) allows us to change table and column names, then explicitly choose to support the old (deprecated) names.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/2104/merge (Job: 2684) is good! :+1:

**Comment by theopolis** [comment]
These changes will implement https://github.com/facebook/osquery/issues/2098.

**Comment by osqueryer** [comment]
Build origin/pr/2104/merge (Job: 2685) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/2104/merge (Job: 2689) is good! :+1:

**Pull request merged**
