### PR TITLE
fix comma in osx attack pack

### PR DESCRIPTION
**Pull request by friedbutter**
fix missing comma in the pack

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [3864](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3864/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [838](https://jenkins.osquery.io/job/osqueryPullRequestAudit/838/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [839](https://jenkins.osquery.io/job/osqueryPullRequestAudit/839/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [3866](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3866/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [3867](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3867/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [840](https://jenkins.osquery.io/job/osqueryPullRequestAudit/840/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [3868](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3868/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [3869](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3869/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
Should have had a dependency on: https://github.com/facebook/osquery/issues/2841

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [3870](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3870/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 52a9cb8764f9617bb2e8d6c62ec7eafb944a665a (Job results: [841](https://jenkins.osquery.io/job/osqueryPullRequestAudit/841/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
The only one I'm concerned about here is `Linux`, that has the release-tests variable set. It's passing some, now that the infra is recovering from the Linuxbrew update.

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
