### PR TITLE
[osquery] Updated copyright headers to new format.

### PR DESCRIPTION
**Pull request by bhamodi**
@theopolis @jamesgpearce - Updated the copyright headers to the new format outlined in our internal wiki.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Nice, thanks Baraa.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1844/merge (Job: 2376) is good! :+1:

**Comment by bhamodi** [comment]
:+1:

**Pull request merged**
