### PR TITLE
Preserve atime and mtime by default for readFile

### PR DESCRIPTION
**Pull request by theopolis**
For most reads, osquery as a forensic tool, should preserve atimes within the filesystem.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
The expected output:
```
~/git/github/osquery (branch:forensic_reads) » ./build/darwin10.11/osquery/osqueryi
osquery - being built, with love, at Facebook
Using a virtual database. Need help, type '.help'
osquery> select * from file where path = '/etc/passwd';
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| path        | directory | filename | inode  | uid | gid | mode | device | size | block_size | atime      | mtime      | ctime      | hard_links | type    | pattern |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| /etc/passwd | /etc      | passwd   | 159639 | 0   | 0   | 0644 | 0      | 5253 | 4096       | 1449885369 | 1449653044 | 1449885383 | 1          | regular |         |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
osquery> select * from hash where path = '/etc/passwd';
+-------------+-----------+----------------------------------+------------------------------------------+------------------------------------------------------------------+
| path        | directory | md5                              | sha1                                     | sha256                                                           |
+-------------+-----------+----------------------------------+------------------------------------------+------------------------------------------------------------------+
| /etc/passwd | /etc      | 5e7f80888f3d491c4963881364048c24 | c0c71bac843a3ec7233e99e123888beb6da8fbcf | 39c487734fed185cf16217552ed8b451525c240e13d41001b3782b46fdcf4708 |
+-------------+-----------+----------------------------------+------------------------------------------+------------------------------------------------------------------+
osquery> select * from file where path = '/etc/passwd';
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| path        | directory | filename | inode  | uid | gid | mode | device | size | block_size | atime      | mtime      | ctime      | hard_links | type    | pattern |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| /etc/passwd | /etc      | passwd   | 159639 | 0   | 0   | 0644 | 0      | 5253 | 4096       | 1449888956 | 1449653044 | 1449885383 | 1          | regular |         |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
osquery> ^D
~/git/github/osquery (branch:forensic_reads) » sudo ./build/darwin10.11/osquery/osqueryi
osquery - being built, with love, at Facebook
Using a virtual database. Need help, type '.help'
osquery> select * from file where path = '/etc/passwd';
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| path        | directory | filename | inode  | uid | gid | mode | device | size | block_size | atime      | mtime      | ctime      | hard_links | type    | pattern |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| /etc/passwd | /etc      | passwd   | 159639 | 0   | 0   | 0644 | 0      | 5253 | 4096       | 1449888956 | 1449653044 | 1449885383 | 1          | regular |         |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
osquery> select * from hash where path = '/etc/passwd';
+-------------+-----------+----------------------------------+------------------------------------------+------------------------------------------------------------------+
| path        | directory | md5                              | sha1                                     | sha256                                                           |
+-------------+-----------+----------------------------------+------------------------------------------+------------------------------------------------------------------+
| /etc/passwd | /etc      | 5e7f80888f3d491c4963881364048c24 | c0c71bac843a3ec7233e99e123888beb6da8fbcf | 39c487734fed185cf16217552ed8b451525c240e13d41001b3782b46fdcf4708 |
+-------------+-----------+----------------------------------+------------------------------------------+------------------------------------------------------------------+
osquery> select * from file where path = '/etc/passwd';
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| path        | directory | filename | inode  | uid | gid | mode | device | size | block_size | atime      | mtime      | ctime      | hard_links | type    | pattern |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
| /etc/passwd | /etc      | passwd   | 159639 | 0   | 0   | 0644 | 0      | 5253 | 4096       | 1449888956 | 1449653044 | 1449888966 | 1          | regular |         |
+-------------+-----------+----------+--------+-----+-----+------+--------+------+------------+------------+------------+------------+------------+---------+---------+
osquery> ^D
~/git/github/osquery (branch:forensic_reads) » 
```

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Pull request merged**
