### PR TITLE
eliminated some warnings from Clang 3.7 analyze mode

### PR DESCRIPTION
**Pull request by rcseacord**
Removed calls to std::move (mostly in return statements) that would prevent copy elision.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by marpaia** [comment]
ok to test

**Comment by osqueryer** [comment]
Build is good! :+1:

**Comment by osqueryer** [comment]
Build is good! :+1:

**Pull request merged**
