### PR TITLE
filesystem: allowing currently executing user to own binary

### PR DESCRIPTION
**Pull request by muffins**
The check for `isUserCurrentUser` on Windows has been failing since the recent overhaul of the relaxation of Safe perms. This fixes an issue I introduced where there was no buffer being passed when we get the current users token to check if they own the file.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 4a1426d6695676b820297160299fe1c2aa217aec (Job results: [2658](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2658/)) failed the code audit or documentation test.

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 4a1426d6695676b820297160299fe1c2aa217aec (Job results: [2660](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2660/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
The code audit failure is my fault. It should be fixed now.

**Comment by muffins** [comment]
Closing this out as the cppchecks don't seem related to this. Can issue a follow up PR fixing some of those.

**Pull request merged**
