### PR TITLE
Update third-party submodules to include gmock

### PR DESCRIPTION
**Pull request by sharvilshah**
Hey @theopolis, since osquery/third-party#2 got merged, I just updated the submodule commit sha. Do you still want me to update `.gitmodules` to point to my own repo?

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
@sharvilshah feel free to add commits to this PR or force update the single commit. Jenkins should auto-build your updates.

**Comment by sharvilshah** [comment]
@theopolis I am still working on mock tests (and mainly grokking the docs/experimenting) on other branch. Do you want just a single pull request? If so, I can close this one, and create a new one when I done with the tests (and rebase that work onto this one).

**Comment by sharvilshah** [comment]
I like the idea of a pull request with all logical changes of a feature/bug in it together. Closing this, and will create a new one.

**Comment by theopolis** [comment]
You can update your PRs:

Do work!
git commit --amend
git push BRANCHNAME -f

And Github will update this PR and Jenkins will run tests again.

**Pull request closed without merging**
