### PR TITLE
Move specs to a top-level path, add query examples

### PR DESCRIPTION
**Pull request by theopolis**
1. Example queries will run with an (optional) integration test.
2. Fix bad accesses with OS X package BOMs
3. Move spec files from ./osquery/tables/specs to ./specs
4. Remove server parsers (netlib) from client builds.

### CODE REVIEW

**Comment by marpaia** [comment]
i like the examples! nice.

**Comment by theopolis** [comment]
Going to remove the explicit `select_all()` in examples and the test harness will assume a `select * from {{table_name}}` wont break things.

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
