### PR TITLE
Add dns_resolvers table

### PR DESCRIPTION
**Pull request by theopolis**
Simple libresolv-based DNS resolvers enumeration.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/1834/merge (Job: 2362) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/1834/merge (Job: 2364) is good! :+1:

**Comment by osqueryer** [comment]
Build origin/pr/1834/merge (Job: 2365) is good! :+1:

**Comment by theopolis** [comment]
I'm not sure if anyone uses the `sortlist` features of `resolv.conf`. I may remove them. I haven't been able to get `search` to pick up the list of search domains either. On OS X the `domain` option is set by DHCP so it might be helpful to add a respective row.

IPv6 on OS X, set through the Networking pane, shows up as a blank address.

**Comment by theopolis** [comment]
The IPv6 comment is wrong, there's only a blank address when using `::1`, otherwise the DHCP-set IPv4 addresses remain. This is confirmed to be reflected in the content of `resolv.conf`-- and withing SC.

**Comment by osqueryer** [comment]
Build origin/pr/1834/merge (Job: 2366) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/1834/merge (Job: 2367) is good! :+1:

**Comment by osqueryer** [comment]
Build origin/pr/1834/merge (Job: 2368) is good! :+1:

**Pull request merged**
