### PR TITLE
tests: Fix compression test failing for Sierra

### LINKED ISSUE #4139: RequestsTests.test_compression fails on MacOS High Sierra
With the update to MacOS High Sierra, filesystems were converted to APFS. When running on top of APFS the OS part of the GZIP header (http://www.zlib.org/rfc-gzip.html#file-format) has a value of `0x13` as opposed to `0x3` as it had before, making this test fail.

We'll need to query either OS version or filesystem to decide on the header value here.

To run the test:
```
build/darwin/osquery/osquery_additional_tests --gtest_filter="RequestsTests.test_compression
```

### PR DESCRIPTION
**Pull request by Ngo-The-Trung**
Fixes #4139

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit a48ccc44934f38c3c4b5a9fa27d78f4f3cf99d3d (Job results: [3577](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3577/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit a48ccc44934f38c3c4b5a9fa27d78f4f3cf99d3d (Job results: [2745](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2745/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit a48ccc44934f38c3c4b5a9fa27d78f4f3cf99d3d (Job results: [3579](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3579/)) failed one or more tests (**Windows**).

**Comment by Ngo-The-Trung** [comment]
Yep it failed

**Comment by osqueryer** [comment]
:-1: The commit a48ccc44934f38c3c4b5a9fa27d78f4f3cf99d3d (Job results: [6688](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6688/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit a48ccc44934f38c3c4b5a9fa27d78f4f3cf99d3d (Job results: [6691](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6691/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit a48ccc44934f38c3c4b5a9fa27d78f4f3cf99d3d (Job results: [2748](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2748/)) failed one or more tests (**macOS/OS X**).

**Comment by Ngo-The-Trung** [comment]
Changes the approach. Just skip that byte when comparing since it's platform dependent.

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3583](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3583/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6694](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6694/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3584](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3584/)) failed one or more tests (**Windows**).

**Comment by fmanco** [comment]
retest this please

**Comment by fmanco** [comment]
I find this approach much better, thanks! Let's just wait for the tests and we should be good to go.

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3587](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3587/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3588](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3588/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6697](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6697/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6699](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6699/)) failed one or more tests (**Linux**).

**Comment by fmanco** [comment]
Jenkins, this is not funny, please stop.. 😭

**Comment by muffins** [comment]
@fmanco  you use `ok to test` to trigger :)

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6706](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6706/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6708](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6708/)) failed one or more tests (**Linux**).

**Comment by fmanco** [comment]
@muffins retest this please should work too I think, but we're having failures due to jenkins not being able to download stuff from github 😢

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6710](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6710/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6711](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6711/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3597](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3597/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3599](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3599/)) failed one or more tests (**Windows**).

**Comment by muffins** [comment]
Yeah the build hosts were bugging out, but they look ok now.

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3605](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3605/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [3606](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3606/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6716](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6716/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 24e66875ed3121726329a4c4ec32b89c5068935e (Job results: [6718](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6718/)) failed one or more tests (**Linux**).

**Comment by fmanco** [comment]
@Ngo-The-Trung we're still working on fixing Jenkins, once that is done I can merge this.

**Pull request merged**
