### PR TITLE
Extending chrome browser extension table to Windows

### PR DESCRIPTION
**Pull request by PoppySeedPlehzr**
This one's a touch big :)

This PR extends the Chrome Browser extensions virtual table, however to get this table up and running I had to fix a bug that existed inside of our globbing functionality. I'm yet uncertain if this modification to the globbing logic fixes the file hash globbing issues discussed in slack, but I'll investigate that next.

Lastly this PR brings in a new test and some slight modifications to the testing directory structure.

### CODE REVIEW

**Comment by PoppySeedPlehzr** [comment]
This PR addresses #2605

**Comment by osqueryer** [comment]
:no_good: The commit 93b73ad3144d08d31e5679c56b31a11122c3f71e (Job results: [487](https://jenkins.osquery.io/job/osqueryPullRequestAudit/487/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 93b73ad3144d08d31e5679c56b31a11122c3f71e (Job results: [3505](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3505/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 93b73ad3144d08d31e5679c56b31a11122c3f71e (Job results: [509](https://jenkins.osquery.io/job/osqueryPullRequestBuild/509/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 39adcca37a36225cde329d480b08f7f7a28c329d (Job results: [3506](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3506/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 39adcca37a36225cde329d480b08f7f7a28c329d (Job results: [510](https://jenkins.osquery.io/job/osqueryPullRequestBuild/510/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 1a847e9d696aed2819d9432e828345843afcaf1f (Job results: [512](https://jenkins.osquery.io/job/osqueryPullRequestBuild/512/)) failed one or more tests (**Windows**).

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 1a847e9d696aed2819d9432e828345843afcaf1f (Job results: [513](https://jenkins.osquery.io/job/osqueryPullRequestBuild/513/)) failed one or more tests (**Windows**).

**Comment by PoppySeedPlehzr** [comment]
Going to go ahead and close this out. I have the build and tests passing on Windows for both my development box, as well as one of our corporate laptops.

**Pull request merged**
