### PR TITLE
[Fix #4304] Fix a memory leak in the sip_config table

### LINKED ISSUE #4304: Possible leak in sip_config
sip_config seems to have an intermittent leak.

Reproduction steps:
Run the leaks profiler as sudo for `select * from sip_config`.

The leak is 55 leaks for 8656 total bytes.

### PR DESCRIPTION
**Pull request by obelisk**
There was an intermittent leak in the SIP config table. It seems to only affect when osquery is running as root (because only root can get the IOMasterPortDefault I believe).

There were two missing release cases which I've fixed as well as a manual definition of "ok" in a status 0.

This is marked as API Change because if `genCsrConfigFromNvram` fails, we will now return `-1` and not `0`. This allows us to distinguish between unset csr values, and a failure to retrieve them.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 98f4576b9d7bfc7ccb656c89b7d5a722449d5b68 (Job results: [6896](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6896/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 98f4576b9d7bfc7ccb656c89b7d5a722449d5b68 (Job results: [6897](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6897/)) failed one or more tests (**Linux**).

**Comment by obelisk** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 98f4576b9d7bfc7ccb656c89b7d5a722449d5b68 (Job results: [6900](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6900/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 98f4576b9d7bfc7ccb656c89b7d5a722449d5b68 (Job results: [6901](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6901/)) failed one or more tests (**Linux**).

**Pull request merged**
