### PR TITLE
Updating README for 10.10 and 10.11

### PR DESCRIPTION
**Pull request by javuto**
Updating README for 10.10 and 10.11, now that there is a CI job for each. The status badge was broken

### CODE REVIEW

**Comment by theopolis** [comment]
I'd go with 1 line and to a "OS X 10/11" then just point it to the 11 build. They are pretty equivalent.

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) is good! :+1:

**Comment by theopolis** [comment]
Remember to `git rebase -i HEAD~2` and squash your commits! Also, FYI you should fork this and create your own branches, then do a PR from your fork's branch into origin's (Facebook).

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) is good! :+1:

**Pull request closed without merging**
