### PR TITLE
FreeBSD provision improvements

### PR DESCRIPTION
**Pull request by lwhsu**

### CODE REVIEW

**Comment by theopolis** [comment]
Are you ready?

**Comment by theopolis** [comment]
ok to test 🤞

**Comment by theopolis** [comment]
ok to test (again!)

**Comment by theopolis** [comment]
screen shot 2017-04-20 at 9 09 34 pm

;)

**Comment by osqueryer** [comment]
:-1: The commit 0275ab2b9ceff3636262afc459cefa506c3fd6f4 (Job results: [2](https://jenkins.osquery.io/job/osqueryPullRequestLinux/2/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
```
[aws-freebsd-11] $ /bin/sh -xe /tmp/jenkins714210416344887250.sh
+ gmake sysprep
[+] found freebsd provision script: /var/jenkins/workspace/osqueryPullRequestFreeBSD/TargetSystem/aws-freebsd-11/tools/provision/freebsd.sh
[+] requesting sudo: pkg update
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
[+] requesting sudo: pkg upgrade -y
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking for upgrades (4 candidates): .... done
Processing candidates (4 candidates): ... done
The following 2 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	firstboot-pkgs: 1.4 -> 1.5

Installed packages to be REINSTALLED:
	firstboot-freebsd-update-1.2 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:11:*')

Number of packages to be upgraded: 1
Number of packages to be reinstalled: 1

3 KiB to be downloaded.
[1/2] Fetching firstboot-pkgs-1.5.txz: . done
[2/2] Fetching firstboot-freebsd-update-1.2.txz: . done
Checking integrity... done (0 conflicting)
[1/2] Upgrading firstboot-pkgs from 1.4 to 1.5...
[1/2] Extracting firstboot-pkgs-1.5: . done
[2/2] Reinstalling firstboot-freebsd-update-1.2...
Extracting firstboot-freebsd-update-1.2: . done
[+] requesting sudo: portsnap fetch update
portsnap fetch should not be run non-interactively.
Run portsnap cron instead
gmake: *** [Makefile:126: sysprep] Error 1
```

**Comment by osqueryer** [comment]
:-1: The commit 0275ab2b9ceff3636262afc459cefa506c3fd6f4 (Job results: [3](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
Ignore the `FreeBSD 11` build, I renamed the job and Github will not receive the correct finish/success/failure API call from Jenkins.

**Comment by lwhsu** [comment]
Thanks, although I do forget that `portsnap fetch` requires an interactive tty. I am thinking:
1. since all the dependencies have pre-built packages now, just comment out using `portsnap` for now, which also saves time and disk space.
2. `portsnap` has a `--interactive` option, but I am not sure it's abusing. I'm checking it.

**Comment by theopolis** [comment]
> since all the dependencies have pre-built packages now, just comment out using portsnap for now, which also saves time and disk space.

We could do that, if we comment and leave a note above about why we don't need it.

**Comment by osqueryer** [comment]
:-1: The commit 1c4c067c61cccae91bfb8d3601446377ed7f69a3 (Job results: [4532](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4532/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
test freebsd please

**Comment by osqueryer** [comment]
:-1: The commit 1c4c067c61cccae91bfb8d3601446377ed7f69a3 (Job results: [4](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
No `rocksdb-lite` PKG available?

**Comment by lwhsu** [comment]
There is rocksdb-lite package available now. Thanks for the merging!

**Pull request merged**
