### PR TITLE
refactor before adding bash_sessions history files to shell_history

### PR DESCRIPTION
**Pull request by jschroth**
This adds logging of history files in the bash_sessions directory on MacOS.

### CODE REVIEW

**Comment by akindyakov** [comment]
Thank you @jschroth , for you contribution!
As far as I can see, you did a nice feature and some refactoring in one PR. May I ask you to separate refactoring and new functionality implementation to different PRs?

**Comment by jschroth** [comment]
@akindyakov updated to just include refactor in this diff

**Comment by akindyakov** [comment]
ok to test

**Comment by akindyakov** [comment]
@jschroth , thank you!

**Pull request merged**
