### PR TITLE
Allow EINTR within ThriftTransport

### PR DESCRIPTION
**Pull request by theopolis**
This patches our bundled Thrift to allow `EINTR`. This does not affect our interruption of the thrift service, but does allow the loop to continue when another of the process's threads drops privilege.

This also "re-enables" a fair bit of testing-- the move to a "posix" category for various tables blinded us to CI execution. We also choose to `SELECT *` from tables without an `examples` in their spec.

### CODE REVIEW

**Comment by theopolis** [comment]
Fixes #2876, #2875.

**Comment by osqueryer** [comment]
:no_good: The commit 1a5fd8379b4ae22ffa316c56d7ff47e5f04d3f59 (Job results: [887](https://jenkins.osquery.io/job/osqueryPullRequestAudit/887/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 1a5fd8379b4ae22ffa316c56d7ff47e5f04d3f59 (Job results: [187](https://jenkins.osquery.io/job/osqueryPullRequestOSX/187/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 1a5fd8379b4ae22ffa316c56d7ff47e5f04d3f59 (Job results: [3919](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3919/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 1a5fd8379b4ae22ffa316c56d7ff47e5f04d3f59 (Job results: [3920](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3920/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit bc62c106b5a3a3715915908ec820d1bc4f49850f (Job results: [3921](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3921/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit bc62c106b5a3a3715915908ec820d1bc4f49850f (Job results: [188](https://jenkins.osquery.io/job/osqueryPullRequestOSX/188/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d30d0828d43efbe7f4b0d7664233f6f1e2ac445c (Job results: [189](https://jenkins.osquery.io/job/osqueryPullRequestOSX/189/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d30d0828d43efbe7f4b0d7664233f6f1e2ac445c (Job results: [3923](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3923/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit c8f6919958afd37b49fa0afe5172106472434e8f (Job results: [3925](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3925/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit c8f6919958afd37b49fa0afe5172106472434e8f (Job results: [190](https://jenkins.osquery.io/job/osqueryPullRequestOSX/190/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit c8f6919958afd37b49fa0afe5172106472434e8f (Job results: [3926](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3926/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 0b9159cf85493c6a17878bf10adeae451f67156f (Job results: [191](https://jenkins.osquery.io/job/osqueryPullRequestOSX/191/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 0b9159cf85493c6a17878bf10adeae451f67156f (Job results: [3927](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3927/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 0b9159cf85493c6a17878bf10adeae451f67156f (Job results: [3928](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3928/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 0b9159cf85493c6a17878bf10adeae451f67156f (Job results: [3929](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3929/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 0b9159cf85493c6a17878bf10adeae451f67156f (Job results: [192](https://jenkins.osquery.io/job/osqueryPullRequestOSX/192/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 0b9159cf85493c6a17878bf10adeae451f67156f (Job results: [3930](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3930/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
Boom:
```
General exception executing query: [1;31mselect * from platform_info limit 1[0m (bad lexical cast: source type value could not be interpreted as target)
  File "/Users/osquery/jenkins/workspace/osqueryPullRequestOSX/TargetSystem/vm-osx12/tools/tests/test_example_queries.py", line 30, in test_cross_platform_queries
    self._execute_set(PLATFORM_EXAMPLES["specs"])

Query (0ms): select * from carbon_black_info limit 1, rows: 1
Query (0ms): select * from chrome_extensions limit 1, rows: 0
Query (0ms): select * from cpuid limit 1, rows: 1
Query (0ms): select * from etc_hosts limit 1, rows: 1
Query (5ms): select * from etc_protocols limit 1, rows: 1
Query (301ms): select * from etc_services limit 1, rows: 1
Query (2ms): select * from interface_addresses limit 1, rows: 1
Query (2ms): select * from interface_details limit 1, rows: 1
Query (2ms): select * from kernel_info limit 1, rows: 1
Query (1ms): select * from listening_ports limit 1, rows: 1
Query (0ms): select * from os_version limit 1, rows: 1
General exception executing query: [1;31mselect * from platform_info limit 1[0m (bad lexical cast: source type value could not be interpreted as target)
  File "/Users/osquery/jenkins/workspace/osqueryPullRequestOSX/TargetSystem/vm-osx12/tools/tests/test_example_queries.py", line 30, in test_cross_platform_queries
    self._execute_set(PLATFORM_EXAMPLES["specs"])

Query (0ms): select * from carbon_black_info limit 1, rows: 1
Query (0ms): select * from chrome_extensions limit 1, rows: 0
Query (0ms): select * from cpuid limit 1, rows: 1
Query (0ms): select * from etc_hosts limit 1, rows: 1
Query (4ms): select * from etc_protocols limit 1, rows: 1
Query (301ms): select * from etc_services limit 1, rows: 1
Query (1ms): select * from interface_addresses limit 1, rows: 1
Query (3ms): select * from interface_details limit 1, rows: 1
Query (1ms): select * from kernel_info limit 1, rows: 1
Query (1ms): select * from listening_ports limit 1, rows: 1
Query (0ms): select * from os_version limit 1, rows: 1
General exception executing query: [1;31mselect * from platform_info limit 1[0m (bad lexical cast: source type value could not be interpreted as target)
  File "/Users/osquery/jenkins/workspace/osqueryPullRequestOSX/TargetSystem/vm-osx12/tools/tests/test_example_queries.py", line 30, in test_cross_platform_queries
    self._execute_set(PLATFORM_EXAMPLES["specs"])
```

**Comment by osqueryer** [comment]
:-1: The commit 1194e3d4b3751faa228f7399ae6d2cb0c58d7b03 (Job results: [193](https://jenkins.osquery.io/job/osqueryPullRequestOSX/193/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 1194e3d4b3751faa228f7399ae6d2cb0c58d7b03 (Job results: [3931](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3931/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 1194e3d4b3751faa228f7399ae6d2cb0c58d7b03 (Job results: [3932](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3932/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit c50d1035506dea0358deed21f2fb7d75736220a0 (Job results: [3933](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3933/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit c50d1035506dea0358deed21f2fb7d75736220a0 (Job results: [194](https://jenkins.osquery.io/job/osqueryPullRequestOSX/194/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit c50d1035506dea0358deed21f2fb7d75736220a0 (Job results: [3934](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3934/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 87acecee63b80704ec00185f4516aef4cdd8ee4b (Job results: [195](https://jenkins.osquery.io/job/osqueryPullRequestOSX/195/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 87acecee63b80704ec00185f4516aef4cdd8ee4b (Job results: [3935](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3935/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 87acecee63b80704ec00185f4516aef4cdd8ee4b (Job results: [3936](https://jenkins.osquery.io/job/osqueryPullRequestLinux/3936/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 70c6598e99b8f723cca0507982f5c0074be6f1a8 (Job results: [196](https://jenkins.osquery.io/job/osqueryPullRequestOSX/196/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit 70c6598e99b8f723cca0507982f5c0074be6f1a8 (Job results: [896](https://jenkins.osquery.io/job/osqueryPullRequestAudit/896/)) failed the code audit or documentation test.

**Pull request merged**
