### PR TITLE
Make docs build dir within CMake to allow docs/fast

### PR DESCRIPTION
**Pull request by theopolis**

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit ce287be2aaebd9250385efa43d5f55fcd135d610 (Job results: [4](https://jenkins.osquery.io/job/osqueryPullRequestAudit/4/)) failed the code audit.

**Comment by osqueryer** [comment]
:no_good: The commit 5e1b7a83dc8c4fcdb27ce43db6e2030cf2275e29 (Job results: [5](https://jenkins.osquery.io/job/osqueryPullRequestAudit/5/)) failed the code audit.

**Comment by theopolis** [comment]
The auditing job still expects the submodules to be initialized.

**Comment by osqueryer** [comment]
:-1: The commit 5e1b7a83dc8c4fcdb27ce43db6e2030cf2275e29 (Job results: [2973](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2973/)) failed one or more tests.

**Pull request closed without merging**
