### PR TITLE
Logger config

### PR DESCRIPTION
**Pull request by fmanco**
Enable configure() calls on logger plugins.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [3227](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3227/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [1670](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1670/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [3228](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3228/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [1671](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1671/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [4157](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4157/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [7253](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7253/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [7254](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7254/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [4158](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4158/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [1672](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1672/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [7255](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7255/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [7256](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7256/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [3229](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3229/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [1673](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1673/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 91390e3623b0895fba7bb92001a0a6d3415d1dab (Job results: [4159](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4159/)) failed one or more tests (**Windows**).

**Comment by muffins** [comment]
This LGTM. Would you mind updating the PR title to be more descriptive? What you have as the summary text would be good :)

**Comment by fmanco** [comment]
@muffins thanks will do.

**Pull request merged**
