### PR TITLE
Remove CLion files

### PR DESCRIPTION
**Pull request by marpaia**
These files are ten months old, nobody uses CLion on the team to verify
that these still work properly, etc. If someone uses CLion and default
project settings would be useful, please add and maintain new project
files.

### CODE REVIEW

**Comment by sharvilshah** [comment]
I have been using CLion for a bit, and while I am not super familiar with it's project structure files (yet) those default files have been working great. I guess I can just update `.gitignore`.

**Comment by marpaia** [comment]
@sharvilshah feel free to re-commit updated project files, i just wanted to clean it out since they're really out of date, many things may or may not have changed in project configurations.

**Comment by sharvilshah** [comment]
@marpaia Cool thanks. I'll read up on the docs, and update the project files and try to maintain them.
Out of curiosity what do you guys use for the development? The reason CLion stuck is it can download sources and docs for the header files and I don't need to have a browser/man pages open for that.

**Comment by marpaia** [comment]
I'm a pretty religious vim user, personally. @theopolis rocks sublime a lot, although he's been known to be more willing to try new editors than i am :)

**Pull request merged**
