### PR TITLE
bug: do not wait for main service thread before reporting stop to SCM

### PR DESCRIPTION
**Pull request by muffins**
The logic that I had implemented around waiting for thread execution to complete before notifying the SCM of our service stopped state was incorrect. This updates the service thread wait logic to obtain a handle to the main execution thread which is used to wait before sending a `SERVICE_STOPPED` status to the SCM. This should prevent SCM returning error codes of 109, as well as prevent system crashes when the service shuts down. This also turns on tests to ensure that we don't see any exit error code aside from 0 when the service shuts down. Below is some contextual history that we found a way around.

Big shoutout to @ExceptionalHandler for helping me work through what this wait logic should look like, and reporting the issue to us in the first place!

~I messed around with the logic a bit, but found that this was causing errors with the SCM stopping, and as in #4379 this is causing failures when the SCM sends a stop signal. This removes the logic to assure that if nothing else the osquery service fully stops and returns a success exit code to the SCM, as well as adds the integration tests to assure this behavior.~

~That being said, with the lack of waits on the main thread of execution, I have seen occasional crashes of the service as there is the possibility that the main thread of execution is caught on joining the dispatcher threads when we report to SCM that we've stopped, which is causing a SIGABORT. I haven't seen this happen all the time, just when the daemon is under heavy load, and given we're currently "failing" to shut down the service now I think this is the lesser of two evils. I still intend to sort out what the proper shutdown logic needs to look like to ensure the dispatcher finishes joining before we interact with SCM, but so far traditional methodologies like `WaitForSingleObjectEx` on the thread handle, and using a "finished" `SetEvent` call in the main thread have not successfully worked, and just made our SCM service stop failures worse.~

### CODE REVIEW

**Comment by muffins** [comment]
I may have a better solution for this, will have an update shortly!

**Comment by osqueryer** [comment]
:-1: The commit bdfa131acaad51a78fcd3810316804de1c11b7f3 (Job results: [3086](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3086/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit bdfa131acaad51a78fcd3810316804de1c11b7f3 (Job results: [3087](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3087/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit bdfa131acaad51a78fcd3810316804de1c11b7f3 (Job results: [7084](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7084/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 233ba003b2e669de9816fe5aeaecbc2998117a25 (Job results: [3974](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3974/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 96c92c7901bbf2ed9c5909c8b78dc9b0eeffdd7d (Job results: [3980](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3980/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 96c92c7901bbf2ed9c5909c8b78dc9b0eeffdd7d (Job results: [7090](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7090/)) failed one or more tests (**Linux**).

**Pull request merged**
