### PR TITLE
Updating build docs to include make packages

### PR DESCRIPTION
**Pull request by clong**
The package instructions are located on the custom-packages page, but I think it's likely people will want to know how to do this while building from source

### CODE REVIEW

**Comment by theopolis** [comment]
I'm not sure, the `make packages` description is a few sections down. I feel like this is unnecessarily repeating information.

**Comment by obelisk** [comment]
I mostly agree with Ted, we might want to add a line:

'If you need a custom package, see below under `Custom Packages`'

Have the command twice breaks the DRY principal.

**Comment by muffins** [comment]
@clong did you have any follow up on this? Can we close or do we still want this merged in?

**Comment by clong** [comment]
Sorry, I thought this was closed. I agree with @obelisk, the Linux instructions begin with 

> To create a package (e.g. a deb on Ubuntu or an rpm on CentOS), simply spin up a vagrant instance.

And then there is literally no detail about how to create an actual deb or rpm until you scroll way down the page to "custom packages" (which is sort of an ambiguous title -- packages could refer to anything). 

Happy with whatever change is made here, as long as there is a reference to the package building instructions contained within the `Building on Linux` section

**Pull request merged**
