### PR TITLE
tests: Allow VERBOSE_TEST=1 to run verbose ctest

### PR DESCRIPTION
**Pull request by theopolis**
The goal is to allow `ctest` to output verbose messages when the environment variable `VERBOSE` is defined. We can define this in Jenkins to help debug problems with long-running tests, like `test_osqueryd`. This test is flaky on macOS and is not easily reproduced locally.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 42edd0d6ce87b04797ba1c4e36c521d62f5b3f53 (Job results: [6347](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6347/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 42edd0d6ce87b04797ba1c4e36c521d62f5b3f53 (Job results: [6348](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6348/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 44ca49101ba20ceea076a4cdf6f99f43f5d0087d (Job results: [3228](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3228/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 44ca49101ba20ceea076a4cdf6f99f43f5d0087d (Job results: [6352](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6352/)) failed one or more tests (**Linux**).

**Pull request merged**
