### PR TITLE
config: Parser keys should be objects or arrays

### PR DESCRIPTION
**Pull request by theopolis**
I found this with our `libfuzzer` integration :)

### CODE REVIEW

**Comment by theopolis** [comment]
I'm finding more, hold up

**Comment by theopolis** [comment]
Unless you want 1 commit per bug bash?

**Comment by obelisk** [comment]
This is the second change to config parsers currently open in a PR. :P

**Comment by obelisk** [comment]
No, having them all here should be fine.

**Comment by theopolis** [comment]
Where are the others?

These are the other crashes:
```
diff --git a/osquery/config/parsers/file_paths.cpp b/osquery/config/parsers/file_paths.cpp
index 322aa62..5119be6 100644
--- a/osquery/config/parsers/file_paths.cpp
+++ b/osquery/config/parsers/file_paths.cpp
@@ -98,16 +98,18 @@ Status FilePathsConfigParserPlugin::update(const std::string& source,
   if (config.count("exclude_paths") > 0) {
     auto obj = data_.getObject();
     const auto& exclude_paths = config.at("exclude_paths").doc();
-    for (const auto& category : exclude_paths.GetObject()) {
-      auto arr = data_.getArray();
-      if (category.value.IsArray()) {
-        for (const auto& path : category.value.GetArray()) {
-          std::string path_string = path.GetString();
-          data_.pushCopy(path_string, arr);
+    if (exclude_paths.IsObject()) {
+      for (const auto& category : exclude_paths.GetObject()) {
+        auto arr = data_.getArray();
+        if (category.value.IsArray()) {
+          for (const auto& path : category.value.GetArray()) {
+            std::string path_string = path.GetString();
+            data_.pushCopy(path_string, arr);
+          }
+
+          std::string category_string = category.name.GetString();
+          data_.add(category_string, arr, obj);
         }
-
-        std::string category_string = category.name.GetString();
-        data_.add(category_string, arr, obj);
       }
     }
 
diff --git a/osquery/config/parsers/views.cpp b/osquery/config/parsers/views.cpp
index b9556a5..68e9d35 100644
--- a/osquery/config/parsers/views.cpp
+++ b/osquery/config/parsers/views.cpp
@@ -62,27 +62,29 @@ Status ViewsConfigParserPlugin::update(const std::string& source,
   }
 
   QueryData r;
-  for (const auto& view : views.GetObject()) {
-    std::string name = view.name.GetString();
-    std::string query = view.value.GetString();
-    if (query.empty()) {
-      continue;
-    }
-
-    std::string old_query = "";
-    getDatabaseValue(kQueries, kConfigViews + name, old_query);
-    erase_views.erase(name);
-    if (old_query == query) {
-      continue;
-    }
-
-    // View has been updated
-    osquery::query("DROP VIEW " + name, r);
-    auto s = osquery::query("CREATE VIEW " + name + " AS " + query, r);
-    if (s.ok()) {
-      setDatabaseValue(kQueries, kConfigViews + name, query);
-    } else {
-      LOG(INFO) << "Error creating view (" << name << "): " << s.getMessage();
+  if (views.IsObject()) {
+    for (const auto& view : views.GetObject()) {
+      std::string name = view.name.GetString();
+      std::string query = view.value.GetString();
+      if (query.empty()) {
+        continue;
+      }
+
+      std::string old_query = "";
+      getDatabaseValue(kQueries, kConfigViews + name, old_query);
+      erase_views.erase(name);
+      if (old_query == query) {
+        continue;
+      }
+
+      // View has been updated
+      osquery::query("DROP VIEW " + name, r);
+      auto s = osquery::query("CREATE VIEW " + name + " AS " + query, r);
+      if (s.ok()) {
+        setDatabaseValue(kQueries, kConfigViews + name, query);
+      } else {
+        LOG(INFO) << "Error creating view (" << name << "): " << s.getMessage();
+      }
     }
   }
```

**Comment by obelisk** [comment]
Could those benefit from an early bail out instead of tabbing in on the `IsObject()` check?

**Comment by theopolis** [comment]
> Could those benefit from an early bail out

Yes, but in my hunt for bugs I am more resistant than normal of introducing new return flows.

**Pull request merged**
