### PR TITLE
minor fixes to cb_info table

### PR DESCRIPTION
**Pull request by mtmcgrew**
* use getSystemRoot to get windows dir
* fix compile warnings
* update documentation
* replace %20 with space in sensor group

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 8c286a91946a9cffe1a0140fdd33d8ef6dcc3820 (Job results: [3110](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3110/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 6b0a8dc887d9c16ca3cbac362cd826609a240c22 (Job results: [3111](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3111/)) failed one or more tests (**OS X/Linux**).

**Comment by mtmcgrew** [comment]
retest this please

**Comment by osqueryer** [comment]
:-1: The commit 6b0a8dc887d9c16ca3cbac362cd826609a240c22 (Job results: [132](https://jenkins.osquery.io/job/osqueryPullRequestBuild/132/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 6b0a8dc887d9c16ca3cbac362cd826609a240c22 (Job results: [3117](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3117/)) failed one or more tests (**OS X/Linux**).

**Pull request merged**
