### PR TITLE
Use all available CPUs when provisioning a Vagrant box

### PR DESCRIPTION
**Pull request by sharvilshah**
As much of a fan I am of sword-fighting, I would still like my code to be compiled faster.

compiling

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by marpaia** [comment]
Is there any concern about resource contention with the host if you allocate all CPUs to the VM?

**Comment by theopolis** [comment]
Although provisioning is painful, I vote to keep this at 2. I usually have several vagrants running or a combo of vagrants and more persistent VMware machines.

**Comment by sharvilshah** [comment]
How does using and environment variable sound? If it's set use that value, fallback to 2 otherwise?

**Comment by marpaia** [comment]
oOo, I think an environment variable would be cool! I'd be interested in how @theopolis feels about it, but if that's the way to go here, we should also include an update to https://github.com/facebook/osquery/blob/master/docs/wiki/development/building.md

**Comment by theopolis** [comment]
Sounds perfect!

**Comment by sharvilshah** [comment]
@marpaia @theopolis 

Now supports settings `v.cpus` via an environment variable.

Here's how it looks:

```bash
❯ V_CPUS=`sysctl -n hw.ncpu` vagrant up ubuntu14 && vagrant ssh ubuntu14
...

vagrant@vagrant-ubuntu-trusty-64:~$ nproc
8
vagrant@vagrant-ubuntu-trusty-64:~$
```

And defaults to 2, when the ENV is not set:

```bash
❯ vagrant up ubuntu14 && vagrant ssh ubuntu14
...

vagrant@vagrant-ubuntu-trusty-64:~$ nproc
2
vagrant@vagrant-ubuntu-trusty-64:~$
```

**Comment by marpaia** [comment]
Thoughts on making this `OSQUERY_BUILD_CPUS` or something more specific?

**Comment by sharvilshah** [comment]
Agreed, `OSQUERY_BUILD_CPUS` sounds better. Updated.

**Pull request merged**
