### PR TITLE
Support for extensions

### LINKED ISSUE #2009: Windows can load a "hello world" extension

### PR DESCRIPTION
**Pull request by yying**
Includes changes to support osquery extensions

Closes #2009

### CODE REVIEW

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 6f8c59815eecb76a6e66a7244550cdfd1ca70536 (Job results: [42](https://jenkins.osquery.io/job/osqueryPullRequestAudit/42/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 6f8c59815eecb76a6e66a7244550cdfd1ca70536 (Job results: [3059](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3059/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
Seems like this is due for a rebase.

**Comment by osqueryer** [comment]
:no_good: The commit 0478f661b681f990f447d5fa2bbf39d4159f8fbb (Job results: [103](https://jenkins.osquery.io/job/osqueryPullRequestAudit/103/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 0478f661b681f990f447d5fa2bbf39d4159f8fbb (Job results: [3120](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3120/)) failed one or more tests (**OS X/Linux**).

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 0478f661b681f990f447d5fa2bbf39d4159f8fbb (Job results: [112](https://jenkins.osquery.io/job/osqueryPullRequestAudit/112/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 0478f661b681f990f447d5fa2bbf39d4159f8fbb (Job results: [3129](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3129/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit a9e57ff88ee4e4e98189d727ebfe8dc23dfa873e (Job results: [115](https://jenkins.osquery.io/job/osqueryPullRequestAudit/115/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit a9e57ff88ee4e4e98189d727ebfe8dc23dfa873e (Job results: [3132](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3132/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit bcc1865f238f3b0aa4174cc3e41fce503437a789 (Job results: [116](https://jenkins.osquery.io/job/osqueryPullRequestAudit/116/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit bcc1865f238f3b0aa4174cc3e41fce503437a789 (Job results: [3133](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3133/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit bcc1865f238f3b0aa4174cc3e41fce503437a789 (Job results: [140](https://jenkins.osquery.io/job/osqueryPullRequestAudit/140/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit bcc1865f238f3b0aa4174cc3e41fce503437a789 (Job results: [172](https://jenkins.osquery.io/job/osqueryPullRequestBuild/172/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit bcc1865f238f3b0aa4174cc3e41fce503437a789 (Job results: [3157](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3157/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit e80b42e72422ffaa305b8f78bca9bb445ebfeb1a (Job results: [141](https://jenkins.osquery.io/job/osqueryPullRequestAudit/141/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit e80b42e72422ffaa305b8f78bca9bb445ebfeb1a (Job results: [3158](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3158/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 195b64142888cbf0240cda7e5645fda9d9b35580 (Job results: [142](https://jenkins.osquery.io/job/osqueryPullRequestAudit/142/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 195b64142888cbf0240cda7e5645fda9d9b35580 (Job results: [3159](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3159/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 53bf0998a768476130c335f4c966b740c6c6affe (Job results: [3160](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3160/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
Something is breaking the POSIX module loading for sure.

**Comment by yying** [comment]
Yep, tracking it down.

**Comment by osqueryer** [comment]
:no_good: The commit 1c13b0ea009af3be8c5005b9161f072f968d21a0 (Job results: [149](https://jenkins.osquery.io/job/osqueryPullRequestAudit/149/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 0ee468d29dbfed95e059053508f7e79309a6792d (Job results: [3169](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3169/)) failed one or more tests (**OS X/Linux**).

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 0ee468d29dbfed95e059053508f7e79309a6792d (Job results: [3171](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3171/)) failed one or more tests (**OS X/Linux**).

**Pull request merged**
