### PR TITLE
Windows: Error if provisioning fails

### LINKED ISSUE #2292: Windows build: boost-msvc14 not found but provision succeeds
See:
```


Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
darhsl       12/31/1600   4:00 PM                osquery-packages              
Installing the following packages:
boost-msvc14
By installing you accept licenses for the packages.
boost-msvc14 not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\WINDOWS\system32\config\systemprofile\AppData\Local\Temp\osquery-packages;http://chocolatey.org/api/v2"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - boost-msvc14 - boost-msvc14 not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\WINDOWS\system32\config\systemprofile\AppData\Local\Temp\osquery-packages;http://chocolatey.org/api/v2"


Reading environment variables from registry. Please wait... Done.
Set build name.
New build name is 'df9a33e0ec860547a38badeb6d038de19122c9fd'
Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: 'df9a33e0ec860547a38badeb6d038de19122c9fd', new value: 'df9a33e0ec860547a38badeb6d038de19122c9fd'
Finished: SUCCESS
```

Example: https://jenkins.osquery.io/job/osqueryMasterBuildWindows10/11/console

### PR DESCRIPTION
**Pull request by artemdinaburg**
Check return code from the provision script and error if it errored.

Should close #2292

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
:-1: The commit caeae8b50900b2cb3611dc66d3af9dcca4574c9c (Job results: [3003](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3003/)) failed one or more tests.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit caeae8b50900b2cb3611dc66d3af9dcca4574c9c (Job results: [3004](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3004/)) failed one or more tests.

**Comment by theopolis** [comment]
Ok, the errors occur: https://jenkins.osquery.io/job/osqueryPullRequestWindows/TargetSystem=win10/lastBuild/console

**Pull request merged**
