### PR TITLE
force restart of osqueryd at end of OS/X package install

### PR DESCRIPTION
**Pull request by readshaw**
This pull request addresses an issue where an existing osqueryd is not restarted during the installation of a new OS/X package over the top.  This would mean that the newly installed code would not run automatically in package upgrade scenarios.

The fix is to reuse an existing postinstall fragment in make_osx_package.sh to unload the launchctl configuration before installing the new version of the .plist file and start the daemon.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Looks good!

**Comment by theopolis** [comment]
Just want to make sure you're aware @readshaw, it looks like the commit in this PR is using a different email (and name, nreadshaw) than your Github account. You can do a commit amend to reset the author after changing it locally or globally. If you then force push to this branch in your fork the PR will automatically update.

**Comment by readshaw** [comment]
Thanks for the feedback.  I made the author change, went ahead and squashed the commits but the rebase dragged into some other changes.  Not sure if this made the situation better or worse.  What do you suggest as a next step?

**Comment by readshaw** [comment]
Closing, because is superceded by https://github.com/facebook/osquery/pull/1911 in a (hopefully) cleaner PR.

**Pull request closed without merging**
