### PR TITLE
[Fix #2626] deps: Add no-avx to linenoise-ng build

### LINKED ISSUE #2626: deps: linenoise-ng installed with AVX instructions
The test-release `RUN_RELEASE_TESTS=1` jobs are failing because the output binaries include `vxorps` instructions. The only dependency change since 2.0.0 is `linenoise-ng` for Linux and OS X.

### PR DESCRIPTION
**Pull request by theopolis**

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 9cebbf1fda6ba334852ef7884954e18b64158e02 (Job results: [497](https://jenkins.osquery.io/job/osqueryPullRequestAudit/497/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 9cebbf1fda6ba334852ef7884954e18b64158e02 (Job results: [3515](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3515/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 9cebbf1fda6ba334852ef7884954e18b64158e02 (Job results: [520](https://jenkins.osquery.io/job/osqueryPullRequestBuild/520/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 9cebbf1fda6ba334852ef7884954e18b64158e02 (Job results: [3516](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3516/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e91c24ef138c1fba83abb95f2e0205fefafdad66 (Job results: [522](https://jenkins.osquery.io/job/osqueryPullRequestBuild/522/)) failed one or more tests (**Windows**).

**Pull request merged**
