### PR TITLE
Build fix for file_events_tests

### PR DESCRIPTION
**Pull request by mdevens**
Fix for issue https://github.com/facebook/osquery/issues/1845

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by mdevens** [comment]
Just signed up. Thanks.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1851/merge (Job: 2382) is good! :+1:

**Comment by theopolis** [comment]
Thanks again @mdevens, this closes #1845.

**Pull request merged**
