### PR TITLE
Rollup of build changes

### PR DESCRIPTION
**Pull request by theopolis**
~~1. Statically link OpenSSL provided by brew on OS X 10.10.~~
2. Remove unused CMake package discovery (LZMA, Snappy). Snappy discovery is included within RocksDB.
3. Change RocksDB discovery to include the `librocksdb_lite.a/so` paths.
4. Build RocksDB LITE in brew and from source (on every supported Linux).
5. Change thrift logic to support linking dynamically, depending on CMake build options.
6. Attempt to support a dynamic link-all option and include relevant documentation.
7. Update CentOS 7 to 7.1 in Vagrant.
8. Allow registry exceptions when profiling and during end to end testing.

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by sharvilshah** [comment]
Thanks for getting this going, I am not super familiar with CMake (I should get on that though) and would have taken way longer to get this going.

**Comment by theopolis** [comment]
I'm not very happy about the static linking of OpenSSL in any case, but the osquery project should be able to take on the burden of including it in some capacity. It's easy to link it statically, but a better intermediate approach would to include an RPATH and use `/usr/share/osquery/lib` to stage our dependent dynamic links. We'd get 3 benefits: (1) a smaller memory footprint when running multiple osquery* binaries, (2) an easier-to-identify yet still opaque libssl version binding, (3) precedent for iterating on 1 and minifying individual RSS in the longer term. 

3. Get more interesting when considering adoption into mainline Linux package repos. We will most definitely need to segregate our table dependencies and move to a set of shared libraries that implement features. We're ready to do this currently, we just don't distribute this way.

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
I'm going to create a separate PR that includes all the above changes EXCEPT for the OpenSSL/Brew static linking. We can then discuss those merits separately.

**Comment by theopolis** [comment]
With the most recent update to this PR: I've removed the OpenSSL changes.

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
