### PR TITLE
Enable AppVeyor

### PR DESCRIPTION
**Pull request by fmanco**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 066937e6389ff5da765f006160489ad6be7f4618 (Job results: [3640](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3640/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 066937e6389ff5da765f006160489ad6be7f4618 (Job results: [3641](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3641/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 066937e6389ff5da765f006160489ad6be7f4618 (Job results: [6747](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6747/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 066937e6389ff5da765f006160489ad6be7f4618 (Job results: [6748](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6748/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 230e5f38cb48fcc557fae1f2f2d4ad0fc1f85c74 (Job results: [3642](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3642/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 230e5f38cb48fcc557fae1f2f2d4ad0fc1f85c74 (Job results: [3643](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3643/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 230e5f38cb48fcc557fae1f2f2d4ad0fc1f85c74 (Job results: [6749](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6749/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 230e5f38cb48fcc557fae1f2f2d4ad0fc1f85c74 (Job results: [6750](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6750/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 4f8057f21c1255f7db3a7fd0079eb71ff5c2fdf5 (Job results: [2782](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2782/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 4f8057f21c1255f7db3a7fd0079eb71ff5c2fdf5 (Job results: [3645](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3645/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 4f8057f21c1255f7db3a7fd0079eb71ff5c2fdf5 (Job results: [6752](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6752/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 4f8057f21c1255f7db3a7fd0079eb71ff5c2fdf5 (Job results: [6753](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6753/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 4f8057f21c1255f7db3a7fd0079eb71ff5c2fdf5 (Job results: [3646](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3646/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5e9603fecb13ce3715f0dafb651400e4276969c7 (Job results: [3647](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3647/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5e9603fecb13ce3715f0dafb651400e4276969c7 (Job results: [6754](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6754/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5e9603fecb13ce3715f0dafb651400e4276969c7 (Job results: [3648](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3648/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5e9603fecb13ce3715f0dafb651400e4276969c7 (Job results: [6756](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6756/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 83226f3ffc97e96618d3d62ec7da9da9786b54a6 (Job results: [3649](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3649/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 83226f3ffc97e96618d3d62ec7da9da9786b54a6 (Job results: [3650](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3650/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 83226f3ffc97e96618d3d62ec7da9da9786b54a6 (Job results: [6755](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6755/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 83226f3ffc97e96618d3d62ec7da9da9786b54a6 (Job results: [6757](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6757/)) failed one or more tests (**Linux**).

**Comment by fmanco** [comment]
AppVeyor is already building (and failing) this PR so no need to merge for testing. But this need more iterations. I need to fix a few things and also run the tests which this PR doesn't  do yet.

**Comment by fmanco** [comment]
Let's close this for now since I'm not really working on it.

**Pull request closed without merging**
