### PR TITLE
[RFC] Building on High Sierra

### PR DESCRIPTION
**Pull request by jedi22**
These are all the changes that I had to make to the osquery build system to get make deps and make working on High Sierra. I had to build bison myself to apply a patch addressing a change in macOS' printf stack. Other than that I had to add ninja and reorder a couple dependencies.

### CODE REVIEW

**Comment by theopolis** [comment]
I'm not sure, I don't think bison is that easy, I would check that this works with make build_deps on a clean install.

Also why reorder cmake, what are the specific dependency changes?

**Comment by jedi22** [comment]
This worked after a make depsclean and after a make clean in a separate bison repo. I would check why I moved cmake.

**Comment by jedi22** [comment]
Just tested on a 100% clean install and it works.

**Comment by jedi22** [comment]
I moved cmake because clang-format needs it to build

**Comment by jedi22** [comment]
make build_deps works if you move the homebrew tap points forward.

**Comment by osqueryer** [comment]
:-1: The commit 02a7485bd062724621234b805651648653f77591 (Job results: [2142](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2142/)) failed one or more tests (**Windows**).

**Pull request merged**
