### PR TITLE
Adding Aobo keylogger and OSX_Keydnap to OSX attacks

### PR DESCRIPTION
**Pull request by Centurion89**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by Centurion89** [comment]
Whoa, not sure how that third-party modification got in there. I don't even see that file in my repo. Let me know if this is something that needs to be fixed before committing.

**Comment by zwass** [comment]
Thanks @Centurion89! Looks like @PickmanSec beat you to it on the Eleanor backdoor (https://github.com/facebook/osquery/pull/2226). Let's remove Eleanor and the stray `third-party` file from this commit, and then merge the Aobo query

**Comment by theopolis** [comment]
@Centurion89 if you do:
```
$ git submodule update --init
$ git add -u .
$ git commit -m "Remove the submodule change"
$ git push
```

You should be read to rock.

**Comment by Centurion89** [comment]
Arg, didn't work.

Just gonna abandon this pull request and open a new one. Sorry for the hassle

**Pull request closed without merging**
