### PR TITLE
Allow the non-blocking kernel-test publisher to drop 5%

### LINKED ISSUE #2306: Flaky tests: KernelCommunicationTests assess read + drops lower bound
See:
```
Running kernel tests requires root.
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from KernelCommunicationTests
[ RUN      ] KernelCommunicationTests.test_communication
/Users/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/osx11/osquery/events/kernel/tests/kernel_communication_tests.cpp:90: Failure
Value of: reads + drops
  Actual: 1995610
Expected: num_threads * events_per_thread
Which is: 2000000
[  FAILED  ] KernelCommunicationTests.test_communication (6338 ms)
[----------] 1 test from KernelCommunicationTests (6338 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (6338 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] KernelCommunicationTests.test_communication

 1 FAILED TEST
make[2]: *** [kernel/CMakeFiles/kernel-test] Error 1
make[1]: *** [kernel-test/fast] Error 2
make: *** [kernel-test/fast] Error 2
```

This test failure is caused by the default mode for kernel event consumption switching from lossless (blocking) to lossy.

### PR DESCRIPTION
**Pull request by theopolis**
Closes #2306

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 365fda659cc287b1cc74d40bfe2f011498512824 (Job results: [3000](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3000/)) failed one or more tests.

**Comment by theopolis** [comment]
Passed on OS X, failed on CentOS7 because a node went offline:
```
Agent went offline during the build
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2351)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2820)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
```

**Comment by osqueryer** [comment]
:-1: The commit 30b11d89509b10555bb8046c678d8f5efbef0dec (Job results: [3001](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3001/)) failed one or more tests.

**Comment by theopolis** [comment]
Now the OS X 10.11 (2) host goes offline. And the CentOS7 host:
```
/usr/local/osquery/bin/ld: /usr/local/osquery/lib64/libreadline.a(readline.o): relocation R_X86_64_32 against `rl_get_previous_history' can not be used when making a shared object; recompile with -fPIC
/usr/local/osquery/lib64/libreadline.a: error adding symbols: Bad value
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [osquery/osqueryi] Error 1
make[2]: *** [osquery/CMakeFiles/shell.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Pull request merged**
