### PR TITLE
split registry to separate classes

### PR DESCRIPTION
**Pull request by mkareta**
Split registry cpp file into separate files. The actual code was **not** changed, except clang format changes. 

This is first of series of PRs that will be focused on:
- strong types for registry 
- perfromance improvments 
- locks/multhithreding review

### CODE REVIEW

**Comment by theopolis** [comment]
Ah, yes this has been needed for a while. Take a look at my "quick" pass at splitting these up: https://github.com/facebook/osquery/pull/4076

**Comment by theopolis** [comment]
Right, in this refactor, let's avoid changing code.

**Comment by osqueryer** [comment]
:-1: The commit 0aa1427d76e2d58ffd25306cddb38755f8eecfa7 (Job results: [4181](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4181/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 0aa1427d76e2d58ffd25306cddb38755f8eecfa7 (Job results: [4182](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4182/)) failed one or more tests (**Windows**).

**Pull request merged**
