### PR TITLE
Disallow the shadowing of local variables and fix existing shadows

### PR DESCRIPTION
**Pull request by jedi22**
I'd also like to add this as an error so that you cannot build when shadowing a local variable.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 0e126fee5cc310cf22f8d7167515317d28069df4 (Job results: [64](https://jenkins.osquery.io/job/osqueryPullRequestLinux/64/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 0e126fee5cc310cf22f8d7167515317d28069df4 (Job results: [65](https://jenkins.osquery.io/job/osqueryPullRequestLinux/65/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:no_good: The commit ba4428986e191240c24b0819b7bb40b0196ca2af (Job results: [1696](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1696/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit ba4428986e191240c24b0819b7bb40b0196ca2af (Job results: [71](https://jenkins.osquery.io/job/osqueryPullRequestLinux/71/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 3f3adadb0ef5621de30b0a6e81cbf08c89f0ced8 (Job results: [72](https://jenkins.osquery.io/job/osqueryPullRequestLinux/72/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 3f3adadb0ef5621de30b0a6e81cbf08c89f0ced8 (Job results: [73](https://jenkins.osquery.io/job/osqueryPullRequestLinux/73/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
Do you mind changing the commit title to something more specific?

**Pull request merged**
