### PR TITLE
Extended crontab table to support files in /etc/cron.d/

### PR DESCRIPTION
**Pull request by nosajnedgo**
Addresses issue #2026

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by friedbutter** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 765cef839dc358380dfe0515c94e0130f083a2d2 (Job results: [314](https://jenkins.osquery.io/job/osqueryPullRequestAudit/314/)) failed the code audit.

**Comment by PoppySeedPlehzr** [comment]
This looks good, thanks for contributing!  Once the builds have finished successfully we can get this merged in.

**Comment by friedbutter** [comment]
@PoppySeedPlehzr is code audit working? Can we ignore this one for now?

**Pull request merged**
