### PR TITLE
look up the external plugin by the correct name

### LINKED ISSUE #4152: error when loading an external logger plugin alongside a builtin one
tl;dr: when using `--logger_plugin=filesystem,test-logger` (where `test-logger` is the name of a plugin loaded from an external extension), the extension manager dies with `terminate called after throwing an instance of 'std::out_of_range'  what():  map::at` after loading the extension.

I'm working on developing a custom logger extension, and I'm running into a bug where loading the logger plugin works fine when it is the only logger plugin loaded, but causes osquery to throw an error when it is loaded with any of the builtin loggers. [Here](https://gist.github.com/doy-stripe/e0504f6e75f348321eca7f2f78071d33) is the source to an extension that reproduces this issue. It's using osquery-go rather than the C++ SDK - I don't *think* that should matter, but it might, I guess.

When I run `sudo osqueryd --extensions_autoload=extensions.load --logger_plugin=test-logger --verbose`, I get this (successful) output:

```
I0223 21:32:53.529295 86395 init.cpp:368] osquery initialized [version=2.11.0]
I0223 21:32:53.543350 86395 system.cpp:344] Found stale process for osqueryd (84082)
I0223 21:32:53.543396 86395 system.cpp:377] Writing osqueryd pid (86395) to /var/run/osqueryd.pidfile
I0223 21:32:53.543459 86395 extensions.cpp:346] Found autoloadable extension: /usr/local/osquery_extensions/test.ext
I0223 21:32:53.543933 86401 watcher.cpp:549] osqueryd watcher (86395) executing worker (86402)
I0223 21:32:53.544157 86401 watcher.cpp:591] Created and monitoring extension child (86403): /usr/local/osquery_extensions/test.ext
I0223 21:32:53.551705 86402 init.cpp:365] osquery worker initialized [watcher=86395]
I0223 21:32:53.551975 86402 rocksdb.cpp:132] Opening RocksDB handle: /var/osquery/osquery.db
2018/02/23 21:32:53 initializing test-plugins
2018/02/23 21:32:53 waiting for socket /var/osquery/osquery.em to exist...
I0223 21:32:53.577345 86415 interface.cpp:338] Extension manager service starting: /var/osquery/osquery.em
2018/02/23 21:32:54 registering plugins
2018/02/23 21:32:54 running extension
I0223 21:32:54.553108 86455 interface.cpp:141] Registering extension (test-plugins, 1908, version=, sdk=)
I0223 21:32:54.553154 86455 registry.cpp:351] Extension 1908 registered logger plugin test-logger
2018/02/23 21:32:54 init: osqueryd
2018/02/23 21:32:54 status: {"s":0,"f":"init.cpp","i":365,"m":"osquery worker initialized [watcher=86395]","h":"[REDACTED]","c":"Fri Feb 23 21:32:53 2018 UTC","u":1519421573}
2018/02/23 21:32:54 status: {"s":0,"f":"rocksdb.cpp","i":132,"m":"Opening RocksDB handle: /var/osquery/osquery.db","h":"[REDACTED]","c":"Fri Feb 23 21:32:53 2018 UTC","u":1519421573}
2018/02/23 21:32:54 status: {"s":0,"f":"interface.cpp","i":338,"m":"Extension manager service starting: /var/osquery/osquery.em","h":"[REDACTED]","c":"Fri Feb 23 21:32:53 2018 UTC","u":1519421573}
2018/02/23 21:32:54 status: {"s":0,"f":"interface.cpp","i":141,"m":"Registering extension (test-plugins, 1908, version=, sdk=)","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
2018/02/23 21:32:54 status: {"s":0,"f":"registry.cpp","i":351,"m":"Extension 1908 registered logger plugin test-logger","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
I0223 21:32:54.557971 86402 events.cpp:825] Event publisher not enabled: audit: Publisher disabled via configuration
I0223 21:32:54.558014 86402 events.cpp:825] Event publisher not enabled: syslog: Publisher disabled via configuration
I0223 21:32:54.558099 86402 events.cpp:1078] Error registering subscriber: socket_events: Subscriber disabled via configuration
I0223 21:32:54.558203 86458 events.cpp:746] Starting event publisher run loop: inotify
I0223 21:32:54.558212 86402 main.cpp:106] Not starting the distributed query service: Distributed query service not enabled.
I0223 21:32:54.558244 86459 events.cpp:746] Starting event publisher run loop: udev
2018/02/23 21:32:54 status: {"s":0,"f":"events.cpp","i":825,"m":"Event publisher not enabled: audit: Publisher disabled via configuration","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
2018/02/23 21:32:54 status: {"s":0,"f":"events.cpp","i":825,"m":"Event publisher not enabled: syslog: Publisher disabled via configuration","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
2018/02/23 21:32:54 status: {"s":0,"f":"events.cpp","i":1078,"m":"Error registering subscriber: socket_events: Subscriber disabled via configuration","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
2018/02/23 21:32:54 status: {"s":0,"f":"events.cpp","i":746,"m":"Starting event publisher run loop: inotify","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
2018/02/23 21:32:54 status: {"s":0,"f":"main.cpp","i":106,"m":"Not starting the distributed query service: Distributed query service not enabled.","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
2018/02/23 21:32:54 status: {"s":0,"f":"events.cpp","i":746,"m":"Starting event publisher run loop: udev","h":"[REDACTED]","c":"Fri Feb 23 21:32:54 2018 UTC","u":1519421574}
```

But if I instead run `sudo osqueryd --extensions_autoload=extensions.load --logger_plugin=filesystem,test-logger --verbose`, this happens:

```
I0223 21:31:48.202580 84082 init.cpp:368] osquery initialized [version=2.11.0]
I0223 21:31:48.213490 84082 system.cpp:344] Found stale process for osqueryd (83514)
I0223 21:31:48.213531 84082 system.cpp:377] Writing osqueryd pid (84082) to /var/run/osqueryd.pidfile
I0223 21:31:48.213593 84082 extensions.cpp:346] Found autoloadable extension: /usr/local/osquery_extensions/test.ext
I0223 21:31:48.214121 84083 watcher.cpp:549] osqueryd watcher (84082) executing worker (84084)
I0223 21:31:48.214355 84083 watcher.cpp:591] Created and monitoring extension child (84085): /usr/local/osquery_extensions/test.ext
2018/02/23 21:31:48 initializing test-plugins
2018/02/23 21:31:48 waiting for socket /var/osquery/osquery.em to exist...
I0223 21:31:48.220993 84084 init.cpp:365] osquery worker initialized [watcher=84082]
I0223 21:31:48.221196 84084 rocksdb.cpp:132] Opening RocksDB handle: /var/osquery/osquery.db
I0223 21:31:48.242049 84096 interface.cpp:338] Extension manager service starting: /var/osquery/osquery.em
2018/02/23 21:31:49 registering plugins
2018/02/23 21:31:49 running extension
I0223 21:31:49.218353 84148 interface.cpp:141] Registering extension (test-plugins, 55813, version=, sdk=)
I0223 21:31:49.218399 84148 registry.cpp:351] Extension 55813 registered logger plugin test-logger
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
I0223 21:31:54.215692 84083 watcher.cpp:549] osqueryd watcher (84082) executing worker (84310)
I0223 21:31:54.222234 84310 init.cpp:365] osquery worker initialized [watcher=84082]
I0223 21:31:54.222450 84310 rocksdb.cpp:132] Opening RocksDB handle: /var/osquery/osquery.db
I0223 21:31:54.242370 84317 interface.cpp:338] Extension manager service starting: /var/osquery/osquery.em
E0223 21:31:57.252949 84310 init.cpp:545] Cannot activate filesystem,test-logger logger plugin: Unknown registry plugin: test-logger
```

It appears that something is causing the extension manager to crash, and when it gets restarted, it doesn't have state about the extensions that were previously loaded, and so it then fails to load the logger plugin from the extension.

### PR DESCRIPTION
**Pull request by doy-stripe**
fixes #4152

### CODE REVIEW

**Comment by doy-stripe** [comment]
(you should have just received an email requesting to add me to the Stripe company CLA)

**Comment by obelisk** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit ce8a6bed638f4d66535144c3e2c0e0b2ab3026a8 (Job results: [1105](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1105/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit ce8a6bed638f4d66535144c3e2c0e0b2ab3026a8 (Job results: [1106](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1106/)) failed one or more tests (**FreeBSD**).

**Comment by muffins** [comment]
Don’t mind the FreeBSD test fails, and as for the CLA, who did y’all email? If it’s theopolis we might wait until next week, as he’s onboard PTO :)

**Comment by muffins** [comment]
Nice fix! Not sure how easy it’d be, but would you mind looking into adding a unit test for this case alongside the PR?

**Comment by doy-stripe** [comment]
looks like the email went to tsai@fb.com.

**Comment by muffins** [comment]
Perfect, we should be set then

**Comment by doy-stripe** [comment]
do you have some pointers to how the unit test should work? i'm really not very familiar with how this codebase works at all - this patch was just a pretty obvious typo. i can't seem to find any existing tests for external plugins.

**Comment by muffins** [comment]
Ah right you are. Not sure we'll be able to do this without using the integration framework as that'll be helpful for externally registered plugins.

**Comment by doy-stripe** [comment]
to clarify, is this fine to merge as-is, or is it going to block on tests?

**Comment by muffins** [comment]
@doy-stripe this should be fine to merge as is, my apologies for the delay in response! Unit tests would likely not work, we’d need an integration test to register multiple plugins, but considering this is a big fix we will just merge and file a follow up task to write kne

**Pull request merged**
