### PR TITLE
Bump AWS SDK to 0.12.17 for Linux/*BSD

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
This wont work until I update the `.17` tarball to our S3 bucket.

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
We should be up to 13.8 now! See the new build changes and the new AWS-SDK formula: https://github.com/facebook/osquery/blob/master/tools/provision/formula/aws-sdk-cpp.rb#L6

To begin testing:
```
make distclean
make deps
make
```

Please re-open if there are any problems. :dancer:

**Pull request closed without merging**
