### PR TITLE
Enable "json1" extension

### PR DESCRIPTION
**Pull request by andrew-d**
This is waiting on osquery/third-party#11.  Once that is merged, I'll bump the subproject commit and force-push.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
https://github.com/osquery/third-party/pull/11 has landed, feel free to bump the submodule commit when ready!

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
I'm guessing this is relevant: 
```
[ RUN      ] SQLiteUtilTests.test_query_planner
/Users/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/osx10/osquery/sql/tests/sqlite_util_tests.cpp:163: Failure
Value of: TypeList({BIGINT_TYPE})
  Actual: { 3 }
Expected: getTypes(columns)
Which is: { 0 }
/Users/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/osx10/osquery/sql/tests/sqlite_util_tests.cpp:168: Failure
Value of: TypeList({BIGINT_TYPE, BIGINT_TYPE, INTEGER_TYPE})
  Actual: { 3, 3, 2 }
Expected: getTypes(columns)
Which is: { 0, 0, 2 }
/Users/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/osx10/osquery/sql/tests/sqlite_util_tests.cpp:177: Failure
Value of: TypeList({TEXT_TYPE, INTEGER_TYPE, BIGINT_TYPE, INTEGER_TYPE})
  Actual: { 1, 2, 3, 2 }
Expected: getTypes(columns)
Which is: { 1, 2, 0, 2 }
/Users/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/osx10/osquery/sql/tests/sqlite_util_tests.cpp:190: Failure
Value of: TypeList({INTEGER_TYPE, INTEGER_TYPE, BIGINT_TYPE})
  Actual: { 2, 2, 3 }
Expected: getTypes(columns)
Which is: { 2, 2, 0 }
```

I'll have some time later this weekend to dig into changes. But I'm guessing there is a reordering of the types and we (osquery codebase) was doing a best-effort mimic of the SQLite enums. If those enums are in the header we can try a more-strict mapping.

**Comment by andrew-d** [comment]
Yeah, looks like there's some issues there...

From what I can see in some initial digging, the query planner isn't able to get the proper type for "unknown" columns - and I can confirm that this is also happening using the 3.9.2 release of SQLite.  I'm not super-familiar with this code, but I'll probably poke at it a bit this weekend and see what I can find.

**Comment by theopolis** [comment]
Hey @andrew-d, I can pull your branch and try to work through this tonight. If you have any updates but aren't 100% though, feel free to post them as WIP.

**Comment by andrew-d** [comment]
Yeah, I didn't really spend too much time on it this weekend - mostly putting debug statements everywhere :stuck_out_tongue:  Nothing worth pushing here, though.

**Comment by theopolis** [comment]
Cool, thanks for testing/trying! :dancers:

**Pull request closed without merging**
