### PR TITLE
Augeas table performance improvements

### PR DESCRIPTION
**Pull request by thedrow**
This PR contains improvments that cut half of the memory requirements of the augeas table and on my computer shortens the runtime of "SELECT * FROM augeas" by 4 seconds.

This change depends on https://github.com/hercules-team/augeas/pull/474 being merged or us forking augeas.

### CODE REVIEW

**Comment by theopolis** [comment]
I'm getting:
```
(gdb) bt
#0  0x00007ffff741d428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff741f02a in __GI_abort () at abort.c:89
#2  0x000055555620d004 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x000055555620c9ea in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x000055555620ca20 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x000055555620ccac in __cxxabiv1::__cxa_throw (obj=obj@entry=0x55555851f430, tinfo=0x555556543e90 <typeinfo for std::logic_error>, 
    dest=0x555556213950 <std::logic_error::~logic_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:87
#6  0x000055555623f02a in std::__throw_logic_error (__s=0x555555696950 <.str.180.llvm.9C835A06> "basic_string::_M_construct null not valid")
    at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:74
#7  0x0000555556264664 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) ()
#8  0x000055555624eba4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char const*> (
    __end=<optimized out>, __beg=<optimized out>, this=<optimized out>)
    at /tmp/gcc-20170523-21480-1ln58b0/gcc-5.3.0/build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h:195
#9  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (__end=<optimized out>, 
    __beg=<optimized out>, this=<optimized out>)
    at /tmp/gcc-20170523-21480-1ln58b0/gcc-5.3.0/build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h:214
#10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=<optimized out>, __s=<optimized out>, 
    __a=...) at /tmp/gcc-20170523-21480-1ln58b0/gcc-5.3.0/build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h:457
#11 0x000055555647566e in osquery::tables::matchAugeasPattern(augeas*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::allocator<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, osquery::QueryContext&, bool) ()
#12 0x0000555556475d86 in osquery::tables::genAugeas[abi:cxx11](osquery::QueryContext&) ()
#13 0x00005555564b17ee in osquery::augeasTablePlugin::generate[abi:cxx11](osquery::QueryContext&) ()
#14 0x00005555563d8957 in osquery::tables::sqlite::xFilter(sqlite3_vtab_cursor*, int, char const*, int, Mem**) ()
#15 0x000055555628e9d2 in sqlite3VdbeExec ()
#16 0x000055555626f509 in sqlite3_step ()
#17 0x000055555625da82 in shell_exec(char const*, int (*)(void*, int, char**, char**, int*), callback_data*, char**) ()
#18 0x000055555625f4cd in do_meta_command(char*, callback_data*) ()
#19 0x000055555625e90a in osquery::launchIntoShell(int, char**) ()
#20 0x00005555562652a0 in main ()
``` 
on my desktop o.O

**Comment by thedrow** [comment]
Maybe I'm passing a null string to std::string. I'll add some checks.

**Comment by theopolis** [comment]
Friendly ping, any progress here?

**Comment by thedrow** [comment]
@lutter has to decide if he wants to merge https://github.com/hercules-team/augeas/pull/474
Alternatively, we can fork augeas :(

**Comment by thedrow** [comment]
No need for this PR :)
I'll submit a new one once https://github.com/hercules-team/augeas/pull/481 is merged.

**Pull request closed without merging**
