### PR TITLE
Shell Cleanups

### PR DESCRIPTION
**Pull request by sharvilshah**
* Mostly formatting fixes -- slightly more inline with the rest of the codebase
* Removed unused variables/macros/fields
* Remove Oracle/MS style SQL command terminator -- only support `;` as the command terminator.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
This is great! If you want some added fun, run cppcheck and "make analyze" on the shell related code too. I think there was some semi-important, but seldom executed, path to a failed nullptr dereference check.

**Comment by theopolis** [comment]
ok to test

**Comment by sharvilshah** [comment]
Nothing from `make analyze`.

Couple of style nits from `cppcheck`:

```
Checking osquery/devtools/shell.cpp...
[osquery/devtools/shell.cpp:1131]: (style) Expression is always false because 'else if' condition matches previous condition at line 1128.
[osquery/devtools/shell.cpp:247]: (style) The scope of the variable 'zPrompt' can be reduced.
[osquery/devtools/shell.cpp:480]: (style) The scope of the variable 'n' can be reduced.
[osquery/devtools/shell.cpp:757]: (style) The scope of the variable 'x' can be reduced.
[osquery/devtools/shell.cpp:766]: (style) Variable 'x' is assigned a value that is never used.
[osquery/sql/sqlite_util.h:46]: (style, inconclusive) Technically the member function 'osquery::SQLiteDBInstance::isPrimary' can be const.
Checking osquery/devtools/shell.cpp: SIGINT...
[osquery/devtools/shell.cpp:1]: (information) Skipping configuration 'SIGINT' since the value of 'SIGINT' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
```

Fixing couple of them in a bit.

**Comment by sharvilshah** [comment]
Fixed. The latest from cppcheck:

```
cppcheck --enable=all --inconclusive osquery/devtools/shell.cpp
Checking osquery/devtools/shell.cpp...
[osquery/sql/sqlite_util.h:46]: (style, inconclusive) Technically the member function 'osquery::SQLiteDBInstance::isPrimary' can be const.
Checking osquery/devtools/shell.cpp: SIGINT...
[osquery/devtools/shell.cpp:1]: (information) Skipping configuration 'SIGINT' since the value of 'SIGINT' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
(information) Cppcheck cannot find all the include files (use --check-config for details)
```

**Comment by theopolis** [comment]
:+1:

**Pull request merged**
