### PR TITLE
Add basic math extension functions

### PR DESCRIPTION
**Pull request by theopolis**
Add:
```
pow(2, 16);
ceil(9.8);
floor(9.8);
degrees(3.4);
radians(180);
pi();
sqrt(10);
exp(2);
log(90);
log10(90);
```

And a suite of additional trig functions: `sin`, `cos`, `tan`, `cot`, `asin`, `acos`, `atan`.

### CODE REVIEW

**Comment by theopolis** [comment]
I mostly wanted `power`, but it's very easy to wrap most C library math functions.

**Comment by osqueryer** [comment]
Build origin/pr/2123/merge (Job: 2712) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/2123/merge (Job: 2713) failed :-1:

**Comment by theopolis** [comment]
Failing on Ubuntu16, which is not ready to build yet.

**Pull request merged**
