### PR TITLE
Added build support for ManjaroLinux

### PR DESCRIPTION
**Pull request by Zaksh**
Added necessary changes in tools/get_platform.py to detect ManjaroLinux, tools/provision.sh to select manjaro based packages, tools/provision/lib.sh to add package and remove_package function support for Manjaro. 

These changes will help execute "make deps" properly on Manjaro Linux.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Hi @Zaksh! In the last few days I've been working to remove a lot of the "cruft" from how we installed for new OSes. This should simplify support for Manjaro.

It should be easy to rebase this commit, if you're based on Arch then take a look at the reduced set of packages for Arch: https://github.com/facebook/osquery/blob/master/tools/provision/arch.sh

You may also consider updating the `Vagrantfile` to add targets for Arch or Manjaro so we can better test when making build/dependency changes. :)

**Comment by Zaksh** [comment]
Hey @theopolis!

I have made changes but I am not aware of Vagrant so didn't update Vagrantfile. I hope someone with the knowledge can help in this regard. I have removed package gcc as Manjaro has gcc-multilib installed within it.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 777f898f5dbfebdd214e7af5232c4c971696c531 (Job results: [2984](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2984/)) failed one or more tests.

**Pull request merged**
