### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by hubdotcom**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
I hope the bots keep this discussion respectful and constructive. :rocket:

**Comment by theopolis** [comment]
Hey @hubdotcom, I think our MO is to keep the license year static at the year the project started. @marpaia might have more context on our license styling.

**Comment by marpaia** [comment]
IIRC @theopolis is correct, we're supposed to leave the LICENSE as is.

**Pull request closed without merging**
