### PR TITLE
Add option for status-only secondary logger plugins

### PR DESCRIPTION
**Pull request by theopolis**
This adds an esoteric option `--logger_secondary_status_only` that will only be used/needed when using multiple logger plugins. Some configurations may only warn WARNING/ERROR logs to be forwarded to the secondary plugin.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit f26173e48c435942f1d72f2c6bbc2227a597b98d (Job results: [3378](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3378/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit f26173e48c435942f1d72f2c6bbc2227a597b98d (Job results: [3379](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3379/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-6** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2534/files/f26173e48c435942f1d72f2c6bbc2227a597b98d..8ca274cc816686425a79c6c7daa7489150c85122)

**Comment by facebook-github-bot-1** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2534/files/8ca274cc816686425a79c6c7daa7489150c85122..378d59ec097ac089998de1fb61c8c0ab724c43bf)

**Comment by facebook-github-bot-1** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2534/files/378d59ec097ac089998de1fb61c8c0ab724c43bf..c0c506dccadeacab34622dbfc23fd8d299716b75)

**Comment by osqueryer** [comment]
:-1: The commit c0c506dccadeacab34622dbfc23fd8d299716b75 (Job results: [386](https://jenkins.osquery.io/job/osqueryPullRequestBuild/386/)) failed one or more tests (**Windows**).

**Comment by facebook-github-bot-0** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2534/files/c0c506dccadeacab34622dbfc23fd8d299716b75..e82dc9d8ff034a91b45512e8415316a9067154f2)

**Pull request merged**
