### PR TITLE
OS/X packaging improvements

### PR DESCRIPTION
**Pull request by readshaw**
This pull request addresses two issues encountered while preparing for an OS/X deployment:

1. An issue where an existing osqueryd is not restarted during the installation of a new OS/X package over the top (supercedes: https://github.com/facebook/osquery/pull/1908). This would mean that the newly installed code would not run automatically in package upgrade scenarios.  The fix is to reuse an existing postinstall fragment in make_osx_package.sh to unload the launchctl configuration before installing the new version of the .plist file and start the daemon.

2. An enhancement to bundle a custom server certificate chain with an installed osquery client on OS/X.  This simplifies the deployment when a TLS server uses an internal CA where a clean system may not have the CA certificates installed in key chain.

BTW, I see tools/tests/test_extensions.py in this pull request, but I am not sure how to remove it.  I had already merged changes from master.  Any advice welcome.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Yeah, looks like there's a merge included in your PR. The best way out is to reset --hard to origin/master, then cherry-pick your two commits on top.

If you want to pull on a feature branch do a: pull --rebase. There's some more tips/tricks here: https://github.com/facebook/osquery/blob/master/CONTRIBUTING.md

**Comment by readshaw** [comment]
Thanks Teddy.  Since the extraneous merge was small, I just pushed a commit to revert that change.

Does that look better to you now?

**Comment by readshaw** [comment]
Squashed commits.  No functional change to the PR.

Anything else you need from me?

**Comment by theopolis** [comment]
Perfect!

**Pull request merged**
