### PR TITLE
Various performance improvements, stability, and bug fixes.

### PR DESCRIPTION
**Pull request by theopolis**
This is largely an attempt to solve #1556. 

- There are some API changes to `osquery_info`:
 - `config_path` is removed, use `select * from osquery_flags where name = 'config_path'` 
 - `config_md5` is now called `config_hash` since it is mostly a synthetic hash of various datas/calculated values. It should be treated like a a CRC, less like a md5 of some controlled input. It should be used to detect changes to the config.
 - `start_time` included in `osquery_info` is a UNIX time that is consistent across platforms. Use this to determine when the worker (if using a worker) last started. The process's start time can be different on platforms, as well as use different units.
- There are a few changes to how differentials are calculated to improve memory and CPU perf:

Before:
```
DATABASE_serialize/1/1               4191       4176     161019                                 
DATABASE_serialize/10/10           268215     264966       2559                                 
DATABASE_serialize/10/100         2609523    2601086        257                                 
DATABASE_serialize_json/1/1          5273       5247     127952                                 
DATABASE_serialize_json/10/10      290625     289659       2388                                 
DATABASE_serialize_json/10/100    2941248    2932178        230                                 
DATABASE_diff/1/1                    1039       1035     665437                                 
DATABASE_diff/10/10                 78151      77587       8995                                 
DATABASE_diff/10/100               768517     760853        850                                 
DATABASE_query_results/1/1          38275      38042      17838                                 
DATABASE_query_results/10/10       807191     801985        786                                 
DATABASE_query_results/10/100     7368347    7365032         93                                 
DATABASE_store                       4617       4593     148207                                 
DATABASE_store_large               180672      97072       6793                                 
DATABASE_store_append              169138     213909       4199
```

After:
```
DATABASE_serialize/1/1               6250       5268     100000                                 
DATABASE_serialize/10/10           271170     265741       2657                                 
DATABASE_serialize/10/100         2619557    2601896        260                                 
DATABASE_serialize_json/1/1          5091       5043     129836                                 
DATABASE_serialize_json/10/10      295581     293358       2217                                 
DATABASE_serialize_json/10/100    2916310    2906103        233                                 
DATABASE_diff/1/1                     962        959     666089                                 
DATABASE_diff/10/10                 76346      75959       8763                                 
DATABASE_diff/10/100               776801     774445        814                                 
DATABASE_query_results/1/1          20574      20515      32956                                 
DATABASE_query_results/10/10       405375     402670       1668                                 
DATABASE_query_results/10/100     1129725     896349        793                                 
DATABASE_store                       4523       4527     150798                                 
DATABASE_store_large               183189      97299       7081                                 
DATABASE_store_append              176627     201290       4083 
```

The big win is **DATABASE_query_results**

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (87d0216296d356d30dbf135ffb0be068069a841a) is good! :+1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
Flaky tests recorded and will be soon squashed.

**Pull request merged**
