### PR TITLE
Refactor authorizations tables

### PR DESCRIPTION
**Pull request by theopolis**
Reduce some code reuse.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit e70fe1a9e1decb1a81d8b2c8dc3c8c527141fb06 (Job results: [2458](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2458/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit e70fe1a9e1decb1a81d8b2c8dc3c8c527141fb06 (Job results: [1910](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1910/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit e70fe1a9e1decb1a81d8b2c8dc3c8c527141fb06 (Job results: [1911](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1911/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit e70fe1a9e1decb1a81d8b2c8dc3c8c527141fb06 (Job results: [2460](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2460/)) failed the code audit or documentation test.

**Pull request merged**
