### PR TITLE
Fix error handling in AWS logger plugins

### LINKED ISSUE #3310: aws_firehose logger plugin reports 'success' but doesn't send anything to firehose stream
Using aws_firehose logger plugin on mac os x (10.12.5) with config below.  Running 2.4.2 installed from .pkg. osqueryd --verbose reports queries executing and 'success' sending 0 logs to Firehose. Repeating "Successfully sent 0 logs to Firehose." with no data received by Firehose stream.  Stream verified as running and accepting data via curl. Firehose plugin reports successful initiation. (log below).  Any additional debugging output possible?

Config (/var/osquery.conf):
```
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10,
    "logger_plugin": "aws_firehose",
    "aws_firehose_stream": "osquery",
    "aws_firehose_period": 10,
    "aws_access_key_id": "<snip>",
    "aws_secret_access_key": "<snip>",
    "aws_region": "us-east-1"
  },
  // Define a schedule of queries:
  "schedule": {
     "time": {
     "query": "SELECT * FROM time;",
     "interval": 2,
     "removed": false
     }
  }
}
```
osqueryd --ephemeral --database_path /tmp/osquery.db --verbose
Output:
```
08:47:37.808974 3696231360 init.cpp:383] osquery initialized [version=2.4.2]
08:47:37.810426 263774208 watcher.cpp:465] osqueryd watcher (7917) executing worker (7918)
08:47:37.818892 3696231360 init.cpp:380] osquery worker initialized [watcher=7917]
08:47:37.819735 3696231360 rocksdb.cpp:205] Opening RocksDB handle: /tmp/osquery.db
08:47:37.824524 121147392 interface.cpp:317] Extension manager service starting: /var/osquery/osquery.em
08:47:37.825426 3696231360 aws_util.cpp:340] Using AWS region from flag: us-east-1
08:47:37.825537 3696231360 aws_firehose.cpp:138] Firehose logging initialized with stream: osquery
08:47:37.827044 3696231360 preferences.cpp:216] Cannot find/read defaults plist from path: /private/var/db/receipts/com.facebook.osquery.kernel.plist
08:47:37.827114 3696231360 events.cpp:827] Event publisher failed setup: kernel: Cannot access /dev/osquery
08:47:37.827133 3696231360 events.cpp:827] Event publisher failed setup: scnetwork: Publisher not used
08:47:37.827420 3696231360 events.cpp:1080] Error registering subscriber: process_events: No kernel event publisher
08:47:37.827515 3696231360 events.cpp:1080] Error registering subscriber: process_file_events: No kernel event publisher
08:47:37.843750 3696231360 daemon.cpp:38] Not starting the distributed query service: Distributed query service not enabled.
...
08:47:38.844130 124903424 scheduler.cpp:74] Executing scheduled query time: SELECT * FROM time;
08:47:38.847478 124903424 scheduler.cpp:132] Found results for query: time
08:47:39.130697 121683968 aws_firehose.cpp:115] Successfully sent 0 logs to Firehose.
08:47:39.257388 121683968 aws_firehose.cpp:115] Successfully sent 0 logs to Firehose.
08:47:40.406997 121683968 aws_firehose.cpp:115] Successfully sent 0 logs to Firehose.
```

### PR DESCRIPTION
**Pull request by zwass**
The AWS plugins were correctly handling errors with individual records posting,
but did not handle an error for the overall request (such as an auth error). As
a result, when these errors occurred, osquery would print "Successfully sent 0
records to Kinesis." We now explicitly handle these errors.

Fixes #3310

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 149171c6965919d815c4ab1d60e945b37b4191f4 (Job results: [1245](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1245/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 149171c6965919d815c4ab1d60e945b37b4191f4 (Job results: [5125](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5125/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 149171c6965919d815c4ab1d60e945b37b4191f4 (Job results: [1246](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1246/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 149171c6965919d815c4ab1d60e945b37b4191f4 (Job results: [5126](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5126/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
Ping!

**Comment by osqueryer** [comment]
:no_good: The commit 04ce67150e3bea40fb5993ec9c4d90f0c07375e1 (Job results: [2042](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2042/)) failed the code audit or documentation test.

**Comment by zwass** [comment]
Sorry for neglecting this for so long. It was a trivial fix to the tests, but it had fallen off my radar.

I am getting some strange unrelated seeming segfault when I run the tests in normal build locally, but everything is working in a debug build. My local build has been pretty messed up for a while, so I'm thinking it is unrelated. We'll see how it does in CI.

**Comment by osqueryer** [comment]
:-1: The commit 3c799f4553ba8ddf6e65c3bd9e96471817a2cda2 (Job results: [5307](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5307/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 3c799f4553ba8ddf6e65c3bd9e96471817a2cda2 (Job results: [2203](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2203/)) failed one or more tests (**Windows**).

**Pull request merged**
