### PR TITLE
Adding version checking to provisioning script

### PR DESCRIPTION
**Pull request by PoppySeedPlehzr**

### CODE REVIEW

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 29e094bbcb25dc26dfcce6f07fcae006eb796159 (Job results: [295](https://jenkins.osquery.io/job/osqueryPullRequestBuild/295/)) failed one or more tests (**Windows**).

**Comment by facebook-github-bot-0** [comment]
@PoppySeedPlehzr updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2478/files/29e094bbcb25dc26dfcce6f07fcae006eb796159..42d7b86b2d5edbeafc1902c72ed6254929c26d49)

**Comment by facebook-github-bot-9** [comment]
@PoppySeedPlehzr updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2478/files/42d7b86b2d5edbeafc1902c72ed6254929c26d49..2a51b06a2e3ac24308c7669f0fb98574d1c16c89)

**Pull request merged**
