### PR TITLE
Build on debian wheezy with recent changes

### PR DESCRIPTION
**Pull request by mathieuk**
As above, just updating the scripts so that things build again with the recent changes in osquery.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Sorry this has taken me a while to comment on! There was issues with `std::is_trivially_destructible` within Google Benchmark before, do the updated `third-party` changes: https://github.com/osquery/third-party/commit/01fc0acb658d2f08ebb7a0388ac2e49f4f2b00c9 not work on 10.04?

**Comment by mathieuk** [comment]
They did, but you've since changed the build process to not install benchmark through thirdparty anymore: https://github.com/facebook/osquery/commit/d63510f8bdd9eeee6058ef068b93ad991f76f67a .

**Comment by theopolis** [comment]
Ok, if that used to work, try: https://s3.amazonaws.com/osquery-packages/deps/benchmark-0.1.0-osq1.tar.gz, that has the patches from the third-party repo before the benchmark folder was deleted.

We could also gate the benchmark building using an environment variable like `SKIP_BENCHMARKS=1` similar to the existing `SKIP_TESTS=1`: http://osquery.readthedocs.org/en/stable/development/building/#debug-builds-formatting-and-more

**Comment by mathieuk** [comment]
benchmark from that archive, oddly, won't build:

```
Linking CXX executable filter_test
make[3]: Leaving directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
[ 94%] Built target filter_test
make[3]: Entering directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
Scanning dependencies of target options_test
make[3]: Leaving directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
make[3]: Entering directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
[100%] Building CXX object test/CMakeFiles/options_test.dir/options_test.cc.o
Linking CXX executable options_test
Linking CXX executable fixture_test
make[3]: Leaving directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
make[3]: Leaving directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
[100%] Built target options_test
[100%] Built target fixture_test
make[2]: Leaving directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
make[1]: Leaving directory `/tmp/osquery-provisioning/benchmark-0.1.0/build'
make: *** No rule to make target `install'.  Stop.
make: *** [deps] Error 2
```
Before that it has other issues, like it being made with BSD tar ( gives warnings like `tar: Ignoring unknown extended header keyword 'SCHILY.dev'` ) and the directly being named `benchmark` instead of `benchmark-0.1.0`. 

I'm sure this all can be fixed. But maybe using the patch approach for specific systems is a more flexible way to go? Leaves the responsibility for building up to the distro provisioning scripts, instead of having multiple archives (which may be forgotten when updating) and/or archives that deviate from the source which may result in vcs-less "fork" of sorts, which may cause other issues down the line. 

Ofcourse, ideally I'd want to have it fixed at the source  through resolving https://github.com/google/benchmark/issues/134, but I'm a bit out of my depth with C++ so I'm having trouble getting that to move forward.

**Comment by theopolis** [comment]
Alright, I agree that the maintenance of the hosted and patched deps bundle is too much overhead. Let's roll with the patch until google/benchmark#134 lands. @mathieuk, do you mind squashing these 4 commits into 1?

**Comment by mathieuk** [comment]
Not at all, done.

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
:+1:

**Pull request merged**
