### PR TITLE
Split example SQL

### PR DESCRIPTION
**Pull request by spasam**
This seems to work. May be there is better way to do it!

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Ah dang, I was hoping that the `ok to test` would respect my tag limits. I guess I have more work to do in Jenkins. It should have limited the job selection to just `Code Audit`.

**Comment by osqueryer** [comment]
:no_good: The commit 4521b6166767434d164a66264f259baa1a24672d (Job results: [2526](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2526/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 4521b6166767434d164a66264f259baa1a24672d (Job results: [2752](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2752/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 4521b6166767434d164a66264f259baa1a24672d (Job results: [2754](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2754/)) failed one or more tests (**Windows**).

**Pull request merged**
