### PR TITLE
 Fix for issue-3953

### PR DESCRIPTION
**Pull request by uptycs-nishant**
Host header takes part in the signature calculation.
The problem was aws was setting the host and calculating the signature and http_client was resetting the host header un-conditionally.

### CODE REVIEW

**Comment by uptycs-nishant** [comment]
fixing #3953

**Comment by uptycs-nishant** [comment]
Thanks @securityclippy for your help in verifying this fix.

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 46f28e79e8da6a68ce46e77c15f0c38fc3e4808c (Job results: [2839](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2839/)) failed the code audit or documentation test.

**Pull request merged**
