### PR TITLE
Event index time and streaming

### PR DESCRIPTION
**Pull request by theopolis**
This is a work-in-progress step towards using "index" time instead of event time for event subscriber data retrieval. An "index" time will allow implicit a performance-enhancing data limitation that does not require/trigger expired events.

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by mofarrell** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
