### PR TITLE
Remove SSLv2 references

### PR DESCRIPTION
**Pull request by sharvilshah**
After upgrading to OS X 10.11, kept getting this while building from source:

```
Undefined symbols for architecture x86_64:
  "_SSLv2_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in libcppnetlib-client-connections.a(client.cpp.o)
  "_SSLv2_client_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in libcppnetlib-client-connections.a(client.cpp.o)
  "_SSLv2_server_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in libcppnetlib-client-connections.a(client.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This removes SSLv2 references just like we did for SSLv3 before.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by sharvilshah** [comment]
This may not be as simple as I thought.

While the above change builds and runs, on quitting `osqueryi` it segfaults with ` pointer being freed was not allocated`.

```
❯ lldb ./build/darwin10.11/osquery/osqueryi
(lldb) target create "./build/darwin10.11/osquery/osqueryi"
Current executable set to './build/darwin10.11/osquery/osqueryi' (x86_64).
(lldb) br set -n malloc_error_break
Breakpoint 1: where = libsystem_malloc.dylib`malloc_error_break, address = 0x0000000000012f3e

(lldb) run

Process 98385 launched: './build/darwin10.11/osquery/osqueryi' (x86_64)
I1217 21:25:28.973147 2117746688 options.cpp:56] Verbose logging enabled by config option
I1217 21:25:28.973372 2117746688 events.cpp:565] Event publisher failed setup: kernel: Cannot access /dev/osquery
W1217 21:25:28.973408 2117746688 events.cpp:767] Error registering subscriber: process_file_events: No kernel event publisher
I1217 21:25:28.973479 5844992 events.cpp:508] Starting event publisher run loop: diskarbitration
I1217 21:25:28.973503 6381568 events.cpp:508] Starting event publisher run loop: fsevents
I1217 21:25:28.973520 6918144 events.cpp:508] Starting event publisher run loop: iokit
I1217 21:25:28.973534 7454720 events.cpp:508] Starting event publisher run loop: scnetwork
osquery - being built, with love, at Facebook
Using a virtual database. Need help, type '.help'
osquery>
osqueryi(98385,0x7fff7e3a4000) malloc: *** error for object 0x101006a00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Process 98385 stopped
* thread #1: tid = 0x1331a4, 0x00007fff9d5cff3e libsystem_malloc.dylib`malloc_error_break, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00007fff9d5cff3e libsystem_malloc.dylib`malloc_error_break
libsystem_malloc.dylib`malloc_error_break:
->  0x7fff9d5cff3e <+0>: pushq  %rbp
    0x7fff9d5cff3f <+1>: movq   %rsp, %rbp
    0x7fff9d5cff42 <+4>: nop
    0x7fff9d5cff43 <+5>: nopl   (%rax)


(lldb) bt
* thread #1: tid = 0x1331a4, 0x00007fff9d5cff3e libsystem_malloc.dylib`malloc_error_break, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00007fff9d5cff3e libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00007fff9d5c1001 libsystem_malloc.dylib`free + 314
    frame #2: 0x00000001003f8649 osqueryi`lh_free + 81
    frame #3: 0x00000001003fcbb5 osqueryi`OBJ_NAME_cleanup + 80
    frame #4: 0x00000001003ebcbf osqueryi`EVP_cleanup + 34
    frame #5: 0x00000001005279fa osqueryi`boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() + 90
    frame #6: 0x000000010012befa osqueryi`std::__1::__shared_ptr_pointer<boost::asio::ssl::detail::openssl_init_base::do_init*, std::__1::default_delete<boost::asio::ssl::detail::openssl_init_base::do_init>, std::__1::allocator<boost::asio::ssl::detail::openssl_init_base::do_init> >::__on_zero_shared() + 42
    frame #7: 0x00007fff8ed79cb8 libc++.1.dylib`std::__1::__shared_weak_count::__release_shared() + 44
    frame #8: 0x00007fff8cbc346b libsystem_c.dylib`__cxa_finalize_ranges + 345
    frame #9: 0x00007fff8cbc376f libsystem_c.dylib`exit + 55
    frame #10: 0x00007fff970865b4 libdyld.dylib`start + 8
    frame #11: 0x00007fff970865ad libdyld.dylib`start + 1

(lldb) x/4xw 0x101006a00
0x101006a00: 0x00000000 0x00000000 0x00000000 0x00000000
```

Looking at the debugger somewhere after calling asio's `do_init` destructor, a null pointer is being freed, which can be anywhere in libressl, cpp-netlib or boost asio.

Thoughts?

**Comment by sharvilshah** [comment]
Also surprising that we already pass in a mask of `SSL_OP_NO_SSLv3 | SSL_OP_NO_SSLv2 | SSL_OP_ALL` but it seems to be not respected or is broken.

**Comment by theopolis** [comment]
Maybe blow away your build directory? You shouldn't be hitting either of these. What version of LibreSSL do you have installed through brew?

**Comment by sharvilshah** [comment]
I already did try that. Trying once more on master.

libressl: 2.3.1
boost: 1.5.9
cpp-netlib: 0.11.2

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Comment by sharvilshah** [comment]
Okay, that did not work and since you are able to build on 10.11, I will try to get a fresh 10.11 install in a VM and try building there. At least then I would know if there is something conflicting machine or not.

**Comment by theopolis** [comment]
In all cases, I'm OK with removing the SSLv2 detection since nothing needs it any more.

**Comment by sharvilshah** [comment]
Closing this. I fixed it by rebuilding boost and cpp-netlib on my machine.

**Pull request closed without merging**
