### PR TITLE
Allow freebsd to shadow to fix build

### PR DESCRIPTION
**Pull request by jedi22**

### CODE REVIEW

**Comment by jedi22** [comment]
test freebsd please

**Comment by osqueryer** [comment]
:-1: The commit 230eeab724e45c92b8036d6294878aec7fdbfebf (Job results: [1935](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1935/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 230eeab724e45c92b8036d6294878aec7fdbfebf (Job results: [1936](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1936/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
Looks good, if the conflicts are resolved.

**Comment by osqueryer** [comment]
:-1: The commit 71befe59baa82f601186bec477134f066f75467d (Job results: [5054](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5054/)) failed one or more tests (**Linux**).

**Pull request merged**
