### PR TITLE
[osx] added autorelease pools

### PR DESCRIPTION
**Pull request by mkareta**
Added autorelease pool to fix long term memory usage. 

Default autorelease pool is drained on thread exit, so we need to use nested pools to avoid memory leaks, since our query execution thread is long running.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit b7304e13cb39b6a36e03be1727c514a65b2366aa (Job results: [3628](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3628/)) failed the code audit or documentation test.

**Comment by fmanco** [comment]
ok to test to trigger darwin tests

**Comment by osqueryer** [comment]
:no_good: The commit b7304e13cb39b6a36e03be1727c514a65b2366aa (Job results: [3632](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3632/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit b6e6b65735d3230d435b328db4a940925a6cb524 (Job results: [3635](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3635/)) failed the code audit or documentation test.

**Comment by muffins** [comment]
@fmanco @mkareta looks like this wasn't passing the code audit CI test, can you hook us up with why this was landed? Also looks like there's an outstanding question from @obelisk that could use an answer.

**Comment by theopolis** [comment]
> looks like this wasn't passing the code audit CI test but it did 
https://jenkins.osquery.io/job/osqueryPullRequestAudit/3637/ (this builds `281eea7`)

`clang-format` can be at different versions depending on your setup. The version that Jenkins runs is from `/usr/local/osquery/bin` this is at version 6.0.0, to make sure you're running this version run `make deps`. On macOS or within your IDE, you may be using a system or plugin-provided version. My guess is this version fragmentation is leading to the weird behavior you are describing.

**Comment by fmanco** [comment]
That makes sense @theopolis , thanks for taking a look. Indeed testing now on my machine this shouldn't have passed, but the test definitely did.

**Pull request merged**
