### PR TITLE
Allow building as non-root on MacOS

### PR DESCRIPTION
**Pull request by fiorix**
This was my first time trying to build osquery on my mac and I hit a couple of problems:

1. Cloned osquery inside my personal dropbox directory, which is `~/Dropbox (Personal)/...` and due to the space on the directory name it failed to create a symlink - this one was fixed by adding double quotes in the Makefile in the `ln -s` command

2. During `make deps` it invoked pip, which wanted root to install stuff in the system's PYTHONPATH. I usually refuse to give root to build things, so I changed one of the provisioning scripts to make it call `pip install --user` instead; not sure you want this patch as-is because it may (will, likely) break other builds

Anyway, after these tweaks I was able to build it without root, like this:

```
mkdir -p ~/tmp/osquery_deps
export PYTHONPATH=~/tmp/osquery_deps/lib/python2.7/site-packages
export OSQUERY_DEPS=~/tmp/osquery_deps
make deps
make
```

I don't expect this to be merged, but I hope it'd serve as a heads up for an alternative to not using root to build osquery.

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by fiorix** [comment]
Just confirmed that after the build no binaries link to files in my home or temp dir:

```
osqueryi:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.9.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1125.3.4)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.20.16)
	/System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement (compatibility version 1.0.0, current version 1205.20.31)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxar.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.12.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
osqueryd:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.9.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1125.3.4)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.20.16)
	/System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement (compatibility version 1.0.0, current version 1205.20.31)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxar.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.12.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
osquery_tests:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
osquery_tables_tests:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.9.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1125.3.4)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.20.16)
	/System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement (compatibility version 1.0.0, current version 1205.20.31)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxar.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.12.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
osquery_additional_tests:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.9.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1125.3.4)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.20.16)
	/System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement (compatibility version 1.0.0, current version 1205.20.31)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxar.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.12.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
osquery_benchmarks:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.9.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1125.3.4)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.20.16)
	/System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement (compatibility version 1.0.0, current version 1205.20.31)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxar.1.dylib (compatibility version 1.0.0, current version 1.3.0)
	/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.12.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by fiorix** [comment]
I'm actually surprised that these checks pass. Perhaps we should remove the "sudo" command from freebsd to make it build like this too.

**Comment by theopolis** [comment]
@fiorix, if you have time to test, `vagrant up freebsd11`, it `rsync`s the directory to `/vagrant` so you can `cd /vagrant; gmake deps`.

**Comment by fiorix** [comment]
The build on BSD is pretty broken :)

First, the rsync to /vagrant doesn't seem to work because something in the build process things that the build dir is a git repo.

Then, there's quite a few deps missing in the BSD image in that Vagrantfile. Giving it another shot later and if it works I'll report back here.

**Comment by theopolis** [comment]
> First, the rsync to /vagrant doesn't seem to work because something in the build process thinks that the build dir is a git repo.

Weird, seems to work mostly fine on my host. We don't support/test the vagrant builds, only provide them for quick and easy testing but I'd like to keep them as working as possible. Here's my experience:
```
$ vagrant up freebsd11
Bringing machine 'freebsd11' up with 'virtualbox' provider...
==> freebsd11: Importing base box 'bento/freebsd-11'...
==> freebsd11: Matching MAC address for NAT networking...
==> freebsd11: Checking if box 'bento/freebsd-11' is up to date...
==> freebsd11: Setting the name of the VM: osquery_freebsd11_1511844502910_66503
==> freebsd11: Clearing any previously set network interfaces...
==> freebsd11: Preparing network interfaces based on configuration...
    freebsd11: Adapter 1: nat
    freebsd11: Adapter 2: hostonly
==> freebsd11: Forwarding ports...
    freebsd11: 22 (guest) => 2222 (host) (adapter 1)
==> freebsd11: Running 'pre-boot' VM customizations...
==> freebsd11: Booting VM...
==> freebsd11: Waiting for machine to boot. This may take a few minutes...
    freebsd11: SSH address: 127.0.0.1:2222
    freebsd11: SSH username: vagrant
    freebsd11: SSH auth method: private key
    freebsd11: 
    freebsd11: Vagrant insecure key detected. Vagrant will automatically replace
    freebsd11: this with a newly generated keypair for better security.
    freebsd11: 
    freebsd11: Inserting generated public key within guest...
    freebsd11: Removing insecure key from the guest if it's present...
    freebsd11: Key inserted! Disconnecting and reconnecting using new SSH key...
==> freebsd11: Machine booted and ready!
==> freebsd11: Checking for guest additions in VM...
==> freebsd11: Configuring and enabling network interfaces...
==> freebsd11: Installing rsync to the VM...
==> freebsd11: Rsyncing folder: /home/teddy/git/osquery/ => /vagrant
==> freebsd11:   - Exclude: [".vagrant/", "build", ".git/objects", ".git/modules/third-party/objects"]
==> freebsd11: Running provisioner: shell...
    freebsd11: Running: inline script
==> freebsd11: Updating FreeBSD repository catalogue...
[...]
==> freebsd11: Install them as occasion demands.
==> freebsd11: ====
==> freebsd11: fdesc   /dev/fd     fdescfs     rw  0   0
==> freebsd11: proc    /proc       procfs      rw  0   0
```
Then:
```
$ vagrant ssh freebsd11
$ cd /vagrant/
$ gmake sysprep # This is most likely the missing command to setup needed pkgs
[...]
[+] running auxiliary initialization
fatal: Not a git repository: /vagrant/third-party/../.git/modules/third-party
gmake: *** [Makefile:211: sysprep] Error 128
$
```
That final error is because the `third-party` folder was rsync'd and not shared via `nfs` which is the default for vagrant. So it's just a folder, not a git submodule.

**Comment by theopolis** [comment]
I applied your changes locally (removing the `sudo` on FreeBSD) and it works!

**Comment by fiorix** [comment]
👍

**Pull request merged**
