### PR TITLE
Bump rocksdb to 4.9

### PR DESCRIPTION
**Pull request by thedrow**
There are some API changes in 4.8 & 4.9.
I'm not sure if we're using those APIs yet. Let's see if the tests pass first.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 525c338f115ce7bb90c037dffd6946cc9c21aa8f (Job results: [3121](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3121/)) failed one or more tests (**OS X/Linux**).

**Comment by thedrow** [comment]
I'm not sure how to publish the built binaries or if I'm allowed to do so.

**Comment by osqueryer** [comment]
:-1: The commit ab510554ce7f84d74c50d20e8210d2f4fb0e83c1 (Job results: [3122](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3122/)) failed one or more tests (**OS X/Linux**).

**Comment by thedrow** [comment]
Is this failing on CentOS 6 for the same reason as #2181?

**Comment by theopolis** [comment]
I'm not entirely sure why CentOS6 failed. I tried to locally run your patch on a CentOS6 build host and it works. These things are about at the end of their lives and will be moved into AWS soon. I'm going to run the tests again out of curiosity but will merge the upgrade regardless.

There are some added ENV variables that allow a host to build a bottled version of the dependency, but I need to upload that result to S3. It would be cool to have automation there but dependencies don't change often enough. ;)

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
