### PR TITLE
Windows: Copy required DLLs into the build directory

### LINKED ISSUE #2296: Have CMake build windows binaries
Add this to our cmake for building the windows binaries, as opposed to the bat files.
`cmake --build . --target shell --config Release`

### PR DESCRIPTION
**Pull request by artemdinaburg**
* Copy DLLs into shell and daemon build directories
* Update batch files to use `cmake --build` instead of msbuild
* Remove copy files commands from batch file
* Update readme to reflect new changes

This closes #2296.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit c0e7a78c99cf5ac29f3de89d946a307c1fd6c64a (Job results: [3005](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3005/)) failed one or more tests.

**Pull request merged**
