### PR TITLE
linux: updating linuxbrew pins

### PR DESCRIPTION
**Pull request by muffins**
This addresses #3463

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 100f445416efdc47f37df1f18ebd207f0b26be0b (Job results: [1365](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1365/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 100f445416efdc47f37df1f18ebd207f0b26be0b (Job results: [1366](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1366/)) failed one or more tests (**macOS/OS X**).

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 100f445416efdc47f37df1f18ebd207f0b26be0b (Job results: [1367](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1367/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 100f445416efdc47f37df1f18ebd207f0b26be0b (Job results: [1368](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1368/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit 100f445416efdc47f37df1f18ebd207f0b26be0b (Job results: [1996](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1996/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 100f445416efdc47f37df1f18ebd207f0b26be0b (Job results: [5253](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5253/)) failed one or more tests (**Linux**).

**Comment by jedi22** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 100f445416efdc47f37df1f18ebd207f0b26be0b (Job results: [1997](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1997/)) failed the code audit or documentation test.

**Comment by muffins** [comment]
`make format_master` on OS X and Linux isn't needing any changes, this looks to be Jenkins error.

**Pull request merged**
