### PR TITLE
Refactored timer functionality in osquery shell

### PR DESCRIPTION
**Pull request by yying**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2290/merge (Job: 2933) failed :-1:

**Comment by PoppySeedPlehzr** [comment]
```
5/9 Test #5: python_test_osqueryd .............***Failed   38.85 sec
.I0725 14:53:03.841156 12023 options.cpp:61] Verbose logging enabled by config option
I0725 14:53:03.841502 12023 daemon.cpp:38] Not starting the distributed query service: Distributed query service not enabled.
...FI0725 14:53:40.071988 12068 options.cpp:61] Verbose logging enabled by config option
I0725 14:53:40.072194 12068 daemon.cpp:38] Not starting the distributed query service: Distributed query service not enabled.
.
======================================================================
FAIL: test_5_daemon_sigint (__main__.DaemonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/ubuntu16/tools/tests/test_base.py", line 455, in wrapper
    raise exceptions[0][0]
AssertionError: -2 != 130

----------------------------------------------------------------------
Ran 6 tests in 38.746s

FAILED (failures=1)
Test (attempt 1) DaemonTests::test_5_daemon_sigint failed: -2 != 130 (test_base.py:437)
Test (attempt 2) DaemonTests::test_5_daemon_sigint failed: -2 != 130 (test_base.py:437)
Test (attempt 3) DaemonTests::test_5_daemon_sigint failed: -2 != 130 (test_base.py:437)
```

**Pull request merged**
