### PR TITLE
Make syslog rate limit configurable by flag

### PR DESCRIPTION
**Pull request by zwass**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 6f26cb1b6e2aca8d93b49cc0867c68999d38dd5a (Job results: [3365](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3365/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2c18a603a6356fd6414430491f97ab2c1298e11a (Job results: [370](https://jenkins.osquery.io/job/osqueryPullRequestBuild/370/)) failed one or more tests (**Windows**).

**Comment by zwass** [comment]
Windows failure looks unrelated:
```
ERROR: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: c:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10 at hudson.remoting.Channel@4472727e:Windows10_1: java.io.IOException: Unable to delete 'c:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10\build\windows10\osquery\sql'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
ERROR: Cannot delete workspace: remote file operation failed: c:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10 at hudson.remoting.Channel@4472727e:Windows10_1: java.io.IOException: Unable to delete 'c:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10\build\windows10\osquery\sql'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Finished: FAILURE
```

**Comment by theopolis** [comment]
I've never encountered that before, maybe a race within Jenkins?

**Comment by theopolis** [comment]
Let's send it back to the queue, @osqueryer test this please

**Pull request merged**
