### PR TITLE
Added known_hosts table

### PR DESCRIPTION
**Pull request by PickmanSec**
added known_hosts table

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by PickmanSec** [comment]
Don't think this is my fault.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
Right, this is not your bug. It is still a bug in the `hash` table and is not hitting on RHEL7 due to an updated grub package.

**Pull request merged**
