### PR TITLE
deps: Rebuild all dependencies for Darwin and Linux (v5)

### PR DESCRIPTION
**Pull request by theopolis**
This kick's off the set of v3.0 changes! The osquery build "runtime" was stagnating and rebuilding every year is a good way to bring in new changes, verify we still run on older platforms, and audit any aging configurations. This rebuild is also the first step towards supporting a 'naked' build, similar to most CMake projects where osquery's build does not force every option.

Here's an overview of what this change includes:

- This changes osquery on Linux to use LLVM's libc++ instead of GCC's libstdc++
- LLVM/Clang is now at version 5.0.1, which includes incremental ThinLTO (LTO cache). This will improve relinking time on Linux to sub-60s builds.
- The old size of `osqueryd` was 24945808, the new size is 24172456, mostly from `-Oz`, further reduction with new compiler version 24020368 (900kB of executable code reduction).
- Reduced number of dependencies, shorter bootstrap times for both Linux and Darwin.
- LLVM coverage is at 100%, all code in osquery was compiled with `clang` on POSIX platforms.
- LLVM install is now nearly half the size on Linux, which halves the disk space required for the build runtime.
- On MacOS, the linking requirements are relaxed but this is not perfect. The code still relies on each dependency's configuration to decide weak linking correctly. We plan to address this more completely in the future.
- Runtime space requirements are now 579MB on macOS, 1.6GB on Linux.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 9d3a8d7339dc29db832973540de15f7ef86f081f (Job results: [2955](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2955/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 9d3a8d7339dc29db832973540de15f7ef86f081f (Job results: [6354](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6354/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 9d3a8d7339dc29db832973540de15f7ef86f081f (Job results: [6355](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6355/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 595f06722456e0b97cb8b968730e73674c724bf9 (Job results: [2956](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2956/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 595f06722456e0b97cb8b968730e73674c724bf9 (Job results: [6356](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6356/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 595f06722456e0b97cb8b968730e73674c724bf9 (Job results: [6357](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6357/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 595f06722456e0b97cb8b968730e73674c724bf9 (Job results: [2449](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2449/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 595f06722456e0b97cb8b968730e73674c724bf9 (Job results: [2958](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2958/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 595f06722456e0b97cb8b968730e73674c724bf9 (Job results: [6360](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6360/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 595f06722456e0b97cb8b968730e73674c724bf9 (Job results: [6361](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6361/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit d5698e7725cbd761381cea0cd2002cde590c758a (Job results: [2959](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2959/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit d5698e7725cbd761381cea0cd2002cde590c758a (Job results: [6362](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6362/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d5698e7725cbd761381cea0cd2002cde590c758a (Job results: [6363](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6363/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit d5698e7725cbd761381cea0cd2002cde590c758a (Job results: [2960](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2960/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit d5698e7725cbd761381cea0cd2002cde590c758a (Job results: [6364](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6364/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d5698e7725cbd761381cea0cd2002cde590c758a (Job results: [6365](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6365/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 7c292c1e2eced191eef8322ba01fbe714b4aba61 (Job results: [2961](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2961/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 7c292c1e2eced191eef8322ba01fbe714b4aba61 (Job results: [6366](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6366/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 96e82619fd49d22d1440718a913a9d32775adfee (Job results: [2962](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2962/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 96e82619fd49d22d1440718a913a9d32775adfee (Job results: [6368](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6368/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 96e82619fd49d22d1440718a913a9d32775adfee (Job results: [6369](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6369/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 16999c61ae7625a5b720ff9550cfe0e51c9edbea (Job results: [2966](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2966/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 16999c61ae7625a5b720ff9550cfe0e51c9edbea (Job results: [2459](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2459/)) failed one or more tests (**macOS/OS X**).

**Pull request merged**
