### PR TITLE
reorganized includes to improve compile time 2

### PR DESCRIPTION
**Pull request by mkareta**
This PR is based on #4445 please do not review it before #4445 is merged.
This PR is part of #4076

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit e44be65640c1744f0af4880fcdd61fd7dd4ad458 (Job results: [7283](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7283/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e44be65640c1744f0af4880fcdd61fd7dd4ad458 (Job results: [4189](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4189/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit e44be65640c1744f0af4880fcdd61fd7dd4ad458 (Job results: [7286](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7286/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 898f0255cee1c39c5766441516bfc3f81d6c9779 (Job results: [4200](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4200/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 898f0255cee1c39c5766441516bfc3f81d6c9779 (Job results: [3264](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3264/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 898f0255cee1c39c5766441516bfc3f81d6c9779 (Job results: [7294](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7294/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 898f0255cee1c39c5766441516bfc3f81d6c9779 (Job results: [1711](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1711/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 898f0255cee1c39c5766441516bfc3f81d6c9779 (Job results: [4203](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4203/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 898f0255cee1c39c5766441516bfc3f81d6c9779 (Job results: [7298](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7298/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 046f7c9f49614f095ff2eb1ace6a9abb0cca9b10 (Job results: [4216](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4216/)) failed one or more tests (**Windows**).

**Comment by akindyakov** [comment]
Actually not fine, this is a second thought. Since your change it would not be enough to include `first.h` if you need class from it, you also should include `status.h`. It is bit confusing, isn't it?
Look at the example: https://gist.github.com/akindyakov/7aea290e534674915fa46e3e795bdf29

**Pull request merged**
