### PR TITLE
build: Reduce compile time by 20%

### PR DESCRIPTION
**Pull request by theopolis**
This is a roll up of refactors. It includes several reorganizations that lead to a 40k reduction in include file reads per-build (just core, not including tests).

This is accomplished through 3 significant changes:
- The "plugin" structures and classes are separated from the "registry" factory.
- Mutexes and locking are not in "core" includes anymore.
- The "table" headers is greatly reduced, no longer including ptree or lexical casting.

The last part, removal of lexical casting, is substituted with the C++11 string-to-number literal methods. These can except but for the most part the lexical casting was not catching exceptions so I've chosen to keep the callsites as dangerous as I found them.

I also noticed a lack of doube conversion need. This is concerning as I've seen a few columns use double-type values. Sooner rather than later we should work on preserving the value types for each type row.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 8f1ca53e9fd83ddef1fda27b06e29b5dab6f7b18 (Job results: [2525](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2525/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 8f1ca53e9fd83ddef1fda27b06e29b5dab6f7b18 (Job results: [2526](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2526/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 8f1ca53e9fd83ddef1fda27b06e29b5dab6f7b18 (Job results: [3323](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3323/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 8f1ca53e9fd83ddef1fda27b06e29b5dab6f7b18 (Job results: [3324](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3324/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 296544d9a6f18431300df30d966feeef857efec0 (Job results: [1586](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1586/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
@mkareta I saw you were interested in this, I tried to take care of the boring part and resolved all of the merge conflicts. It needs some love for FreeBSD and Windows, essentially there are callsites not covered by the change from boost's lexical cast to C++'s `to_string`. I looked very quickly and they seemed manageable. If you don't have time for this, that's OK I can get to it later on, but it's going to take a while on my side.

**Comment by osqueryer** [comment]
:-1: The commit 296544d9a6f18431300df30d966feeef857efec0 (Job results: [1587](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1587/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 296544d9a6f18431300df30d966feeef857efec0 (Job results: [4068](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4068/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 296544d9a6f18431300df30d966feeef857efec0 (Job results: [4069](https://jenkins.osquery.io/job/osqueryPullRequestWindows/4069/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 296544d9a6f18431300df30d966feeef857efec0 (Job results: [7164](https://jenkins.osquery.io/job/osqueryPullRequestLinux/7164/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
A lot of this was added in subsequent commits.

**Pull request closed without merging**
