### PR TITLE
Windows 10 Testing

### PR DESCRIPTION
**Pull request by yying**
No a real PR yet. Using this for Windows 10 Jenkins debugging...

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:+1: The commit b37ad55e6179c51a008ddc38b9d2f417d1eb1dab (Job results: [3015](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3015/)) was built successfully!

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:+1: The commit b37ad55e6179c51a008ddc38b9d2f417d1eb1dab (Job results: [3016](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3016/)) was built successfully!

**Comment by theopolis** [comment]
The issues with building are in the dependencies install script. We are not yet at compiling or CMake, let alone running the tests.

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:+1: The commit b37ad55e6179c51a008ddc38b9d2f417d1eb1dab (Job results: [3017](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3017/)) was built successfully!

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:+1: The commit b37ad55e6179c51a008ddc38b9d2f417d1eb1dab (Job results: [3018](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3018/)) was built successfully!

**Comment by theopolis** [comment]
The last-most-recent build error for Windows10:
```
VisualStudio2015Community v2015.03.01 [Approved]
System.Collections.Hashtable
Visual Studio will be installed from Web
Install-ChocolateyPackage VisualStudio2015Community exe /Quiet /NoRestart /Log C:\WINDOWS\TEMP\chocolatey\vs.log /AdminFile C:\WINDOWS\TEMP\chocolatey\AdminDeployment.xml http://download.microsoft.com/download/0/B/C/0BC321A4-013F-479C-84E6-4A2F90B11269/vs_community.exe -validExitCodes 0 3010 2147781575 -2147185721 -2147205120 -2147172352
Installing VisualStudio2015Community...
Chocolatey timed out waiting for the command to finish. The timeout 
 specified (or the default value) was '2700' seconds. Perhaps try a 
 higher `--execution-timeout`? See `choco -h` for details.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of visualstudio2015community was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2015Community\Tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - visualstudio2015community (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2015Community\Tools\ChocolateyInstall.ps1'.
 See log for details.
```

**Pull request closed without merging**
