### PR TITLE
tidy: Improve clang-tidy (modernize) list of checks and run across codebase

### PR DESCRIPTION
**Pull request by theopolis**
This is a code mod from `clang-tidy`. It touches lots of files so several open PRs may need to be rebased if this is landed.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit d38914f8a1800ce7942d16b222b53a7b17efa42e (Job results: [2711](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2711/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit d38914f8a1800ce7942d16b222b53a7b17efa42e (Job results: [1005](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1005/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d38914f8a1800ce7942d16b222b53a7b17efa42e (Job results: [1006](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1006/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d38914f8a1800ce7942d16b222b53a7b17efa42e (Job results: [2178](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2178/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d38914f8a1800ce7942d16b222b53a7b17efa42e (Job results: [2179](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2179/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit a5767b1d0c5c855998c86fc7ab28c0af3d34eec1 (Job results: [1007](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1007/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:no_good: The commit a5767b1d0c5c855998c86fc7ab28c0af3d34eec1 (Job results: [2712](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2712/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit a5767b1d0c5c855998c86fc7ab28c0af3d34eec1 (Job results: [2180](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2180/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit a5767b1d0c5c855998c86fc7ab28c0af3d34eec1 (Job results: [2181](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2181/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 498d0ed5a1770d77b93dd51525aa9c1059cf7169 (Job results: [1009](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1009/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 498d0ed5a1770d77b93dd51525aa9c1059cf7169 (Job results: [1010](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1010/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d89e91fa2518179959d9c6c027469d55a07cf137 (Job results: [1011](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1011/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d89e91fa2518179959d9c6c027469d55a07cf137 (Job results: [1012](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1012/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit f779e30298ae819c71f60d25740bf470777842b3 (Job results: [2204](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2204/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
There's never a good time to do these sorts of code mods. I apologize to those who have to rebase. :'(

**Pull request merged**
