### PR TITLE
tables: porting the process_memory_map table to windows

### PR DESCRIPTION
**Pull request by muffins**
This brings the `process_memory_map` table to Windows. Below is a sample of the output. There's a few columns that don't _exactly_ map over, so I'm open to suggestions about what values we might want for `device`, `inode`, and `pseudo`.

```
osquery> select * from process_memory_map limit 10;
+-----+--------------------+--------------------+-------------------+-----------------+--------+-------+---------------------------------+--------+
| pid | start              | end                | permissions       | offset          | device | inode | path                            | pseudo |
+-----+--------------------+--------------------+-------------------+-----------------+--------+-------+---------------------------------+--------+
| 420 | 0x00007FF722080000 | 0x00007ff722081000 | PAGE_READONLY     | 140699404599296 | -1     | -1    | c:\windows\system32\svchost.exe | -1     |
| 420 | 0x00007FF722081000 | 0x00007ff722086000 | PAGE_EXECUTE_READ | 140699404599296 | -1     | -1    | c:\windows\system32\svchost.exe | -1     |
| 420 | 0x00007FF722086000 | 0x00007ff72208a000 | PAGE_READONLY     | 140699404599296 | -1     | -1    | c:\windows\system32\svchost.exe | -1     |
| 420 | 0x00007FF72208A000 | 0x00007ff72208b000 | PAGE_READWRITE    | 140699404599296 | -1     | -1    | c:\windows\system32\svchost.exe | -1     |
| 420 | 0x00007FF72208B000 | 0x00007ff72208f000 | PAGE_READONLY     | 140699404599296 | -1     | -1    | c:\windows\system32\svchost.exe | -1     |
| 420 | 0x00007FF8674D0000 | 0x00007ff8674d1000 | PAGE_READONLY     | 140704861716480 | -1     | -1    | C:\Windows\SYSTEM32\ntdll.dll   | -1     |
| 420 | 0x00007FF8674D1000 | 0x00007ff8675e0000 | PAGE_EXECUTE_READ | 140704861716480 | -1     | -1    | C:\Windows\SYSTEM32\ntdll.dll   | -1     |
| 420 | 0x00007FF8675E0000 | 0x00007ff867625000 | PAGE_READONLY     | 140704861716480 | -1     | -1    | C:\Windows\SYSTEM32\ntdll.dll   | -1     |
| 420 | 0x00007FF867625000 | 0x00007ff867626000 | PAGE_READWRITE    | 140704861716480 | -1     | -1    | C:\Windows\SYSTEM32\ntdll.dll   | -1     |
| 420 | 0x00007FF867626000 | 0x00007ff867628000 | PAGE_WRITECOPY    | 140704861716480 | -1     | -1    | C:\Windows\SYSTEM32\ntdll.dll   | -1     |
+-----+--------------------+--------------------+-------------------+-----------------+--------+-------+---------------------------------+--------+
```

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 8dafc0dd03a421b7e49b57bb196d43a57fe4f288 (Job results: [543](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/543/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
LGTM

**Comment by osqueryer** [comment]
:-1: The commit 8dafc0dd03a421b7e49b57bb196d43a57fe4f288 (Job results: [544](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/544/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
Ignore the FreeBSD error.

**Pull request merged**
