### PR TITLE
Document --host_identifier=specified CLI option

### PR DESCRIPTION
**Pull request by bmoylan**
This feature was added in #3165 but was never documented.

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit e7354bc3b0850243ad4d9837b6a45e249da2a491 (Job results: [2360](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2360/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit e7354bc3b0850243ad4d9837b6a45e249da2a491 (Job results: [2883](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2883/)) failed the code audit or documentation test.

**Comment by muffins** [comment]
ok to test

**Pull request merged**
