### PR TITLE
Add kauth kernel extension.

### PR DESCRIPTION
**Pull request by babakbahamin**
With comments from the first attempt addressed.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by marpaia** [comment]
ok to test

**Comment by marpaia** [comment]
need those green checkmarks

**Comment by mofarrell** [comment]
@babakbahamin Great to see this up here.  A kernel extension is now being developed in the [kernel](https://github.com/facebook/osquery/tree/kernel) branch.  It currently is setup to send exec events back to the daemon.  If you are interested, it would be great to add the additional functionality you have to that branch.  I plan to work on a more formal interface for kernel land event publishers.  This will make it easier to support many event types.

**Comment by babakbahamin** [comment]
Oh nice! That looks good. Going to close this pull request for now.

**Pull request closed without merging**
