### PR TITLE
tables: porting python_packages to Windows

### PR DESCRIPTION
**Pull request by muffins**
This brings the python packages table to Windows and adds a new detection for Windows builds to build `RelWithDebInfo` releases if the `RELWITHDEBINFO`env variable is found.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit eef46ee8937b9c0874e33c9fe0617d11113f948c (Job results: [737](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/737/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit eef46ee8937b9c0874e33c9fe0617d11113f948c (Job results: [1922](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1922/)) failed one or more tests (**macOS/OS X**).

**Comment by muffins** [comment]
Fixes inbound :p

**Comment by osqueryer** [comment]
:-1: The commit eef46ee8937b9c0874e33c9fe0617d11113f948c (Job results: [1923](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1923/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit eef46ee8937b9c0874e33c9fe0617d11113f948c (Job results: [5810](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5810/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit eef46ee8937b9c0874e33c9fe0617d11113f948c (Job results: [5811](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5811/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit eef46ee8937b9c0874e33c9fe0617d11113f948c (Job results: [738](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/738/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit e62a7cbffc8175cf34b9c3ca4a3ab046737aa77a (Job results: [5813](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5813/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e62a7cbffc8175cf34b9c3ca4a3ab046737aa77a (Job results: [5814](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5814/)) failed one or more tests (**Linux**).

**Comment by muffins** [comment]
Interesting, I'm not able to repro the test fail on Ubuntu 17:
```
osquery git:win-python-packages ❯ make test
Test project /home/thor/work/repos/osquery/build/zesty
    Start 1: osquery_tests
1/8 Test #1: osquery_tests ....................   Passed    0.38 sec
    Start 2: osquery_additional_tests
2/8 Test #2: osquery_additional_tests .........   Passed   15.28 sec
    Start 3: osquery_tables_tests
3/8 Test #3: osquery_tables_tests .............   Passed    0.27 sec
    Start 4: python_test_osqueryi
4/8 Test #4: python_test_osqueryi .............   Passed    4.99 sec
    Start 5: python_test_osqueryd
5/8 Test #5: python_test_osqueryd .............   Passed   14.70 sec
    Start 6: python_test_additional
6/8 Test #6: python_test_additional ...........   Passed    0.28 sec
    Start 7: python_test_extensions
7/8 Test #7: python_test_extensions ...........   Passed    5.53 sec
    Start 8: python_test_example_queries
8/8 Test #8: python_test_example_queries ......   Passed   10.31 sec

100% tests passed, 0 tests failed out of 8

Total Test time (real) =  51.75 sec
```

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit e62a7cbffc8175cf34b9c3ca4a3ab046737aa77a (Job results: [5815](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5815/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e62a7cbffc8175cf34b9c3ca4a3ab046737aa77a (Job results: [5816](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5816/)) failed one or more tests (**Linux**).

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit e62a7cbffc8175cf34b9c3ca4a3ab046737aa77a (Job results: [5819](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5819/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e62a7cbffc8175cf34b9c3ca4a3ab046737aa77a (Job results: [5821](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5821/)) failed one or more tests (**Linux**).

**Comment by muffins** [comment]
Oh man I dun goofed. Fix for the python backdoor pack inbound.

**Pull request merged**
