### PR TITLE
Minor fixes in "logger plugins" docs

### PR DESCRIPTION
**Pull request by zwass**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Nice, mind adding a note about using multiple logger plugins? That the `--logger_plugin` flag can contain a comma-separated list of plugin names?

**Comment by zwass** [comment]
I think that note should go in the "configuration" section (https://osquery.readthedocs.org/en/latest/deployment/logging/) rather than this "development" section. Your thoughts?

**Comment by zwass** [comment]
Actually, that section that describes logging setup doesn't describe logger plugins at all. Perhaps a section should be added describing what they do and that multiple can be used?

**Comment by theopolis** [comment]
Definitely, perhaps it could be inserted into the first few paragraphs within: http://osquery.readthedocs.org/en/stable/deployment/logging/.

And then a call out in: http://osquery.readthedocs.org/en/stable/installation/cli-flags/#loggingresults-flags that mentions the bit about comma-delimited plugin names will allow multiple loggers.

**Comment by zwass** [comment]
My bad for opening this in the central repo. Now that I'm not in the FB Github organization, I can't work on this branch further, so I'm closing this request and working in my repo. Please delete the branch when you get a chance.

**Comment by theopolis** [comment]
Deleted!

**Pull request closed without merging**
