### PR TITLE
deps: Updating windows to boost 1.66.0

### PR DESCRIPTION
**Pull request by muffins**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 0fda68c818bdf7585640c7d472920a607519c257 (Job results: [3246](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3246/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 0fda68c818bdf7585640c7d472920a607519c257 (Job results: [3247](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3247/)) failed one or more tests (**Windows**).

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 0fda68c818bdf7585640c7d472920a607519c257 (Job results: [3248](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3248/)) failed one or more tests (**Windows**).

**Pull request merged**
