### PR TITLE
[#1527] Add a --profile option to the shell, replace 'run'

### PR DESCRIPTION
**Pull request by theopolis**
This adds a `--profile` option to the shell that silently runs the input query(ies). This should be used in combination with the `./tools/profile.py` wrapper to turn the output into usable form. This python script can provide colored stdout or JSON output. It can also detect/report memory leaks.

The profiling functionality used to exist in a smaller/standalone "runner" binary that was not shipped with packages. That is no longer needed and the small implementation had been removed.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Comment by sharvilshah** [comment]
Is the plan to ship `profile.py` (valgrind/leaks wrapper) alongside the binaries?
Sorry for the dumb question, I got excited as I thought that we would embed a profiler. By that I mean either using valgrind or the like as a library, or implementing our own if that's not possible and started looking at how profilers work (although not the best use of my time, super interesting).

**Comment by theopolis** [comment]
It hadn't occurred to me to ship the `profile.py` or provide the profiling stats output within the shell. This is more to prevent folks from having to compile/build. Moving forward, you can use any `osqueryi` combined with a source checkout to profile your queries or do leak checking/reproduction.

It's definitely possible to ship more standalone (or out of the box) profiling capabilities but that'll be wishlist/like-to-have features!

**Pull request merged**
