### PR TITLE
Bump augeas to 1.7 GA

### PR DESCRIPTION
**Pull request by thedrow**
1.7 landed 8 days ago :)
I don't think we should expect any problems.

### CODE REVIEW

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by PoppySeedPlehzr** [comment]
disregard any windows test fails :) I'm currently working on fixing them!

**Comment by osqueryer** [comment]
:-1: The commit 279fbddbb7382614289d87bb815d39d1cad72d55 (Job results: [11](https://jenkins.osquery.io/job/osqueryPullRequestBuild/11/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 279fbddbb7382614289d87bb815d39d1cad72d55 (Job results: [3722](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3722/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 279fbddbb7382614289d87bb815d39d1cad72d55 (Job results: [721](https://jenkins.osquery.io/job/osqueryPullRequestBuild/721/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
This fails Linux and OS X because the "build from release" requirements are a bit different than "build from source". Windows is failing because there're outstanding needs for the existing, non-`augeas`, tests to pass. @PoppySeedPlehzr  is working to fix them right now.

Let's skip bumping `augeas` for right now. The "rc1" I concocted is only 2 commits behind GA.

**Comment by thedrow** [comment]
@theopolis So let's open an issue about it instead.

**Pull request closed without merging**
