### PR TITLE
Carved files no longer contain carver fs path

### PR DESCRIPTION
**Pull request by poppyseedplehzr**

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit d8267094369c42fc0454911cefaad5407b7cd0c0 (Job results: [1558](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1558/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit d8267094369c42fc0454911cefaad5407b7cd0c0 (Job results: [4720](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4720/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d8267094369c42fc0454911cefaad5407b7cd0c0 (Job results: [869](https://jenkins.osquery.io/job/osqueryPullRequestOSX/869/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d8267094369c42fc0454911cefaad5407b7cd0c0 (Job results: [4721](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4721/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d8267094369c42fc0454911cefaad5407b7cd0c0 (Job results: [870](https://jenkins.osquery.io/job/osqueryPullRequestOSX/870/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d8267094369c42fc0454911cefaad5407b7cd0c0 (Job results: [1599](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1599/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d8267094369c42fc0454911cefaad5407b7cd0c0 (Job results: [1600](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1600/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [1601](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1601/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [4722](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4722/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [1602](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1602/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [4723](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4723/)) failed one or more tests (**Linux**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [1603](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1603/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [4724](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4724/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [1604](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1604/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [4725](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4725/)) failed one or more tests (**Linux**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [4736](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4736/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [1611](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1611/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5605a8ea7f9cb5b1931c3670ee23ac52d83b5a08 (Job results: [1612](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1612/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:no_good: The commit bd2aecce0381592fe7e402cb55212654cda828c6 (Job results: [1568](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1568/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 04f815f5bcff1add3772a903d441aa2987b5fcee (Job results: [882](https://jenkins.osquery.io/job/osqueryPullRequestOSX/882/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 04f815f5bcff1add3772a903d441aa2987b5fcee (Job results: [4739](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4739/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 04f815f5bcff1add3772a903d441aa2987b5fcee (Job results: [883](https://jenkins.osquery.io/job/osqueryPullRequestOSX/883/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 04f815f5bcff1add3772a903d441aa2987b5fcee (Job results: [4740](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4740/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 04f815f5bcff1add3772a903d441aa2987b5fcee (Job results: [1614](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1614/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 04f815f5bcff1add3772a903d441aa2987b5fcee (Job results: [1615](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1615/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 9592d03657e1bcbd85112c55ce1c03a45410fce3 (Job results: [901](https://jenkins.osquery.io/job/osqueryPullRequestOSX/901/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 9592d03657e1bcbd85112c55ce1c03a45410fce3 (Job results: [4760](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4760/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 9592d03657e1bcbd85112c55ce1c03a45410fce3 (Job results: [902](https://jenkins.osquery.io/job/osqueryPullRequestOSX/902/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 9592d03657e1bcbd85112c55ce1c03a45410fce3 (Job results: [4761](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4761/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 9592d03657e1bcbd85112c55ce1c03a45410fce3 (Job results: [1631](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1631/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 9592d03657e1bcbd85112c55ce1c03a45410fce3 (Job results: [1632](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1632/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:no_good: The commit 7f37ad0139193eab240f92cadc41380678c1010f (Job results: [1582](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1582/)) failed the code audit or documentation test.

**Pull request merged**
