### PR TITLE
[Fix #3861] build: adding checks to vswhere usage to find msbuild tools

### LINKED ISSUE #3861: Odd Powershell errors on Windows 2016: Cannot bind argument to parameter 'Path'
See: https://jenkins.osquery.io/job/osqueryPullRequestWindows/2938/TargetSystem=aws-windows-2016/console
```
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
[aws-windows-2016] $ cmd /c call C:\Users\ADMINI~1\AppData\Local\Temp\jenkins6085391648822373388.bat

C:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\aws-windows-2016>tools\make-win64-binaries.bat
Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\aws-windows-2016\tools\build.ps1:41 char:26
+   $vcvarsall = Join-Path $vsLoc 'VC'
+                          ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join 
   PathCommand
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\aws-windows-2016\tools\build.ps1:45 char:28
+     $vcvarsall = Join-Path $vcvarsall 'vcvarsall.bat'
+                            ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom 
   mand
 
'""' is not recognized as an internal or external command,
```

### PR DESCRIPTION
**Pull request by muffins**
This addresses #3861 by 1.) ensuring that we enumerate the `-legacy` versions of VS, which should ensure we correctly build for VS 2015, and 2.) we fail back to searching the environment for the VS 2015 directories where the `vcvarsall.bat` script is located in the fashion we were previously building.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 3c904da467470f61806d262b4c69ff405a795026 (Job results: [981](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/981/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 3c904da467470f61806d262b4c69ff405a795026 (Job results: [982](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/982/)) failed one or more tests (**FreeBSD**).

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 3c904da467470f61806d262b4c69ff405a795026 (Job results: [983](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/983/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 3c904da467470f61806d262b4c69ff405a795026 (Job results: [984](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/984/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
FreeBSD isn’t working right now

**Pull request merged**
