### PR TITLE
syncing sdk with codemod and targets

### PR DESCRIPTION
**Pull request by marpaia**
real jank

### CODE REVIEW

**Comment by theopolis** [comment]
but... does it blend?

**Comment by marpaia** [comment]
blending will be extensively tested today, on many speeds.

**Comment by marpaia** [comment]
todo still:

- fix the directory structure of the resulting tarball
- make sure generated code isn't getting added to sources list

**Comment by marpaia** [comment]
@osqueryer test this please

**Comment by theopolis** [comment]
@osqueryer test this please

**Pull request merged**
