### PR TITLE
Fixing python installation path in Chocolatey

### PR DESCRIPTION
**Pull request by PoppySeedPlehzr**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 13b256ccffaa853d034ec5aa8562848d2f7059c4 (Job results: [159](https://jenkins.osquery.io/job/osqueryPullRequestOSX/159/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 13b256ccffaa853d034ec5aa8562848d2f7059c4 (Job results: [875](https://jenkins.osquery.io/job/osqueryPullRequestWindows/875/)) failed one or more tests (**Windows**).

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by theopolis** [comment]
This has all of the things I love.

**Pull request merged**
