### PR TITLE
add fan name to fan speeds table

### PR DESCRIPTION
**Pull request by kaizensoze**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Looks good! @osqueryer, test this please

**Comment by osqueryer** [comment]
Build origin/pr/1891/merge (Job: 2425) failed :-1:

**Comment by theopolis** [comment]
Don't mind the test failure on OS X 10.11, the unit tests ran abnormally long and the HTTPS server it stands up to do some integration tests timed out (which is expected).

**Comment by kaizensoze** [comment]
okie dokie

**Pull request merged**
