### PR TITLE
freebsd: Update CMake for thrift 11 and boost 1.66

### PR DESCRIPTION
**Pull request by theopolis**
FreeBSD has thrift 11 and boost 1.66 so we can remove special handling (local include of beast).

### CODE REVIEW

**Comment by theopolis** [comment]
test freebsd please

**Comment by obelisk** [comment]
LGTM

**Comment by osqueryer** [comment]
:-1: The commit 055243434255ce1680d099dddcc794aa8046fbcf (Job results: [1089](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1089/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 055243434255ce1680d099dddcc794aa8046fbcf (Job results: [1090](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1090/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit c8396a87847447acac0e367252e151c858eaa346 (Job results: [1091](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1091/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit c8396a87847447acac0e367252e151c858eaa346 (Job results: [1092](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1092/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d446c64f25e04f440d659d4453cca1f2dfd82263 (Job results: [1093](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1093/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d446c64f25e04f440d659d4453cca1f2dfd82263 (Job results: [1094](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1094/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit f45483375c3f75d6d5add4bf04e5c47b301406b9 (Job results: [1111](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1111/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit f45483375c3f75d6d5add4bf04e5c47b301406b9 (Job results: [1112](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1112/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 2fa35c05c05437c04b5cdfc8bf0c86cbc721f136 (Job results: [6609](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6609/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2fa35c05c05437c04b5cdfc8bf0c86cbc721f136 (Job results: [6610](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6610/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2fa35c05c05437c04b5cdfc8bf0c86cbc721f136 (Job results: [1113](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1113/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d4a726d44a7c5e5e7806835f60d0da10d91f717d (Job results: [1115](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1115/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d4a726d44a7c5e5e7806835f60d0da10d91f717d (Job results: [1116](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1116/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit d4a726d44a7c5e5e7806835f60d0da10d91f717d (Job results: [1117](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1117/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d4a726d44a7c5e5e7806835f60d0da10d91f717d (Job results: [1118](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1118/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit d4a726d44a7c5e5e7806835f60d0da10d91f717d (Job results: [1119](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1119/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
