### PR TITLE
Simple osquery Logger

### PR DESCRIPTION
**Pull request by dguido**
We wrote a simple logger script to help with development of osqueryd. All it does is listen for messages from osqueryd and log them to the console so we can verify what gets sent.

I thought I'd send over a pull request since it seems relatively useful. Any comments on it? Happy to take feature requests.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Looks good! Thanks for this!

The only nitpick with the code is a few inconsistencies with formatting/pep8.

There are no tests or uses so it's likely this will experience some code-rot if/when config/logging/distributed queries APIs change. That's worrisome; it makes me hesitant to keep the code in the main repo as opposed to some external utility-like project.

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by dguido** [comment]
We moved this little debugger over to https://github.com/trailofbits/osquery-logger

**Pull request closed without merging**
