### PR TITLE
Bumping cpp-netlib and boost for Windows to match Posix

### PR DESCRIPTION
**Pull request by poppyseedplehzr**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 9c6be909772b966907c338bbf9b42b2d3a1795d0 (Job results: [4225](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4225/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 9c6be909772b966907c338bbf9b42b2d3a1795d0 (Job results: [1149](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1149/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 9c6be909772b966907c338bbf9b42b2d3a1795d0 (Job results: [1160](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1160/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 9c6be909772b966907c338bbf9b42b2d3a1795d0 (Job results: [449](https://jenkins.osquery.io/job/osqueryPullRequestOSX/449/)) failed one or more tests (**macOS/OS X**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Pull request merged**
