### PR TITLE
Removing powershell linter installation for build hosts

### PR DESCRIPTION
**Pull request by PoppySeedPlehzr**

### CODE REVIEW

**Comment by PoppySeedPlehzr** [comment]
The windows build hosts shouldn't require the powershell linter, as we're not currently making use of it in the build process.  We can consider bringing this back later if we want to lint on PR, but this is only really applicable for changes made to the `provision.ps1` script, and was only ever brought in for those hacking on powershell.

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
I would just land these provision changes once the Windows build host gets past the `dev-env` portion. The Windows build hosts will fail their unit tests until we find out why `unique_path` is failing.

**Comment by osqueryer** [comment]
:-1: The commit 2e6c97bf4e6fafac9c0a9f1a73da1f371e083b45 (Job results: [709](https://jenkins.osquery.io/job/osqueryPullRequestBuild/709/)) failed one or more tests (**Windows**).

**Pull request merged**
