### PR TITLE
Add constness for the methods of class `WmiRequest`

### PR DESCRIPTION
**Pull request by narendahr15**
_There is a class WmiRequest in osquery/core/windows/wmi.h. It perform a WMI requests and do it during the construction. And it has only two methods, both to read the result of the query (results, getStatus). So, there are no reasons to be non-const for them. Let's mark them as const. And fix all the places which use them as non-const._

Added const keyword to functions and all the places which use them as non-const.

Issue:  #4731

### CODE REVIEW

**Comment by fmanco** [comment]
ok to test

**Comment by guliashvili** [comment]
@narendahr15 make format_master can be used to fix the code audit.

**Comment by narendahr15** [comment]
@guliashvili Sure, I will do it and push the changes.

**Comment by fmanco** [comment]
Hey @narendahr15 I just push the code formatting changes so that we can merge the PR.

**Comment by fmanco** [comment]
@narendahr15 thanks for the contribution.

**Comment by narendahr15** [comment]
@fmanco Thanks for running **make format_master** and committing it.

**Pull request merged**
