### PR TITLE
Add removeService to Dispatcher API

### PR DESCRIPTION
**Pull request by theopolis**
With a `::removeService` method, combined with the abstracted thread start in the Dispatcher API, services auto-remove when finished.

This will un-break the kernel communication tests. These tests only stop when all their producer threads/services have ended.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/2116/merge (Job: 2695) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/2116/merge (Job: 2696) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2116/merge (Job: 2697) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2116/merge (Job: 2709) is good! :+1:

**Pull request merged**
