### PR TITLE
config: Only reconfigure if content changes

### PR DESCRIPTION
**Pull request by theopolis**
See https://community.uptycs.com/osquery-fim-reliability/ for more details on why this is an issue.

Overall it's silly to reconfigure (a somewhat intense process) osquery when the configuration has not changed.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 0bfdfe40edf876dfb6088f731746532d1b53e845 (Job results: [4913](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4913/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 0bfdfe40edf876dfb6088f731746532d1b53e845 (Job results: [1051](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1051/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 0bfdfe40edf876dfb6088f731746532d1b53e845 (Job results: [1052](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1052/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
cc: @lambda-conjecture

**Pull request merged**
