### PR TITLE
Braced initialization codemod

### PR DESCRIPTION
**Pull request by obelisk**
It seems that in newer C++, braced initialization is preferred. I whipped up a quick codemod to replace most instances of this across the codebase (especially std::string).

Also affected are: int, long, long long, const string, and char (though at this point I only want to enforce `(const)* std::string`).

The plan is to add this as another dependency of `make format` and `make format_master`.

Ideally `make format` will only look at files you've changed where as `make format_master` will look through the whole repo. As for speed, the script takes less than a second to run by only going through the osquery directory.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 3829499b1286782cd3f35473919cf7633749690d (Job results: [2733](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2733/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 3829499b1286782cd3f35473919cf7633749690d (Job results: [6666](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6666/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 3829499b1286782cd3f35473919cf7633749690d (Job results: [2734](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2734/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 3829499b1286782cd3f35473919cf7633749690d (Job results: [6667](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6667/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2718bf2c89576f8b913f854a48a111c6d79ffec7 (Job results: [6668](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6668/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2718bf2c89576f8b913f854a48a111c6d79ffec7 (Job results: [6669](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6669/)) failed one or more tests (**Linux**).

**Comment by obelisk** [comment]
CentOS 6 failed because the VM ran out of space.

**Comment by theopolis** [comment]
If you're making a style change codemod then it needs something to enforce it going forward. Either in clang format or some other static analysis check.

**Comment by osqueryer** [comment]
:-1: The commit 88792f432d633e927016763a4615df71f66d8c10 (Job results: [6671](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6671/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 202a9b438d8264e9be3e5b4ab20b95cce15f4790 (Job results: [6672](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6672/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 202a9b438d8264e9be3e5b4ab20b95cce15f4790 (Job results: [6673](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6673/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 4def858b5ea2c03211d4faa0e5e3fe103ca90478 (Job results: [6682](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6682/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 4def858b5ea2c03211d4faa0e5e3fe103ca90478 (Job results: [6683](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6683/)) failed one or more tests (**Linux**).

**Comment by obelisk** [comment]
The new script that checks for these changes in string in all the way at the bottom of the changes list so here is a direct link: https://github.com/obelisk/osquery/blob/d40f1361cfc4f0f1b4081c6aaf86b03363a89d98/tools/formatting/grep-format-checker.sh

**Comment by osqueryer** [comment]
:-1: The commit d40f1361cfc4f0f1b4081c6aaf86b03363a89d98 (Job results: [6684](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6684/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d40f1361cfc4f0f1b4081c6aaf86b03363a89d98 (Job results: [3573](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3573/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d40f1361cfc4f0f1b4081c6aaf86b03363a89d98 (Job results: [6685](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6685/)) failed one or more tests (**Linux**).

**Comment by obelisk** [comment]
ok to test

**Comment by mkareta** [comment]
I personally think that we should stick to google style guide here. https://google.github.io/styleguide/cppguide.html#Braced_Initializer_List
We can use it, but this should be never enforced becuase it may confusing in many places. 
Moreover migrating existing code base do to increase stability or fix something, but produce a lot of changes that can affect other PRs and code that still in development.

**Comment by theopolis** [comment]
Should we close this?

**Comment by fmanco** [comment]
I also think we shouldn't merge this. It's a lot of changes, has a lot of conflicts and would cause conflicts on other PRs, and I'm not totally convinced of the benefit. cc @obelisk

**Pull request closed without merging**
