### PR TITLE
SIP config: handle default case when IOKit key is not set

### PR DESCRIPTION
**Pull request by sharvilshah**
1. If `csr-active-config` IOKit key is not found (or cleared by `csrutil clear`), it is the default case (i.e SIP is enabled) and should not be considered an error.
2. `efi` -> `nvram` variable name update

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by sharvilshah** [comment]
Here's how the default config (i.e. SIP enabled and `csr-active-config` not set) looks:

```
osquery> .all sip_config;
+----------------------------+---------+---------------+
| config_flag                | enabled | enabled_nvram |
+----------------------------+---------+---------------+
| sip                        | 1       | 1             |
| allow_apple_internal       | 0       | 0             |
| allow_device_configuration | 0       | 0             |
| allow_kernel_debugger      | 0       | 0             |
| allow_task_for_pid         | 0       | 0             |
| allow_unrestricted_dtrace  | 0       | 0             |
| allow_unrestricted_fs      | 0       | 0             |
| allow_unrestricted_nvram   | 0       | 0             |
| allow_untrusted_kexts      | 0       | 0             |
+----------------------------+---------+---------------+
```

And with SIP disabled:

```
osquery> .all sip_config;
+----------------------------+---------+---------------+
| config_flag                | enabled | enabled_nvram |
+----------------------------+---------+---------------+
| sip                        | 0       | 0             |
| allow_apple_internal       | 0       | 1             |
| allow_device_configuration | 0       | 0             |
| allow_kernel_debugger      | 0       | 0             |
| allow_task_for_pid         | 1       | 1             |
| allow_unrestricted_dtrace  | 1       | 1             |
| allow_unrestricted_fs      | 1       | 1             |
| allow_unrestricted_nvram   | 1       | 1             |
| allow_untrusted_kexts      | 1       | 1             |
+----------------------------+---------+---------------+
```

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Pull request merged**
