### PR TITLE
Bundling example conf, packs, and certs.pem in choco package

### PR DESCRIPTION
**Pull request by PoppySeedPlehzr**
This addresses #2962

### CODE REVIEW

**Comment by theopolis** [comment]
What is the layout in the ZIP after the `7z a` call?

**Comment by PoppySeedPlehzr** [comment]
Running the command with a missing certs.pem
```
C:\Users\Nick\work\repos\osquery [win-conf-packs-deploy ≡]> .\tools\deployment\make_windows_package.ps1
...
[*] Did not find openssl certs.pem

WARNING: The system cannot find the file specified.
C:\ProgramData\chocolatey\lib\openssl\local\certs

[+] Chocolatey Package has been created. Run 'choco push' to push the package to Chocolatey
```
Directory structure of the zip itself
```
C:\Users\Nick\work\repos\osquery\build\chocolatey\tmp\tools\bin [win-conf-packs-deploy ≡]> ls


    Directory: C:\Users\Nick\work\repos\osquery\build\chocolatey\tmp\tools\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2/2/2017   5:25 PM                packs
-a----        1/24/2017  10:15 AM           3064 osquery.example.conf
------         2/3/2017   1:07 PM        6591881 osquery.zip
-a----         2/3/2017   1:00 PM        8173056 osqueryd.exe
-a----         2/3/2017   1:00 PM        8147968 osqueryi.exe
```
Directory of `C:\ProgramData\osquery\` after install from package
```
C:\Users\Nick\Desktop> l C:\ProgramData\osquery\


    Directory: C:\ProgramData\osquery


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2/3/2017   1:10 PM                osqueryd
d-----         2/2/2017   5:25 PM                packs
-a----        1/24/2017  10:15 AM           3064 osquery.example.conf
-a----         2/3/2017   1:00 PM        8147968 osqueryi.exe
```

**Comment by PoppySeedPlehzr** [comment]
View of the directory layout after a fresh install:
```
C:\Users\Nick\Desktop> l C:\ProgramData\osquery


    Directory: C:\ProgramData\osquery


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2/3/2017   1:20 PM                certs
d-----         2/3/2017   1:32 PM                osqueryd
d-----         2/2/2017   5:25 PM                packs
-a----        1/24/2017  10:15 AM           3064 osquery.example.conf
-a----         2/3/2017   1:00 PM        8147968 osqueryi.exe


C:\Users\Nick\Desktop> l C:\ProgramData\osquery\certs\


    Directory: C:\ProgramData\osquery\certs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         2/3/2017   1:20 PM         263596 cert.pem


C:\Users\Nick\Desktop> l C:\ProgramData\osquery\packs\


    Directory: C:\ProgramData\osquery\packs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/30/2016  10:30 AM           3914 hardware-monitoring.conf
-a----       11/30/2016  10:30 AM          13770 incident-response.conf
-a----        1/24/2017  10:15 AM           9054 it-compliance.conf
-a----       11/30/2016  10:30 AM           1045 osquery-monitoring.conf
-a----         2/2/2017   5:25 PM          18770 osx-attacks.conf
-a----        1/24/2017  10:15 AM           6531 vuln-management.conf
```

**Comment by PoppySeedPlehzr** [comment]
Screenshot of the contents of the zip file. This is what is shipped with the chocolatey package.

screen shot 2017-02-03 at 1 36 54 pm

**Comment by PoppySeedPlehzr** [comment]
I modified the `chocolateyInstall.ps` to create `C:\ProgramData\osquery\log`, as @Centurion89 mentioned we have issues starting the service "Out of the box" without that dir. Additionally I updated the `packs` folder to be called `packs-examples` so that we don't overwrite folks` packs if the already exist.

Alright, after a `choco upgrade osquery -s .` from `2.2.1`, our `C:\ProgramData\osquery` looks like:
```
C:\Users\Nick\Desktop\tmp\tools\bin> ls C:\ProgramData\osquery\


    Directory: C:\ProgramData\osquery


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2/3/2017   1:20 PM                certs
d-----         2/3/2017   2:03 PM                log
d-----         2/3/2017   2:03 PM                osquery.db
d-----         2/3/2017   2:04 PM                osqueryd
d-----         2/3/2017   1:59 PM                packs-examples
-a----       11/30/2016  10:30 AM           4743 manage-osqueryd.ps1
-a----        1/24/2017  10:15 AM           3064 osquery.conf
-a----        1/24/2017  10:15 AM           3064 osquery.example.conf
-a----         2/3/2017   2:02 PM              0 osquery.flags
-a----         2/3/2017   2:03 PM              4 osqueryd.pidfile
-a----         2/3/2017   1:52 PM        8147968 osqueryi.exe
```

The inards of the `osquery.zip` that's shipped with the chocolatey package looks as follows:

screen shot 2017-02-03 at 2 04 48 pm

**Comment by theopolis** [comment]
#shipit

**Comment by marpaia** [comment]
Shouldn't the path be "certs.pem", not "cert.pem"?

**Pull request merged**
