### PR TITLE
Update sleuthkit to v4.3.0 (#2545)

### LINKED ISSUE #2545: deps: Update sleuthkit to sleuthkit-4.3.0
We should update our local `sleuthkit` formula to version 4.3.0: https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.3.0

If everything goes according to plan this should be straight-forward:

1. Change the `url` here to point to the `4.3.0` URL: https://github.com/facebook/osquery/blob/master/tools/provision/formula/sleuthkit.rb#L6
2. Update the `sha256` value.

To test run:

1. `make deps`
2. `/usr/local/osquery/bin/brew uninstall sleuthkit`
3. `OSQUERY_BUILD_DEPS=1 make deps`

The last two tests are somewhat optional. They assure us that the package can be "bottled" for binary distribution.

### PR DESCRIPTION
**Pull request by danielbayerlein**
I've updated the dependency `sleuthkit` to v4.3.0 - fix #2545
Happy Hacktoberfest!

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit c6e14217cf5127dbb2dcca8acc6394b39d73791d (Job results: [3393](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3393/)) failed one or more tests (**OS X/Linux**).

**Comment by danielbayerlein** [comment]
@theopolis Unfortunately, the build "aws-centos7" was not successful. Any idea?

**Comment by theopolis** [comment]
Right, it's the same root cause as https://github.com/facebook/osquery/issues/2510 the `Data::Dumper` module is not included in CentOS7's default perl install. I've added this (`perl-Data-Dumper`) to the build host provision since it's rather 1-off. 

Reference: https://rt.cpan.org/Public/Bug/Display.html?id=97846

**Comment by theopolis** [comment]
Let's give it another try and see if my changes allow `sleuthkit` to build from source. @osqueryer please test this

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Working now: https://jenkins.osquery.io/job/osqueryPullRequestBuild/TargetSystem=aws-centos-7/3394/console I'll let the builds finish and on success will merge. Thanks @danielbayerlein!

**Comment by danielbayerlein** [comment]
@theopolis Thanks a lot! 👍

**Pull request merged**
