### PR TITLE
--autostart option for make_osx_package.sh

### PR DESCRIPTION
**Pull request by eastebry**
Super small fix. The plist file was getting put in /var/osquery, when it should be put in /Library/LaunchDaemons, so the daemon was not being started when the package was installed.

I assume this was not intentional, because the postinstall script still tries to load the plist from the LaunchDaemons folder. If we don't want to the daemon to autostart, we should remove the postinstall script.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by eastebry** [comment]
Ah, I see. The postinstall script only loads the plist if the daemon is currently running. https://github.com/facebook/osquery/blob/master/tools/deployment/make_osx_package.sh#L45. Perhaps, the load should be moved outside of that if statement.

Also, I now realize that you shouldn't rewrite a plist file, then try to unload it. If the label changes, launchctl won't stop the process. The proper workflow would be:
Check if osquery is running -> unload plist -> copy new plist -> load plist.

**Comment by eastebry** [comment]
Added an --autostart option to make_osx_package.sh. Tested in a vm, seems to work fine.

**Comment by theopolis** [comment]
Ping @marpaia, the thought was to install the "sample" launchd plist somewhere then bundle a osqueryctl script that would move it into the right location via symlink. That way you could install without running the daemon. But if you ever did "enable" the daemon then it would take care of the reload. :)

**Comment by theopolis** [comment]
Ok, looked through this again and it's great, we don't need to use osqueryctl if you know you want to build an auto-start package! ok to test

**Comment by marpaia** [comment]
My only "question" would be are we certain that default true is the preferred default behavior? 

Also, yeah, osqueryctl needs to get finished, I got sidetracked last week on the build tooling. I'll pick it back up today.

**Comment by eastebry** [comment]
If osqueryctl is going to take care of this stuff, feel free to close this PR. I like the idea of just building a package that runs the daemon without any user interaction.

The default behavior is not to a start the daemon. Passing the -a or --autostart flag to the packaging script changes that.

Currently, the postinstall script copies the plist file over. Would it be better to stop the daemon in the preinstall script, then symlink the plist and start the daemon in the postinstall script?

Also, any idea what's up with the build here? Looks like building some third-party stuff failed.

**Comment by marpaia** [comment]
i like this. i think there should be an "osqueryctl" for people that want to manage launchd via something like chef or puppet, but supporting an auto-starting package would be nice for folks that want that behavior for sure. let's change this to be turned off by default and merge it. cool, @eastebry?

**Comment by eastebry** [comment]
@marpaia yeah, sounds good. It is off by default right now:
https://github.com/facebook/osquery/pull/684/files#diff-0802f0d0ab0534c89cf7671433bfa13dR24

Do you want to do the copying thing, or symlink the plist?

**Comment by marpaia** [comment]
Ah, nice, my bad, you're right, it's off by default.

If autostart is set, I'd say maybe just copy the file to /Library/LaunchDaemons? @theopolis and I were chatting about this before. I've never seen a symlinked LaunchDaemon, so I'm not super sure if we should symlink? Thoughts?

**Comment by marpaia** [comment]
The homebrew instructions tell you to cp the file as well (as opposed to sym linking) so that kind of seems to be a pattern.

**Comment by eastebry** [comment]
Yeah, not really sure what the advantages of sym linking would be. This change copies them, so we could just stick with that.

**Comment by marpaia** [comment]
@eastebry did you update this commit? i didn't see any changes come through

**Comment by eastebry** [comment]
@marpaia: nope. Sorry, I meant the current change already copies the plist file instead of sym linking it. Should be good to merge. If you want, I can squash those commits.

**Comment by marpaia** [comment]
@eastebry yeah if you could squash and then rebase off master, that would be hella awesome!

**Pull request merged**
