### PR TITLE
Add action for snapshot query results

### PR DESCRIPTION
**Pull request by theopolis**
Cc: @friedbutter

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/2061/merge (Job: 2626) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/2061/merge (Job: 2628) failed :-1:

**Comment by theopolis** [comment]
First set of tests failed because I did not update the expected Logger test outputs for snapshot queries. These must be updated since the new expectation is to include `{"action": "snapshot"}` within each event.

The second set of tests will fail because Decorator query testing also depends on inline snapshot usage.

**Comment by osqueryer** [comment]
Build origin/pr/2061/merge (Job: 2629) is good! :+1:

**Pull request merged**
