### PR TITLE
add column info to CREATE VIRTUAL TABLE statement

### PR DESCRIPTION
**Pull request by schettino72**
## problem

Currently when using `osqueryi`, checking for the schema of a table using `.schema table-name` does not shows any column information.

## solution

I just added the columns information into CREATE VIRTUAL TABLE in similar way it is passed to CREATE TABLE in the `module-argument` (http://www.sqlite.org/lang_createvtab.html). This wont affect the code in xCreate and gives column info when inspecting a table using `.schema`.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the admins verify this patch? Reply with "ok to test" to kick off a build...

**Comment by schettino72** [comment]
ok to test

**Comment by marpaia** [comment]
ok to test

**Comment by marpaia** [comment]
This is next level awesome:

```
[marpaia-mbp] osquery (schema-columns) ./build/darwin/osquery/osqueryi
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
osquery - being built, with love, at Facebook
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
osquery> .schema launchd
CREATE VIRTUAL TABLE launchd USING launchd(path TEXT, name TEXT, label TEXT, run_at_load TEXT, keep_alive TEXT, on_demand TEXT, disabled TEXT, username TEXT, groupname TEXT, stdout_path TEXT, stderr_path TEXT, start_interval TEXT, program_arguments TEXT, program TEXT, watch_paths TEXT, queue_directories TEXT, inetd_compatibility TEXT, start_on_mount TEXT, root_directory TEXT, working_directory TEXT, process_type TEXT);
osquery> .schema etc_hosts
CREATE VIRTUAL TABLE etc_hosts USING etc_hosts(address TEXT, hostnames TEXT);
osquery> .schema processes
CREATE VIRTUAL TABLE processes USING processes(pid INTEGER, name TEXT, path TEXT, cmdline TEXT, uid BIGINT, gid BIGINT, euid BIGINT, egid BIGINT, on_disk TEXT, wired_size TEXT, resident_size TEXT, phys_footprint TEXT, user_time TEXT, system_time TEXT, start_time TEXT, parent INTEGER);
osquery>
```

**Comment by marpaia** [comment]
approved to merge as soon as the builds pass.

**Comment by marpaia** [comment]
Thanks so much for doing this @schettino72!

**Pull request merged**
