### PR TITLE
Pointing tables/schema documentation to new locations

### PR DESCRIPTION
**Pull request by javuto**
Documentation links have changed from `/docs/tables` to `/schema` and sometimes the old links were redirecting but not always. With this change now links will be pointing to the right location.

### CODE REVIEW

**Comment by javuto** [comment]
Warnings also show a link to old site and that one is broken, with this PR it will point to the right location, example:
```
osquery> select * from process_events;
W1023 14:18:22.989404 2525651776 virtual_table.cpp:542] Table process_events is event-based but events are disabled
W1023 14:18:22.989444 2525651776 virtual_table.cpp:549] Please see the table documentation: https://osquery.io/schema/#process_events
```

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 245f775b3e869ed301bd194fc951675c1b84b653 (Job results: [2722](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2722/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 245f775b3e869ed301bd194fc951675c1b84b653 (Job results: [6086](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6086/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 245f775b3e869ed301bd194fc951675c1b84b653 (Job results: [2965](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2965/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 245f775b3e869ed301bd194fc951675c1b84b653 (Job results: [6087](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6087/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 245f775b3e869ed301bd194fc951675c1b84b653 (Job results: [1020](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/1020/)) failed one or more tests (**FreeBSD**).

**Comment by muffins** [comment]
ok to test

**Pull request merged**
