### PR TITLE
logger: Require an open DB for status logs

### PR DESCRIPTION
**Pull request by theopolis**
The `relayStatusLogs` function will access the DB for certain options of `--host_identifier`. This method may be called (thus requiring DB access), before the DB is initialized. The method is called periodically during the daemon's life, returning before the DB is initialized will only delay forwarding status logs to the logger plugin.

### CODE REVIEW

**Comment by theopolis** [comment]
Thanks @yying for the test cases, shamelessly borrowed from https://github.com/yying/osquery/commit/0967e4f0de7016a49095249d9448e8f5d4d4c276

**Comment by osqueryer** [comment]
:-1: The commit e651eabcc47c9863550770210e3ade24ff984233 (Job results: [4547](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4547/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e651eabcc47c9863550770210e3ade24ff984233 (Job results: [721](https://jenkins.osquery.io/job/osqueryPullRequestOSX/721/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 32cd0b88989f78a25e5b2e32a991534cb93d7fed (Job results: [4548](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4548/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 32cd0b88989f78a25e5b2e32a991534cb93d7fed (Job results: [722](https://jenkins.osquery.io/job/osqueryPullRequestOSX/722/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 32cd0b88989f78a25e5b2e32a991534cb93d7fed (Job results: [1446](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1446/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 32cd0b88989f78a25e5b2e32a991534cb93d7fed (Job results: [4549](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4549/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 0dcb3967df405f68ec913eac574d0920b35aba8a (Job results: [4550](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4550/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 0dcb3967df405f68ec913eac574d0920b35aba8a (Job results: [723](https://jenkins.osquery.io/job/osqueryPullRequestOSX/723/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 181da726658f03b213960ba55622889d41d123d1 (Job results: [4551](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4551/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 181da726658f03b213960ba55622889d41d123d1 (Job results: [724](https://jenkins.osquery.io/job/osqueryPullRequestOSX/724/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 181da726658f03b213960ba55622889d41d123d1 (Job results: [4552](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4552/)) failed one or more tests (**Linux**).

**Comment by javuto** [comment]
Confirmed this fixes the issue in Xenial (Ubuntu 16.04 LTS). Thanks @theopolis!

**Comment by theopolis** [comment]
This should fix #3195, thanks @javuto for the review+test!

**Pull request merged**
