### PR TITLE
WIP: YARA Table

### PR DESCRIPTION
**Pull request by wxsBSD**
This implements a YARA table. Currently a WIP but it does allow you to express things like:

select * from yara where path="/bin/ls" and sigfile="/tmp/foo.sig";
select * from yara where path="/bin/ls" and sig_group="sig_group_1";

The latter will use the signature grouping from the config.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by wxsBSD** [comment]
This was thrown together somewhat quickly but I figured I could use some feedback. I still have to make it recognize relative paths for signature files and act accordingly, as discussed with @marpaia.

**Comment by marpaia** [comment]
ok to test

**Comment by wxsBSD** [comment]
It is probably worth calling out that I added a Config::getParser(), which will return the ConfigParserPlugin  requested. This is useful because I store the compiled rules as an attribute of that class instead of having to serialize them into the property tree.

**Comment by wxsBSD** [comment]
I've got nothing more to add for this PR. I think it is ready for review. Once accepted I'll write up some docs for it so others can understand how to use both YARA tables and what it means for the configuration file.

**Comment by theopolis** [comment]
ok to test

**Pull request closed without merging**
