### PR TITLE
Fix typo in build logging

### PR DESCRIPTION
**Pull request by zwass**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the admins verify this patch? Reply with "ok to test" to kick off a build...

**Comment by marpaia** [comment]
ok to test

**Comment by marpaia** [comment]
@javuto can you add @zwass to the list of admins so that he can build his PRs automatically?

**Comment by zwass** [comment]
I was able to add myself to the admins group (I think) through internal tools.

**Comment by marpaia** [comment]
@javuto: Ubuntu14 failed because it had network issues while apt-get updating or something: http://jenkins.osquery.io/job/osqueryPullRequestBuild/160/TargetSystem=Ubuntu14/console

Can you take a look at that?

@zwass when myself, @theopolis or @javuto submit a PR, there's a whitelist in jenkins that automatically builds the PR. If someone else submits a PR, one of use has to say "ok to test" in a comment. That whitelist is maintained via a different interface than the internal tool (although it would be AWESOME to integrate them together!)

**Comment by javuto** [comment]
test this please

**Comment by javuto** [comment]
I added @zwass as admin in Jenkins, so his pull requests will be automatically built from now on. Also he can approve other's people PRs and so on. I'll look into integrating the list of admins with the admins of the repository.

**Comment by theopolis** [comment]
Is it possible to have an OWNERS file in the repo that lists the github usernames? Would Jenkins be able to pull in the repo from master to check this file on each PR?

**Comment by javuto** [comment]
I will have to look at the plugin that does the integration, and how that is done but nothing is impossible! BTW the build is now green :)

**Comment by zwass** [comment]
Should there be an automated message on this PR that the build succeeded?

**Comment by marpaia** [comment]
The merge button turns green:

screen shot 2015-01-07 at 11 55 57 am

There's also now a green checkmark next to the commit in the commits tab:

screen shot 2015-01-07 at 11 56 49 am

**Comment by theopolis** [comment]
@zwass feel free to merge anything anytime. There's no formal code review or process enforcement, it's at your leisure but absolutely recommended.

**Pull request merged**
