### PR TITLE
Update dependency build flows on Linux and OS X

### PR DESCRIPTION
**Pull request by theopolis**
After a few months of introducing a new "type" of technical debt into the new `brew`-based dependency manager (`./tools/provision.sh`), it is time to pay up!

1. Change some of the `CMake` welcome messaging to point to Readthedocs, versus the old build problem statement Github issue.
2. Add a gut-check for new builders who eagerly run `make`. The check should ask them to run `make deps` first.
3. The provision removes a managed `bison` install. This is due to `bison` having been compiled with a static `m4` location. If we edit bison's data directory we may cause the application to fault. We now ask the system to provide a `bison` and `flex`.
4. The `zlib-legacy` package now includes a `.pc` file and local formulas will prefer the legacy-library directory for configurations.
5. The provision arguments now use the "fully qualified" brew package names. These include the organization, tap name, and formula name to differentiate from the upstream-managed formulas.

The most fragile change is a reordering of installs. While this works with bottle installs, it may not work for source builds.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 67d89de203fb6a154567638ec19db8cfadbe2943 (Job results: [3661](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3661/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit dd742f84e59dc7dc26c772b9e2e0020c84f92ba3 (Job results: [3671](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3671/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit a8bd8540c9643533d7b5f31a7164dec530c27dc5 (Job results: [654](https://jenkins.osquery.io/job/osqueryPullRequestAudit/654/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit a8bd8540c9643533d7b5f31a7164dec530c27dc5 (Job results: [3672](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3672/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit f22a56c0a0f057842d5aedfdebb4898b8480e3c9 (Job results: [655](https://jenkins.osquery.io/job/osqueryPullRequestAudit/655/)) failed the code audit.

**Comment by osqueryer** [comment]
:no_good: The commit 3d42f3243221898e1503379790681491caea9c0e (Job results: [657](https://jenkins.osquery.io/job/osqueryPullRequestAudit/657/)) failed the code audit.

**Comment by theopolis** [comment]
This has been quite a journey, which is not quite over.

A few more lessons learned:
1. `bison` (or a newer version) is still needed on OS X
2. `CPPFLAGS` were making it into the formulas, introducing variance.
3. The new `gcc` build (tested on CentOS 7 and Ubuntu 16) requires an explicit link to `rt pthread dl`. This is inserted into some formula's `LDFLAGS` others may use the `gcc` specs.
4. The set of `cmake` args now includes explicit paths to our "legacy" runtimes.
5. The `openssl` and `gcc` formulas have been minified.
6. The `libmagic` mirrors are all returning 404, bump the source version to `5.29`.
7. `zzuf`'s detection of `aio` headers and library functions is weird, this includes a fix to a patched version that more or less excludes `aio` from our testing.

**Pull request merged**
