### PR TITLE
Simplify string stream processing

### PR DESCRIPTION
**Pull request by guliashvili**
strlen and pos removed for minor performance optimization

### CODE REVIEW

**Comment by fmanco** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit ab87ad4d26c9f099b178edc7f2fd6fd7fa980efd (Job results: [3260](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3260/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit ab87ad4d26c9f099b178edc7f2fd6fd7fa980efd (Job results: [3261](https://jenkins.osquery.io/job/osqueryPullRequestOSX/3261/)) failed one or more tests (**macOS/OS X**).

**Comment by obelisk** [comment]
What is the performance gain of this?

**Comment by guliashvili** [comment]
Hi @obelisk,

It is not be anything dramatic of course. We are saving the time of the strlen and access to the characters would be a bit faster also. It's not just about the performance, it just looks better, when you are streaming/processing c string.

**Pull request closed without merging**
