### PR TITLE
Build on Debian 7 (Wheezy)

### LINKED ISSUE #1745: not able to finish make deps on wheezy( failed on rocksdb)
On Debian Wheezy, make deps failed here:

```
/tmp/osquery-provisioning/rocksdb-rocksdb-4.1 /tmp/osquery-provisioning
make[1]: Entering directory `/tmp/osquery-provisioning/rocksdb-rocksdb-4.1'
  GEN      util/build_version.cc
  CC       db/compaction_job.o
db/compaction_job.cc:369:18: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
          bounds.emplace(flevel->files[i].smallest_key);
          ~~~~~~ ^
db/compaction_job.cc:370:18: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
          bounds.emplace(flevel->files[i].largest_key);
          ~~~~~~ ^
db/compaction_job.cc:375:16: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
        bounds.emplace(flevel->files[0].smallest_key);
        ~~~~~~ ^
db/compaction_job.cc:376:16: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
        bounds.emplace(flevel->files[num_files - 1].largest_key);
        ~~~~~~ ^
db/compaction_job.cc:383:20: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
            bounds.emplace(flevel->files[i].smallest_key);
            ~~~~~~ ^
5 errors generated.
make[1]: *** [db/compaction_job.o] Error 1
make[1]: Leaving directory `/tmp/osquery-provisioning/rocksdb-rocksdb-4.1'
make: *** [deps] Error 2
```

something wrong with gcc version?

### PR DESCRIPTION
**Pull request by sharvilshah**
* Install GCC 4.8.4 from source, so that we have C++11 features and can build RocksDB.
* Update Vagrantfile debian boxes from Chef's Bento project, which are better maintained.

Fix #1745

@mathieuk Since you first added support for debian, this might be of interest to you too. Please let me know if you notice something broken.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by sharvilshah** [comment]
@theopolis I tested this on Debian 7 box, relying on Jenkins to make sure I didn't break others.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Comment by theopolis** [comment]
Build is OK, the 10.9 hosts need some love.

**Comment by mathieuk** [comment]
This seems to build just fine for me, @sharvilshah. I did have an issue with clang being selected as compiler, but that may have been because it wasn't a clean checkout.

**Comment by theopolis** [comment]
CMake will definitely cache the compiler it found the first time you ran make. If you want a clean build blow away the build directory.

**Comment by sharvilshah** [comment]
Thanks @mathieuk. Yeah, clearing out the build directory will do the trick.

**Comment by theopolis** [comment]
@mathieuk, there is no build for any Debians right now, but there really should. I believe the appropriate Ubuntu deb has the equivalent package name dependencies. So it should work on the respective Debian release.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) is good! :+1:

**Comment by theopolis** [comment]
@mathieuk, I take that back, the Ubuntu 14.04 deb does not work on Debian 8.

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) is good! :+1:

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) is good! :+1:

**Comment by mathieuk** [comment]
The error is due to osquery_tests dynamically linking the system libstdc++.so.6 (libstdc++.so.6.0.17) while it should be linking to the newly compiled libstdc++ that came with the gcc 4.8.4 install which is in /opt/osquery/gcc/lib64/libstdc++.so.6 ( /opt/osquery/gcc/lib64/libstdc++.so.6.0.19).

tools/lib.sh has install_gcc which links libstdc++.so.6.0.19 into /usr/lib64 while the linker looks in /usr/lib/x86_64-linux-gnu/. A simple but ugly fix would be to create a debian7 specific install_gcc that installs libstdc++ in /usr/lib/x86_64-linux-gnu/ instead.

**Comment by sharvilshah** [comment]
Yeah, you're right. `osqueryi` and `osqueryd` are statically linked with the newer `libstdc++` via `OSQUERY_REQUIRE_RUNTIMES` in cmake, but that does not translate over to the test executables.

I don't know enough cmake, but like you mentioned the simple/ugly fix works. Thoughts @theopolis?

**Comment by theopolis** [comment]
I'll update the test binaries to include the static linking in a bit, with another commit, as it'll take a few more CMake changes.

**Comment by sharvilshah** [comment]
Thanks for the help on this @mathieuk 

And @theopolis, thanks and didn't mean to punt it off to you.

**Comment by MarloweW** [comment]
@sharvilshah  great work, I am gonna give it a shot.

**Pull request merged**
