### PR TITLE
Bumping rocksdb to version 5.1.4

### PR DESCRIPTION
**Pull request by poppyseedplehzr**

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 484e2e6391aa5281bc0da921b9960fb738c2e90b (Job results: [1190](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1190/)) failed one or more tests (**Windows**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 484e2e6391aa5281bc0da921b9960fb738c2e90b (Job results: [1191](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1191/)) failed one or more tests (**Windows**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 484e2e6391aa5281bc0da921b9960fb738c2e90b (Job results: [1192](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1192/)) failed one or more tests (**Windows**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 484e2e6391aa5281bc0da921b9960fb738c2e90b (Job results: [1194](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1194/)) failed one or more tests (**Windows**).

**Comment by poppyseedplehzr** [comment]
ok to test

**Pull request merged**
