### PR TITLE
Add namespaces to processes table on linux

### PR DESCRIPTION
**Pull request by fmanco**

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit b9780069c52ffc34b645d08f0a5af438be0ebc6e (Job results: [3319](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3319/)) failed the code audit or documentation test.

**Comment by obelisk** [comment]
Do you know yet what the perf impact of this is?

**Comment by fmanco** [comment]
Working on it/

**Comment by fossam** [comment]
I checked out the master and applied this patch. Here's the output:
```
osqueryi --line  " select * from processes where pid = '985'; "
               pid = 985
              name = bash
              path = /usr/bin/bash
           cmdline = -bash
             state = S
               cwd = /root
              root = /
               uid = 0
               gid = 0
              euid = 0
              egid = 0
              suid = 0
              sgid = 0
           on_disk = 1
        wired_size = 0
     resident_size = 2064000
        total_size = 115376000
         user_time = 11
       system_time = 6
   disk_bytes_read = 46026752
disk_bytes_written = 727105536
        start_time = 380
            parent = 980
            pgroup = 985
           threads = 1
              nice = 0
  namespace_cgroup = 
     namespace_ipc = �
     namespace_mnt = 
     namespace_net = t
     namespace_pid = �
    namespace_user = �
     namespace_uts = �
# ls -al /proc/985/ns/
total 0
dr-x--x--x. 2 root root 0 Apr 22 23:10 .
dr-xr-xr-x. 9 root root 0 Apr 22 23:02 ..
lrwxrwxrwx. 1 root root 0 Apr 23 05:37 ipc -> ipc:[4026531839]
lrwxrwxrwx. 1 root root 0 Apr 23 05:37 mnt -> mnt:[4026531840]
lrwxrwxrwx. 1 root root 0 Apr 22 23:10 net -> net:[4026531956]
lrwxrwxrwx. 1 root root 0 Apr 23 05:37 pid -> pid:[4026531836]
lrwxrwxrwx. 1 root root 0 Apr 23 05:37 user -> user:[4026531837]
lrwxrwxrwx. 1 root root 0 Apr 23 05:37 uts -> uts:[4026531838]
```
The same problem on both Centos or Ubuntu.
I can't wait this one the land with the correct output.

**Comment by obelisk** [comment]
Please fill out the description before landing :)

**Comment by fmanco** [comment]
@fossam Thanks for the report.

Need to investigate but I assume the problem might be on the code that fetches the namespaces, given this patch doesn't do much. Will try to repro and fix.

**Comment by fmanco** [comment]
This doesn't seem to cause a lot of overhead:

```
[devvm520] ~ $ sudo time ./osqueryi 'select * from processes' > /dev/null
0.14user 0.03system 0:00.19elapsed 88%CPU (0avgtext+0avgdata 19528maxresident)k
0inputs+120outputs (0major+2088minor)pagefaults 0swaps
[devvm520] ~ $ sudo time ./ns-osqueryi 'select * from processes' > /dev/null
0.14user 0.04system 0:00.21elapsed 88%CPU (0avgtext+0avgdata 20404maxresident)k
0inputs+120outputs (0major+2279minor)pagefaults 0swaps
```

This is for a machine with around 500 running processes. This is a single result by I repeated multi times (very scientific 😄 ).

**Pull request merged**
