### PR TITLE
Add test for SchedulerRunner

### PR DESCRIPTION
**Pull request by theopolis**
Enhance the safety of the scheduler and config interaction. This test will run several queries with a second interval for a second, using the `SchedulerRunner` facility.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/1976/merge (Job: 2527) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1976/merge (Job: 2528) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/1976/merge (Job: 2549) is good! :+1:

**Pull request merged**
