### PR TITLE
Add computer_name to system_info

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by javuto** [comment]
ok to test

**Comment by osqueryer** [comment]
Build is good! :+1:

**Comment by osqueryer** [comment]
Build failed :-1:

**Comment by osqueryer** [comment]
Build failed :-1:

**Comment by osqueryer** [comment]
Build is good! :+1:

**Comment by osqueryer** [comment]
Build is good! :+1:

**Comment by javuto** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (b8124347c7da8fe9d0faeb924c4513d8fdbb6aed) is good! :+1:

**Pull request closed without merging**
