### PR TITLE
YARA

### PR DESCRIPTION
**Pull request by wxsBSD**
Implement support for YARA as discussed in #816.

This is currently only for OS X, but I will port to Linux as discussion on this continues.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by wxsBSD** [comment]
It's probably worth noting that this includes the changes from @jedi22's many_confg branch, because I wanted to see how that would affect this work. If desired I can figure out how to split his work from mine as I believe it won't have any effect on mine.

The table is currently only for OS X, but I will add Linux support later this week. The branch has been lightly tested, but I will put it through more rigorous tests and write some later this week. I'm mostly looking for feedback on the approach.

Here's an example config:

```
{
  "scheduledQueries": [
  ],
  "additional_monitoring" : {
    "file_paths": {
      "foo": [ "/Users/wxs/tmp/foo/%" ]
    },
    "yara": {
      "foo": [ "/Users/wxs/yarasigs/foo.sig", "/Users/wxs/yarasigs/bar.sig" ]
    }
  }
}
```

As discussed with @theopolis, the ```yara``` section contains keys which reference keys in the ```file_paths``` section. The yara table will iterate through each key in the ```yara``` section, find the files in the ```file_paths``` section and subscribe to each of them. It will then attempt to load/compile each rule for that key.

The code supports both compiled and source rules, though there is a slight complication when using compiled rules. The YARA interface for loading compiled rules can only load one file. This isn't a big deal because yarac(1), which generates the compiled rule files, can take in multiple source files and produce a single compiled rule file. This eliminates the need to load multiple compiled rules, just generate only one. The code does support multiple source files being loaded in together.

**Comment by marpaia** [comment]
those commit's from @jedi22 should already be in master. do you mind rebasing off master and squashing your commits down to one / get rid of mitchell's?

**Comment by jedi22** [comment]
@marpaia The many_confg diffs are not in master yet

**Comment by marpaia** [comment]
This looks awesome. I'm really stoked to get this into master. Nice work @wxsBSD. 

The yara API looks like it modifies it's own global state. @theopolis, can the same event subscriber be called for two events that get published in parallel? If so, we should probably wrap yara API usage in some sort of `osquery::Yara` class which has locks.

**Comment by marpaia** [comment]
@wxsBSD it looks like your code should work without that PR. is there something in there that you're relying on?

**Comment by wxsBSD** [comment]
@marpaia Nothing I'm relying on. I thought I would require that work so I merged it into my branch and then did my work. As it turns out I don't need those changes, but when I went to split my work from them my git-fu was not strong enough to do it before I fell asleep. I'll see if I can split my work away and commit it separately when I have time today (might have to wait until tonight).

I have noticed that occasionally the same event will fire twice. I chalked it up to something in fsevents misbehaving, but never did fully track it down. As for your comment about YARA modifying it's own global state, I'll investigate. I know the stand-alone YARA tool spins off multiple threads when it wants to run in parallel, but I'm not sure what it does with rules in that situation. If it is as simple as each thread getting it's own copy of the rules then I can likely do that for each event that fires. I'll investigate this a bit more today too.

**Comment by wxsBSD** [comment]
I've split my work into a separate branch (yara2) and have opened a PR for that. I'm going to close this one and discussion can continue on #842.

**Pull request closed without merging**
