### PR TITLE
build: Major change to building within shared folders

### PR DESCRIPTION
**Pull request by theopolis**
This will be a work-in-progress until it's tested on several platforms.

The goal is to implement #3414 and allow easy building within shared-folders like `vboxsf` and `nfs`.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 2d81a8840397828d8f3d96bf7d78546f49dba231 (Job results: [1220](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1220/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 2d81a8840397828d8f3d96bf7d78546f49dba231 (Job results: [1221](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1221/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 2d81a8840397828d8f3d96bf7d78546f49dba231 (Job results: [5100](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5100/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2d81a8840397828d8f3d96bf7d78546f49dba231 (Job results: [5101](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5101/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
Fixes: #3408.

**Pull request merged**
