### PR TITLE
Keep a local reference to the process name to avoid memory corruption

### PR DESCRIPTION
**Pull request by marc-lebourdais**

### CODE REVIEW

**Comment by theopolis** [comment]
Thanks @marc-lebourdais! I'm curious why our MSAN and LSAN do not find memory corruption here, and what logger plugin is abusing the non-local `const string&` provided during its `::init`?

**Comment by marc-lebourdais** [comment]
@theopolis we found this in particular using the syslog logger plugin. Calls to `openlog` assign the passed pointer to a static variable in `syslog.c`:
https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/syslog.cpp#L71
https://fossies.org/dox/glibc-2.24/misc_2syslog_8c_source.html#l00332
https://fossies.org/dox/glibc-2.24/misc_2syslog_8c_source.html#l00067

After a cursory look into how glog handles the passed c-string, it should also be affected by this bug. A few of the other logger plugins get passed the pointer as well, but I didn't check to see if they internally memcpy or just hang on to the raw pointer.

The memory corruption is unlikely to be found in simple unit tests that don't give the OS enough time to add garbage to that temporary address space, e.g.:
https://github.com/facebook/osquery/blob/master/osquery/logger/tests/logger_tests.cpp#L120-L127

The issue could also be fixed by reworking `PluginRequest` to be a `map<string, string*>` but that seemed like it could have further unintended consequences that I didn't feel like researching. I think this PR is fairly straightforward and will solve all those pesky `string::c_str()` calls.

**Comment by theopolis** [comment]
Perfect! As soon as the GitHub bot responds with the CLA accept we'll get merged!

**Comment by marc-lebourdais** [comment]
Perfect! I'm going to wait to go over the CLA until tomorrow with some people at the office to make sure it gets filled out correctly.

**Comment by marc-lebourdais** [comment]
Just a heads up @theopolis I signed the CLA using my company email so I'm not sure it'd get automatically matched up with my public GitHub account (and hence not automatically updating this PR via the bot). I sent out an email to cla@fb.com to see what the deal is, so hopefully that gets resolved soon :)

**Comment by fredemmott** [comment]
CLA processed, but @theopolis , please don't import this yet. Following up via email.

**Comment by marc-lebourdais** [comment]
I just re-signed the CLA as an individual contributor RE: email conversation with @fredemmott.

**Comment by fredemmott** [comment]
So, this is your own work, and not the property of your employer?

**Comment by marc-lebourdais** [comment]
Yes @fredemmott I was advised to sign under an individual contributor agreement, with ownership of the code not a property of my employer.

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
