### PR TITLE
[Fix #2592] deps: Use linenoise-ng for all platforms

### LINKED ISSUE #2592: backspace key not updating terminal output correctly
When entering osqueryi interactive mode on a CentOS 7 system the backspace key seems to update the internal buffers correctly but in the terminal the output is broken. When I enter "xxx" and then hit the backspace key three times the cursor will move to the right once with each key press instead of moving to the left and deleting one "x". Pressing backspace a fourth time will not move the cursor to the right anymore and hitting enter will just result in another prompt which leads me to believe that the internal buffers are updated correctly i.e. after hitting backspace three times the three x's are removed from the internal buffer and hitting enter has the same effect as hitting enter on an empty line.

This renders the interactive mode sort of unusable unless you never make a typo and combined with issue #2591 which i reported earlier renders the tool as a whole pretty much impossible to work with.

### PR DESCRIPTION
**Pull request by theopolis**
Replace `readline` on POSIX platforms with `linenoise-ng` (used on Windows).

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit a0e11b483900aac67e621198c5255438bf68aa2c (Job results: [3475](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3475/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 396c56d608dd839eb79f1990ce28c7a0d0e4875d (Job results: [3476](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3476/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2669b5b42b85cb1b9179051331af2566c01e9dac (Job results: [3485](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3485/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2669b5b42b85cb1b9179051331af2566c01e9dac (Job results: [489](https://jenkins.osquery.io/job/osqueryPullRequestBuild/489/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 76cb2f81f10dc4743485162b5b8d4418a3237492 (Job results: [3488](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3488/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 9c40a8863899bd7afd55e38cc15015ec69b950ea (Job results: [496](https://jenkins.osquery.io/job/osqueryPullRequestBuild/496/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
