### PR TITLE
removing the dependency on unwind

### PR DESCRIPTION
**Pull request by marpaia**
Moving glog to third-party so that we can custom compile it so that
we no longer have the dependency on libunwind. #578

### CODE REVIEW

**Comment by theopolis** [comment]
I think this is causing build breakage for other PRs: http://jenkins.osquery.io/job/osqueryPullRequestBuild/TargetSystem=OSX/lastBuild/console

@javuto can you take a look and see if we can clean up the build dirs.
@marpaia can we leave glog/gflags the way they are built in master and just remove the link to libunwind and replace it with an added C/CXX flag: `-fno-omit-frame-pointer

**Comment by marpaia** [comment]
Moving the UBN to #591

**Comment by marpaia** [comment]
Libs after this PR:

```
root@vagrant-ubuntu-trusty-64:/vagrant# ldd build/linux/osquery/osqueryd
	linux-vdso.so.1 =>  (0x00007fff587fe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7a4046a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7a40251000)
	libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f7a4000a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7a3fe06000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f7a3fbf6000)
	libapt-pkg.so.4.12 => /usr/lib/x86_64-linux-gnu/libapt-pkg.so.4.12 (0x00007f7a3f8aa000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f7a3f699000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7a3f395000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7a3f08e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7a3ee78000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7a3eab2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7a40695000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f7a3e888000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f7a3e685000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7a3e463000)
	libcgmanager.so.0 => /lib/x86_64-linux-gnu/libcgmanager.so.0 (0x00007f7a3e247000)
	libnih.so.1 => /lib/x86_64-linux-gnu/libnih.so.1 (0x00007f7a3e02f000)
	libnih-dbus.so.1 => /lib/x86_64-linux-gnu/libnih-dbus.so.1 (0x00007f7a3de25000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f7a3dbdf000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7a3d9d7000)
root@vagrant-ubuntu-trusty-64:/vagrant#
```

**Comment by marpaia** [comment]
Also, @theopolis, I wasn't able to get osquery to compile with the glog from apt without unwind.

**Comment by marpaia** [comment]
@osqueryer, test this please

**Comment by javuto** [comment]
test this please

**Comment by theopolis** [comment]
SF downloads look to be working again. Let's test this please (again).

**Comment by theopolis** [comment]
Interrupted tar download: 

```
Package python-pip-1.3.1-4.el6.noarch already installed and latest version
Nothing to do
[+] python-devel is already installed. skipping.
/etc/yum.repos.d ~/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/Centos6.6/.sources
[+] devtoolset-2-gcc is already installed. skipping.
[+] devtoolset-2-binutils is already installed. skipping.
[+] devtoolset-2-gcc-c++ is already installed. skipping.
~/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/Centos6.6/.sources
[+] cmake28 is already installed. skipping.
[+] clang is already installed. skipping.
[+] clang-devel is already installed. skipping.
[+] bzip2 is already installed. skipping.
[+] bzip2-devel is already installed. skipping.
[+] openssl-devel is already installed. skipping.
[+] readline-devel is already installed. skipping.
[+] procps-devel is already installed. skipping.
[+] rpm-devel is already installed. skipping.
[+] libblkid-devel is already installed. skipping.
[+] boost source is already downloaded. skipping.
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [deps] Error 2
Build step 'Execute shell' marked build as failure
Setting commit status on GitHub for https://github.com/facebook/osquery/commit/c68ac10022872185131b12b645e4a9597675b7e4
Finished: FAILURE
```

**Comment by javuto** [comment]
Although SF is back, some stuff is still not recovered yet, that is why the builds are failing:
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>

**Comment by theopolis** [comment]
Can I just keep asking to test this please? :jack_o_lantern: :wink:

**Comment by theopolis** [comment]
@marpaia I'm not sure where this regression came from but can you add `ADD_OSQUERY_CORE_LINK("rt")` for Linux builds somewhere in `osquery/CMakeLists.txt`?

```
Linking CXX executable osqueryd
/usr/local/lib/librocksdb.a(env_posix.o): In function `rocksdb::(anonymous namespace)::PosixEnv::NowNanos()':
/home/osquery/jenkins/workspace/osqueryPullRequestBuild/.sources/rocksdb-rocksdb-3.5/util/env_posix.cc:1362: undefined reference to `clock_gettime'
/usr/local/lib/libboost_thread.a(thread.o): In function `boost::this_thread::hiden::sleep_for(timespec const&)':
libs/thread/src/pthread/thread.cpp:(.text+0x1166): undefined reference to `clock_gettime'
/usr/local/lib/libboost_thread.a(thread.o): In function `boost::this_thread::hiden::sleep_until(timespec const&)':
libs/thread/src/pthread/thread.cpp:(.text+0x12c4): undefined reference to `clock_gettime'
libs/thread/src/pthread/thread.cpp:(.text+0x1362): undefined reference to `clock_gettime'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libudev.a(libudev-util.o): In function `now_usec':
(.text.now_usec+0xd): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[3]: *** [osquery/osqueryd] Error 1
make[2]: *** [osquery/CMakeFiles/daemon.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by javuto** [comment]
test this please

**Comment by theopolis** [comment]
Notes: when `make clean` on my ubuntu14:
```
cd build/ubuntu && cmake ../.. && make --no-print-directory clean
-- Building for Ubuntu
-- Found components for DL
-- Found readline library
CMake Error at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1426 (message):
  error: no download info for 'libglog' -- please specify existing/non-empty
  SOURCE_DIR or one of URL, CVS_REPOSITORY and CVS_MODULE, SVN_REPOSITORY,
  GIT_REPOSITORY, HG_REPOSITORY or DOWNLOAD_COMMAND
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1805 (_ep_add_download_command)
  CMake/FindGlog.cmake:7 (ExternalProject_Add)
  CMakeLists.txt:90 (find_package)
```

My solution (since I was checking out the branch with `git checkout no-more-unwind`) was to add --remote to the provision submodule update command.

**Comment by theopolis** [comment]
test this please

**Comment by theopolis** [comment]
test this please (again)

**Comment by theopolis** [comment]
test this please

**Comment by theopolis** [comment]
Continuing: https://github.com/facebook/osquery/pull/598

**Pull request closed without merging**
