### PR TITLE
database: Move r/w reset lock for extensions

### PR DESCRIPTION
**Pull request by theopolis**
The DB reset locking does not protect the database plugin from extensions requesting a reset.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 15b91b806712e83758c6e6f70d84009688af231d (Job results: [4570](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4570/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 5495a7c682a9733fecc4254d45fa208fe92e8271 (Job results: [4575](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4575/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
