### PR TITLE
General code cleanup for the config

### PR DESCRIPTION
**Pull request by theopolis**
This contains config testing and compiling improvements. The goal is to make implementation files that include `config.h` compile faster.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit d647f889e317c22caf21cee715c3dda1c9fc6a3f (Job results: [265](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/265/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:no_good: The commit d647f889e317c22caf21cee715c3dda1c9fc6a3f (Job results: [2003](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2003/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 72e3951e005a3d5704e509f4a2f38b2c067d40dd (Job results: [266](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/266/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 72e3951e005a3d5704e509f4a2f38b2c067d40dd (Job results: [267](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/267/)) failed one or more tests (**FreeBSD**).

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 72e3951e005a3d5704e509f4a2f38b2c067d40dd (Job results: [268](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/268/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 72e3951e005a3d5704e509f4a2f38b2c067d40dd (Job results: [269](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/269/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 72e3951e005a3d5704e509f4a2f38b2c067d40dd (Job results: [5265](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5265/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
I killed the `centos6` test for the Jenkins error.

**Pull request merged**
