### PR TITLE
adding genieo query

### PR DESCRIPTION
**Pull request by PickmanSec**
Added a new genieo query to the osx_attacks pack.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PickmanSec** [comment]
I think I got it right this time. I was trying to have these pull requests look good but that can be hard some times.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Pull request merged**
