### PR TITLE
Refactor dispatcher shutdown logic

### PR DESCRIPTION
**Pull request by theopolis**
This is a refactor of shutdown, dispatcher, and event factory concurrency logic. The results here are an attempt to minimize the number of critical sections identified by LLVM's thread sanitization.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Comment by theopolis** [comment]
I can't repro the hangs within unit tests on my local boxes. A lot of these changes are focused on preventing races so I am worried I've introduced a dead lock somewhere.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:

**Comment by theopolis** [comment]
I think I've tracked the deadlock down to Thrift versions prior to 0.9.3. Let's test again. @osqueryer, test this please

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) is good! :+1:

**Pull request merged**
