### PR TITLE
[Fix #2112] Remove forced benchmark skip

### LINKED ISSUE #2112: Google benchmark 1.0.0 needed
If you encounter the follow error:
```
[ 86%] Building CXX object osquery/CMakeFiles/osquery_benchmarks.dir/main/benchmarks.cpp.o
[ 86%] Linking CXX executable osquery_tables_tests
/Users/reed/git/github/osquery/osquery/main/benchmarks.cpp:17:34: error: cannot initialize a parameter of type 'const char **' with an lvalue of type 'char **'
  ::benchmark::Initialize(&argc, argv);
                                 ^~~~
/usr/local/include/benchmark/benchmark_api.h:155:41: note: passing argument to parameter 'argv' here
void Initialize(int* argc, const char** argv);
                                        ^
```

Please upgrade you google benchmark install.

### Linux
```bash
sudo rm /usr/local/lib/libbenchmark.a
sudo rm -rf /usr/local/include/benchmark
```

### OS X
```
$ brew remove --force google-benchmark
$ make deps
```

### PR DESCRIPTION
**Pull request by theopolis**
Google benchmark 1.0.0 is included with the 1.8.0 build redesign.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 3e0a062783a78a2723f8c5816933edeeb2a1997f (Job results: [3013](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3013/)) failed one or more tests.

**Comment by osqueryer** [comment]
:-1: The commit d0af76f32d1a79b61d5f545be07589cde013da59 (Job results: [3023](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3023/)) failed one or more tests.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit d0af76f32d1a79b61d5f545be07589cde013da59 (Job results: [3024](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3024/)) failed one or more tests.

**Comment by osqueryer** [comment]
:-1: The commit c12f573d6dc5288ee407a78cbd313ad774ee57ce (Job results: [3025](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3025/)) failed one or more tests.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:ok_hand: The commit c12f573d6dc5288ee407a78cbd313ad774ee57ce (Job results: [9](https://jenkins.osquery.io/job/osqueryPullRequestAudit/9/)) passed the code audit!

**Comment by osqueryer** [comment]
:+1: The commit c12f573d6dc5288ee407a78cbd313ad774ee57ce (Job results: [49](https://jenkins.osquery.io/job/osqueryPullRequestBuild/49/)) was built successfully (Windows)!

**Comment by osqueryer** [comment]
:+1: The commit c12f573d6dc5288ee407a78cbd313ad774ee57ce (Job results: [3026](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3026/)) was built successfully (OS X/Linux)!

**Pull request merged**
