### PR TITLE
[Fix #3760] Fixing ConstraintList::literal_matches function

### LINKED ISSUE #3760: path on darwin launchd table not acting as it should
using `like` on the `path` column doesn't appear to work (it's the primary key, if that's relevant).

```
osquery> select count(*) from launchd where name like 'com.apple.%';
+----------+
| count(*) |
+----------+
| 590      |
+----------+
```

so we have a few in there, but if we try using path instead of name:

```
osquery> select count(*) from launchd where path like "/System/%";
+----------+
| count(*) |
+----------+
| 0        |
+----------+
```

if we just do `select count(*) from launchd where path like "%";` we still get 0 results.

Tried this on 2.7.0 and 2.8.0, no difference.

There are a number of packs using this type of query too, which is concerning.

### PR DESCRIPTION
**Pull request by uptycs-nishant**
If a constraint operation is not implemented, "ConstraintList::literal_matches" should return true. 
So that front-hand can handle it correctly.

### CODE REVIEW

**Comment by muffins** [comment]
Would you mind updating your title to be a bit more descriptive about the change? We tend to use `[Fix #3760] Terse description of change` as a format.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit e0a03b3db0dbab0db97bb38890ad26ff4e0fb866 (Job results: [2638](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2638/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit e0a03b3db0dbab0db97bb38890ad26ff4e0fb866 (Job results: [5996](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5996/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit e0a03b3db0dbab0db97bb38890ad26ff4e0fb866 (Job results: [2873](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2873/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit e0a03b3db0dbab0db97bb38890ad26ff4e0fb866 (Job results: [907](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/907/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit e0a03b3db0dbab0db97bb38890ad26ff4e0fb866 (Job results: [2875](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2875/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
