### PR TITLE
Rename products.cpp to programs.cpp

### PR DESCRIPTION
**Pull request by mtmcgrew**
Missed this one.

Rename products.cpp to programs.cpp

### CODE REVIEW

**Comment by mtmcgrew** [comment]
y u no build windows, jenkins

**Comment by theopolis** [comment]
There was some inconsistency between job configuration/Github-Pull-Request-Builder and Jenkins' admin list. I add @mtmcgrew to all of the lists, hopefully that fixes the not-build-everything-automatically issue.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 313556c090b6a25e00fbf546d8ac2aa870f0d685 (Job results: [393](https://jenkins.osquery.io/job/osqueryPullRequestBuild/393/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
Looks like the `products.cpp` delete was picked up, but the move/rename to `programs.cpp` is not included in the PR.

The linking error in the Windows build:
```
osquery_additional.lib(additional_amalgamation.obj) : error LNK2001: unresolved external symbol "class std::vector<class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > >,class std::allocator<class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > > __cdecl osquery::tables::genPrograms(struct osquery::QueryContext &)" (?genPrograms@tables@osquery@@YA?AV?$vector@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@V?$allocator@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@@2@@std@@AEAUQueryContext@2@@Z) [C:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10\build\windows10\osquery\shell.vcxproj]
C:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10\build\windows10\osquery\Release\osqueryi.exe : fatal error LNK1120: 1 unresolved externals [C:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10\build\windows10\osquery\shell.vcxproj]
Done Building Project "C:\jenkins\workspace\osqueryPullRequestWindows\TargetSystem\win10\build\windows10\osquery\shell.vcxproj" (default targets) -- FAILED.
```

I related, it cannot find the `genPrograms` symbol.

**Comment by facebook-github-bot-5** [comment]
@mtmcgrew updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2541/files/313556c090b6a25e00fbf546d8ac2aa870f0d685..adf5440694443884f95537b1720c5f74acc4550f)

**Pull request merged**
