### PR TITLE
Add virtual table: Windows etc_protocols

### PR DESCRIPTION
**Pull request by ExtremeGTX**
It has the same implementation for POSIX, just changed the file path to %WINDIR%\System32\Drivers\etc\protocol

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PoppySeedPlehzr** [comment]
Ok to test

**Comment by PoppySeedPlehzr** [comment]
This closes #2566

**Pull request merged**
