### PR TITLE
[Fix #3051] Adding header include to fix __cpuidex fail

### LINKED ISSUE #3051: OSQuery failed to build on windows due to error C3861: '__cpuidex': identifier not found
We (the MSVC++ team) do a nightly build of the latest OSQuery sources as a compiler "Real World Code" test. We noticed error C3861 is reported after commit  x65899a "Bumping cpp-netlib and boost libs". This warning is reported form file cpuid.cpp like below:
 D:\OSQuery\src\osquery\tables\system\cpuid.cpp(59): error C3861: '__cpuidex': identifier not found

The definition of "__cpuidex" is in VC header file "intrin.h". Do you foget to include this header file? Could you please take a look at this? Thanks!

### PR DESCRIPTION
**Pull request by poppyseedplehzr**

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit ff3aa78fb7397dcfbae54833b400c7c3dd8f5360 (Job results: [1156](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1156/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit ff3aa78fb7397dcfbae54833b400c7c3dd8f5360 (Job results: [4234](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4234/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit ff3aa78fb7397dcfbae54833b400c7c3dd8f5360 (Job results: [1169](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1169/)) failed one or more tests (**Windows**).

**Comment by poppyseedplehzr** [comment]
Ok to test

**Pull request merged**
