### PR TITLE
Fix SDK Build

### PR DESCRIPTION
**Pull request by artemdinaburg**
Make the `make sdk` operation work again. The current CMake scripts do not check if just the SDK is being built, and error because the kernel is not build. The kernel is never built with the SDK, so the SDK will always fail to build. Fix by checking if `OSQUERY_BUILD_SDK_ONLY` is set before throwing an error.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
Instead can we move the include of the Packages CMake into the `SDK_ONLY` gate here: https://github.com/artemdinaburg/osquery/blob/298e5c46a4477bf15b507e5fddb27e291e9c10b5/CMakeLists.txt#L477

**Comment by artemdinaburg** [comment]
It did make more sense to add the guard at the root. I found then I also needed to add it around the checks for adding the `${crypto_library}` dependency. I figure those can be removed when #2252 is addressed.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit c7dc04b65df7dce0132b50719698998c6763636a (Job results: [2991](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2991/)) failed one or more tests.

**Comment by artemdinaburg** [comment]
Not my fault :). Looks like its hitting #2323 on Ubuntu 16.04:

```
Traceback (most recent call last):
  File "/usr/local/osquery/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Makefile:98: recipe for target 'deps' failed
make: *** [deps] Error 1```

**Pull request merged**
