### PR TITLE
Ordered query results

### PR DESCRIPTION
**Pull request by theopolis**
Towards ordered scheduled query results.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit dc042c0087be007f9480a943eacd2737007aee06 (Job results: [316](https://jenkins.osquery.io/job/osqueryPullRequestOSX/316/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit dc042c0087be007f9480a943eacd2737007aee06 (Job results: [4067](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4067/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit dc042c0087be007f9480a943eacd2737007aee06 (Job results: [1023](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1023/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit dc042c0087be007f9480a943eacd2737007aee06 (Job results: [4068](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4068/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit a0188d2ffd4f89e51b3eb6e964c99d1c6bace4aa (Job results: [317](https://jenkins.osquery.io/job/osqueryPullRequestOSX/317/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit a0188d2ffd4f89e51b3eb6e964c99d1c6bace4aa (Job results: [4069](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4069/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit a0188d2ffd4f89e51b3eb6e964c99d1c6bace4aa (Job results: [1024](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1024/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [318](https://jenkins.osquery.io/job/osqueryPullRequestOSX/318/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [1025](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1025/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [4071](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4071/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [4072](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4072/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [1335](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1335/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [635](https://jenkins.osquery.io/job/osqueryPullRequestOSX/635/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [4447](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4447/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [4448](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4448/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d43f377342e5ab05d13324554917974a5e7703fb (Job results: [1358](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1358/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 2b53cbd740e9724986111045f01e0b8e229da097 (Job results: [636](https://jenkins.osquery.io/job/osqueryPullRequestOSX/636/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 2b53cbd740e9724986111045f01e0b8e229da097 (Job results: [4449](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4449/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2b53cbd740e9724986111045f01e0b8e229da097 (Job results: [4450](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4450/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2b53cbd740e9724986111045f01e0b8e229da097 (Job results: [1359](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1359/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit affd61e3aa2fdabef83803e286b2935c0f77eca8 (Job results: [2513](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2513/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit affd61e3aa2fdabef83803e286b2935c0f77eca8 (Job results: [3021](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3021/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit affd61e3aa2fdabef83803e286b2935c0f77eca8 (Job results: [6435](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6435/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 9d6cec32f6de78f8e539705215837f94aeb7f3ab (Job results: [3313](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3313/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:no_good: The commit 9d6cec32f6de78f8e539705215837f94aeb7f3ab (Job results: [3022](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3022/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 9d6cec32f6de78f8e539705215837f94aeb7f3ab (Job results: [2515](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2515/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit 87d9063159062dfc5f9f1b4859bd8e7b84c7136b (Job results: [3023](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3023/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 87d9063159062dfc5f9f1b4859bd8e7b84c7136b (Job results: [3314](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3314/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 87d9063159062dfc5f9f1b4859bd8e7b84c7136b (Job results: [2516](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2516/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 87d9063159062dfc5f9f1b4859bd8e7b84c7136b (Job results: [6437](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6437/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 87d9063159062dfc5f9f1b4859bd8e7b84c7136b (Job results: [2518](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2518/)) failed one or more tests (**macOS/OS X**).

**Pull request merged**
