### PR TITLE
Add support for pre-uninstall scripts at package creation

### PR DESCRIPTION
**Pull request by defaultnamehere**
Similar to post-install scripts, these scripts will let use add `service
stop` and remove stuff from autostart before removing files.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
:no_good: The commit 90982867da1c590f3070199b5328d4ec0ecdb3ec (Job results: [389](https://jenkins.osquery.io/job/osqueryPullRequestAudit/389/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 90982867da1c590f3070199b5328d4ec0ecdb3ec (Job results: [3407](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3407/)) failed one or more tests (**OS X/Linux**).

**Pull request merged**
