### PR TITLE
TLS/HTTPS-based logger plugin

### PR DESCRIPTION
**Pull request by theopolis**
1. Convert our existing proposed HTTP logger plugin into a TLS logger plugin. 
2. Organize RHEL-based building better.
3. Fix a database-deleting error and add scanning to the database-plugin type API.

The TLS-based logger plugin loses a bit of the original rate limiting logic. It also embeds JSON within JSON when converting the buffered log data into a TLS request.

### CODE REVIEW

**Comment by theopolis** [comment]
This implements and continues https://github.com/facebook/osquery/pull/1019.

**Comment by theopolis** [comment]
ok to test

**Comment by marpaia** [comment]
nice! this is awesome.

**Comment by theopolis** [comment]
For posterity, the original outline exists here: #940

**Pull request merged**
