### PR TITLE
Fix for #628

### PR DESCRIPTION
**Pull request by marpaia**

### CODE REVIEW

**Comment by marpaia** [comment]
@osqueryer, test this please

**Comment by marpaia** [comment]
@javuto, are these failures to be expected?http://jenkins.osquery.io/job/osqueryPullRequestBuild/223/console

**Comment by marpaia** [comment]
verified with @javuto, this is failing because of jenkins maintenance

**Comment by javuto** [comment]
@osqueryer, ok to test

**Pull request merged**
