### PR TITLE
Bump sqlite to 3.11.0

### PR DESCRIPTION
**Pull request by theopolis**
1. Bump the third-party checkout to its current master, which includes SQLite3 version 3.11.0.
2. Begin to replace `additional=True` columns with `LIKE`-capable expansions now that the LIKE operator is available in `xBestIndex`.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2389) is good! :+1:

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2392) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2395) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2396) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2397) is good! :+1:

**Comment by theopolis** [comment]
**There are 2 API changes here!** Both of them relate to our previous hacked-up-use of a `pattern` column within the `file` and `yara` tables. This column was introduced because we could not extract expressions provided to the LIKE SQL function. With SQLite version 3.10 we can!

With this PR we remove this column and support it's functionality within `path` or `directory`. Examples include:
```sql
SELECT count(1) FROM file WHERE path LIKE '/etc%';
SELECT count(1) FROM file WHERE path LIKE '/etc/%';
SELECT count(1) FROM file WHERE path LIKE '/etc%%';
SELECT count(1) FROM file WHERE directory = '/home/';
SELECT count(1) FROM file WHERE directory LIKE '/home/%';
```

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2398) is good! :+1:

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2403) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/1858/merge (Job: 2404) is good! :+1:

**Pull request merged**
