### PR TITLE
Add build support for Scientific Linux

### PR DESCRIPTION
**Pull request by justintime32**
Scientific Linux is a derivative of RHEL, and is very similar to CentOS. I added the appropriate provision script, based on the CentOS provision script, to allow for building on Scientific Linux. The main difference between the two is that it uses SL's devtools repository instead of the CentOS one, primarily so that the package signature verification works properly.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2016/merge (Job: 2551) is good! :+1:

**Comment by theopolis** [comment]
Cool, thanks @justintime32, happy to include this, but remember we don't have CI host to test changes continue to work/build on SL6/7. ;)

**Pull request merged**
