### PR TITLE
deps: Build for thrift 0.11.0

### PR DESCRIPTION
**Pull request by theopolis**
This will need a Windows package built too since 0.11.0 is changing the pointer implementation.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 698186179d3ee9306a6748ca80e1ca5e2574183d (Job results: [2921](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2921/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 698186179d3ee9306a6748ca80e1ca5e2574183d (Job results: [6305](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6305/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 698186179d3ee9306a6748ca80e1ca5e2574183d (Job results: [6306](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6306/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 698186179d3ee9306a6748ca80e1ca5e2574183d (Job results: [2403](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2403/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d929ab5c55421ae96579fde3265c6bb411673e44 (Job results: [6307](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6307/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d929ab5c55421ae96579fde3265c6bb411673e44 (Job results: [6308](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6308/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [6309](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6309/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [6310](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6310/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [2406](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2406/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [2407](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2407/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [6311](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6311/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [2408](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2408/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [6312](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6312/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [3195](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3195/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [3196](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3196/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [2409](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2409/)) failed one or more tests (**macOS/OS X**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [3197](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3197/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [6313](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6313/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [3198](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3198/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [6314](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6314/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d74a6d166c4db1925a510ae9ea10885ca1c0db86 (Job results: [2410](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2410/)) failed one or more tests (**macOS/OS X**).

**Comment by muffins** [comment]
I'll start looking into building with 0.11.0.

**Comment by ilovezfs** [comment]
I'm seeing
```
[  7%] Built target osquery_applications_tables
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/build.make osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/depend
cd /tmp/osquery-20171221-83186-d9szbo && /usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/osquery-20171221-83186-d9szbo /tmp/osquery-20171221-83186-d9szbo/osquery/distributed /tmp/osquery-20171221-83186-d9szbo /tmp/osquery-20171221-83186-d9szbo/osquery/distributed /tmp/osquery-20171221-83186-d9szbo/osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/build.make osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/build
[  8%] Building CXX object osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/plugins/tls_distributed.cpp.o
cd /tmp/osquery-20171221-83186-d9szbo/osquery/distributed && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DBOOST_NETWORK_ENABLE_HTTPS -DDARWIN -DDARWIN_10_13 -DGTEST_USE_OWN_TR1_TUPLE=1 -DNDEBUG -DNOMINMAX -DOSQUERY_BUILD_DISTRO=10.13 -DOSQUERY_BUILD_PLATFORM=darwin -DOSQUERY_BUILD_SDK_VERSION=2.11.0 -DSTRIP_FLAG_HELP=1 -DTHRIFT_SQUELCH_CONSOLE_OUTPUT=1 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -isystem /tmp/osquery-20171221-83186-d9szbo/third-party/sysroots/darwin -isystem /usr/local/osquery/legacy/include -isystem /usr/local/osquery/include -I/usr/local/osquery/include/openssl -I/tmp/osquery-20171221-83186-d9szbo/third-party/beast -I/tmp/osquery-20171221-83186-d9szbo/third-party/sqlite3 -I/tmp/osquery-20171221-83186-d9szbo/include -I/tmp/osquery-20171221-83186-d9szbo -I/tmp/osquery-20171221-83186-d9szbo/generated/gen-cpp  -std=c++14 -stdlib=libc++ -DNDEBUG -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -I/private/tmp/osquery-20171221-83186-d9szbo/brew_vendor/aws-sdk-cpp/include -I/private/tmp/osquery-20171221-83186-d9szbo/brew_vendor/cpp-netlib/include -I/private/tmp/osquery-20171221-83186-d9szbo/brew_vendor/linenoise/include -Wl,-L/private/tmp/osquery-20171221-83186-d9szbo/brew_vendor/linenoise/lib   -mmacosx-version-min=10.13 -Qunused-arguments -Wstrict-aliasing -Wno-missing-field-initializers -Wno-unused-local-typedef -Wno-deprecated-register -Wno-unknown-warning-option -Wnon-virtual-dtor -Wchar-subscripts -Wpointer-arith -Woverloaded-virtual -Wformat -Wformat-security -Werror=format-security -Wabi-tag -fpermissive -fstack-protector-all -pipe -fdata-sections -ffunction-sections -Werror=shadow -fvisibility=hidden -fvisibility-inlines-hidden -Os -fPIE -fpie -fPIC -fpic -flto=thin -march=x86-64 -mno-avx -Wall -Wextra -pedantic -Wuseless-cast -Wno-c99-extensions -Wno-zero-length-array -Wno-unused-parameter -Wno-gnu-case-range -Weffc++ -Wshadow -o CMakeFiles/osquery_distributed_plugins.dir/plugins/tls_distributed.cpp.o -c /tmp/osquery-20171221-83186-d9szbo/osquery/distributed/plugins/tls_distributed.cpp
In file included from /tmp/osquery-20171221-83186-d9szbo/osquery/distributed/plugins/tls_distributed.cpp:13:
In file included from /tmp/osquery-20171221-83186-d9szbo/osquery/remote/transports/tls.h:15:
In file included from /tmp/osquery-20171221-83186-d9szbo/osquery/remote/http_client.h:16:
In file included from /tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core.hpp:15:
In file included from /tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core/async_result.hpp:14:
In file included from /tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core/type_traits.hpp:15:
/tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core/detail/type_traits.hpp:28:7: error: 
      definition of type 'io_service' conflicts with typedef of the same name
class io_service;
      ^
/usr/local/include/boost/asio/io_service.hpp:27:20: note: 'io_service' declared here
typedef io_context io_service;
                   ^
In file included from /tmp/osquery-20171221-83186-d9szbo/osquery/distributed/plugins/tls_distributed.cpp:13:
In file included from /tmp/osquery-20171221-83186-d9szbo/osquery/remote/transports/tls.h:15:
In file included from /tmp/osquery-20171221-83186-d9szbo/osquery/remote/http_client.h:16:
In file included from /tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core.hpp:15:
In file included from /tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core/async_result.hpp:14:
In file included from /tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core/type_traits.hpp:15:
/tmp/osquery-20171221-83186-d9szbo/third-party/beast/boost/beast/core/detail/type_traits.hpp:37:1: error: 
      too few template parameters in template redeclaration
template<class Buffer, class Buffers>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/detail/consuming_buffers.hpp:71:1: note: previous template declaration
      is here
template <typename Buffer, typename Buffers, typename Buffer_Iterator>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/plugins/tls_distributed.cpp.o] Error 1
make[1]: *** [osquery/distributed/CMakeFiles/osquery_distributed_plugins.dir/all] Error 2
make: *** [all] Error 2
bash-3.2$ 
```

**Comment by osqueryer** [comment]
:-1: The commit f92bb89ee12486007a4da3ec414d2d8ac3eb5b61 (Job results: [2411](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2411/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit f92bb89ee12486007a4da3ec414d2d8ac3eb5b61 (Job results: [6315](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6315/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit f92bb89ee12486007a4da3ec414d2d8ac3eb5b61 (Job results: [2412](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2412/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit f92bb89ee12486007a4da3ec414d2d8ac3eb5b61 (Job results: [6316](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6316/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
@ilovezfs we need a follow up commit to update Boost and our Beast. Our Beast API is behind what is included in Boost 1.66. I will cut a pre-release tag (2.11.1) for Homebrew when we have this sorted out for Windows and FreeBSD. Hopefully that will be sometime today.

**Comment by ilovezfs** [comment]
@theopolis Sounds good to me! Thanks :)

**Comment by osqueryer** [comment]
:-1: The commit 9fc0d6d4466ed00330382efa21bb0e98aa69d3cf (Job results: [2414](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2414/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 9fc0d6d4466ed00330382efa21bb0e98aa69d3cf (Job results: [6318](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6318/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 9fc0d6d4466ed00330382efa21bb0e98aa69d3cf (Job results: [2415](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2415/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 9fc0d6d4466ed00330382efa21bb0e98aa69d3cf (Job results: [6319](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6319/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 6f470245c7ad6cf3577a29e61b4c4218fb167c65 (Job results: [2417](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2417/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 6f470245c7ad6cf3577a29e61b4c4218fb167c65 (Job results: [2418](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2418/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 6f470245c7ad6cf3577a29e61b4c4218fb167c65 (Job results: [6322](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6322/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 6f470245c7ad6cf3577a29e61b4c4218fb167c65 (Job results: [6323](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6323/)) failed one or more tests (**Linux**).

**Pull request merged**
