### PR TITLE
Fix Ubuntu os_version regex

### PR DESCRIPTION
**Pull request by theopolis**
@marpaia I think this should do it. The "LTS" string wasn't set in the version I tested with. :(

### CODE REVIEW

**Comment by marpaia** [comment]
Boss.

```
+-------------+-------+-------+-------+-------+
| name        | major | minor | patch | build |
+-------------+-------+-------+-------+-------+
| Trusty Tahr | 14    | 4     | 2     |       |
+-------------+-------+-------+-------+-------+
```

**Comment by marpaia** [comment]
@osqueryer, test this, please

**Comment by marpaia** [comment]
So I think that there might be a race condition in http tests where the http server isn't being started fast enough before the tests send a request. I could add a 100ms sleep between launching the thread and running the tests, but adding a sleep to tests sounds like something I wouldn't be proud of. FWIW, I've only ever seen this happen on CentOS 6.

**Comment by theopolis** [comment]
I've seen that a few times before as well. Not sure if we can add CLI/flags to the git commands to avoid HTTP request hangs?

**Pull request merged**
