### PR TITLE
Reorganize file_events into process_file_events

### PR DESCRIPTION
**Pull request by theopolis**
This extends the config to add `file_accesses`. Adding a list of `file_paths` categories will enable access monitoring for those directories on Linux.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Pull request merged**
