### PR TITLE
Add extensions SDK incompatibility checking

### PR DESCRIPTION
**Pull request by theopolis**
This is not an API change, but does begin to enforce API change incompatibility checks for extensions. The first may be 1.8.2 and 1.8.2+ unless we revert a number container size for `RouteUUID`.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit e08d4e3f8a61b698d41b0324ae5a30a723e536e5 (Job results: [350](https://jenkins.osquery.io/job/osqueryPullRequestAudit/350/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit e08d4e3f8a61b698d41b0324ae5a30a723e536e5 (Job results: [3367](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3367/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-7** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2527/files/e08d4e3f8a61b698d41b0324ae5a30a723e536e5..7e5b2e29e4773d77f2adb76e3a76daf6a0f8b642)

**Comment by osqueryer** [comment]
:-1: The commit 7e5b2e29e4773d77f2adb76e3a76daf6a0f8b642 (Job results: [3368](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3368/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-1** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2527/files/7e5b2e29e4773d77f2adb76e3a76daf6a0f8b642..4752f418a1755ca4ce112bcc04551bd5bf2dcefc)

**Comment by osqueryer** [comment]
:-1: The commit 4752f418a1755ca4ce112bcc04551bd5bf2dcefc (Job results: [3370](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3370/)) failed one or more tests (**OS X/Linux**).

**Comment by facebook-github-bot-6** [comment]
@theopolis updated the pull request - [view changes](https://github.com/facebook/osquery/pull/2527/files/4752f418a1755ca4ce112bcc04551bd5bf2dcefc..bcdfe9e8b566237191d16a15a582a296c570f2bf)

**Pull request merged**
