### PR TITLE
Bro integration 2.10.0

### PR DESCRIPTION
**Pull request by iBigQ**
Make the bro integration branch to be based on the latest stable osquery version (2.10.0)

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 5c39afb7abb651178a374c0938a747a4acdf5e55 (Job results: [2831](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2831/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 5c39afb7abb651178a374c0938a747a4acdf5e55 (Job results: [2305](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2305/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 5c39afb7abb651178a374c0938a747a4acdf5e55 (Job results: [2306](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2306/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 5c39afb7abb651178a374c0938a747a4acdf5e55 (Job results: [6204](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6204/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5c39afb7abb651178a374c0938a747a4acdf5e55 (Job results: [6205](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6205/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 5c39afb7abb651178a374c0938a747a4acdf5e55 (Job results: [3086](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3086/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 5c39afb7abb651178a374c0938a747a4acdf5e55 (Job results: [3087](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3087/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:no_good: The commit ae7801cdbc54008772a15ae572af0d6c645cdd8b (Job results: [3046](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3046/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit ae7801cdbc54008772a15ae572af0d6c645cdd8b (Job results: [2539](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2539/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit ae7801cdbc54008772a15ae572af0d6c645cdd8b (Job results: [2540](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2540/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit ae7801cdbc54008772a15ae572af0d6c645cdd8b (Job results: [6460](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6460/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit ae7801cdbc54008772a15ae572af0d6c645cdd8b (Job results: [6461](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6461/)) failed one or more tests (**Linux**).

**Comment by iBigQ** [comment]
Replaced by more recent update #4093

**Pull request closed without merging**
