### PR TITLE
Change second FLAGS_pofile_delay to seconds

### PR DESCRIPTION
**Pull request by fuzzball5000**
https://github.com/facebook/osquery/issues/2351

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 1dc5c7c0ed49ef690517c7f6cfcff1c152b640cc (Job results: [34](https://jenkins.osquery.io/job/osqueryPullRequestAudit/34/)) failed the code audit.

**Comment by theopolis** [comment]
I think this is good, should solve the negative time regression. :)

**Pull request merged**
