### PR TITLE
[#1548] Build and provision edits for FreeBSD CI

### PR DESCRIPTION
**Pull request by theopolis**

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (87d0216296d356d30dbf135ffb0be068069a841a) is good! :+1:

**Comment by osqueryer** [comment]
Build (87d0216296d356d30dbf135ffb0be068069a841a) failed :-1:

**Comment by osqueryer** [comment]
Build (87d0216296d356d30dbf135ffb0be068069a841a) failed :-1:

**Comment by osqueryer** [comment]
Build (87d0216296d356d30dbf135ffb0be068069a841a) failed :-1:

**Comment by osqueryer** [comment]
Build (87d0216296d356d30dbf135ffb0be068069a841a) failed :-1:

**Pull request merged**
