### PR TITLE
add osquery.man to wix config for New-MsiPackage - #5067

### PR DESCRIPTION
**Pull request by juju4**
This is a very quick attempt to address https://github.com/facebook/osquery/issues/5067
testing needed

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by juju4** [comment]
seems fine but does build include package generation? list of included files?
I checked https://jenkins.osquery.io/job/osqueryPullRequestWindows/5508/console and don't see anything be it for build or for packaging

**Comment by muffins** [comment]
@juju4 no, the tests are just required for a land, but we don't have any CI tests that will build the package. I'll pull down your fork to verify that it's adding in the manifest correctly and then we'll land.

**Comment by muffins** [comment]
```
C:\Users\thor\work\repos\osquery [(349d824...)]
λ  .\tools\deployment\make_windows_package.ps1 'msi'
[*] Building osquery MSI
[+] MSI Package written to C:\Users\thor\work\repos\osquery\build\msi\osquery.3.3.0.msi
C:\Users\thor\work\repos\osquery [(349d824...)]
λ  cp C:\Users\thor\work\repos\osquery\build\msi\osquery.3.3.0.msi C:\Users\thor\Desktop\
C:\Users\thor\work\repos\osquery [(349d824...)]
λ  ls C:\ProgramData\osquery\


    Directory: C:\ProgramData\osquery


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/5/2018   1:39 PM                certs
d-----         9/5/2018   1:39 PM                log
d-----         9/5/2018   1:40 PM                osquery.db
d-----         9/5/2018   1:39 PM                osqueryd
d-----         9/5/2018   1:39 PM                packs
-a----       12/22/2017   9:20 AM           6473 manage-osqueryd.ps1
-a----         5/7/2018  10:36 AM           6337 osquery.conf
-a----         9/5/2018   1:39 PM              0 osquery.flags
-a----       12/18/2017  12:29 PM           4319 osquery.man
-a----         9/5/2018   1:39 PM              5 osqueryd.pidfile
-a----         9/5/2018  12:27 PM       11501056 osqueryi.exe
-a----        7/26/2018   8:38 AM          10166 osquery_utils.ps1
```

**Comment by juju4** [comment]
Thanks a lot @muffins !

**Pull request merged**
