### PR TITLE
Avoid unnecessary ptree allocation.

### PR DESCRIPTION
**Pull request by spasam**
Use get_child_optional instead of get_child.

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 977f0556ba68249fcd90f5de03a7b41b5cf69fb6 (Job results: [788](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/788/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 977f0556ba68249fcd90f5de03a7b41b5cf69fb6 (Job results: [2749](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2749/)) failed one or more tests (**Windows**).

**Comment by spasam** [comment]
@theopolis Can't one of the bots do "ok to test" if the user previously contributed code? Seems like that will save you some time!

**Comment by theopolis** [comment]
@spasam unfortunately nope, it's a policy decision to require manual inspection for non-Facebook organization members on every PR. I know that future updates / edits reduce the usefulness of the policy but it's a happy medium.

**Pull request merged**
