### PR TITLE
tables: Add flags to interface_details

### PR DESCRIPTION
**Pull request by theopolis**
This includes a small refactor to the Windows implementation. I think the WMI calls can be reduced with: https://msdn.microsoft.com/en-us/library/aa394218(v=vs.85).aspx to get both the adapter information and configuration.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 393cebf262c31d7632b2dab70d54201fa15b8369 (Job results: [2070](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2070/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 393cebf262c31d7632b2dab70d54201fa15b8369 (Job results: [2071](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2071/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 2d81a9e4a5a98b7f283c958a3957388714819fcc (Job results: [2072](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2072/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 2d81a9e4a5a98b7f283c958a3957388714819fcc (Job results: [5174](https://jenkins.osquery.io/job/osqueryPullRequestLinux/5174/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 2d81a9e4a5a98b7f283c958a3957388714819fcc (Job results: [1292](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1292/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit d4fc26a2cda8d0c7563a6731a15973ae821b2c68 (Job results: [2075](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2075/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d4fc26a2cda8d0c7563a6731a15973ae821b2c68 (Job results: [186](https://jenkins.osquery.io/job/osqueryPullRequestLinux/186/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit d4fc26a2cda8d0c7563a6731a15973ae821b2c68 (Job results: [2076](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2076/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d4fc26a2cda8d0c7563a6731a15973ae821b2c68 (Job results: [187](https://jenkins.osquery.io/job/osqueryPullRequestLinux/187/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 051c908d16b19903d1a793ffe721d40236f1d6c4 (Job results: [188](https://jenkins.osquery.io/job/osqueryPullRequestLinux/188/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 051c908d16b19903d1a793ffe721d40236f1d6c4 (Job results: [189](https://jenkins.osquery.io/job/osqueryPullRequestLinux/189/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Closes #3411.

**Pull request merged**
