### PR TITLE
validate rows assert debugging

### PR DESCRIPTION
**Pull request by guliashvili**
validate_rows does not disclose what is wrong with the query data. pushing assert inside the validate_row so that we will be notified whats wrong

### CODE REVIEW

**Comment by guliashvili** [comment]
jenkins test macos

**Comment by fmanco** [comment]
jenkins test darwin

**Comment by fmanco** [comment]
jenkins test macos

**Comment by fmanco** [comment]
Lets go with this and we'll fix merge conflicts on inflight PRs.

**Comment by guliashvili** [comment]
jenkins test macos

**Comment by guliashvili** [comment]
jenkins test macos

**Comment by guliashvili** [comment]
jenkins test windows

**Pull request merged**
