### PR TITLE
corrected size in block_devices on darwin, linux (#3538)

### PR DESCRIPTION
**Pull request by vishwa35**
This should fix the issues from #3538. Am open to modifying this to display size in bytes, but left it in block units to preserve current Linux implementation.

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 7078819e1de37cebb2e9f99f0a0d76f4f014f005 (Job results: [2184](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2184/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit 5b3c0b0373ac23ddc1364459c0867bbea4e0bba5 (Job results: [2185](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2185/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
LGTM! Thanks!

**Pull request merged**
