### PR TITLE
Update yara to version 3.5.0 (#2546)

### PR DESCRIPTION
**Pull request by lnsp**
I had to add new pull patch because they the yara guys introduced another redeclaration bug. I have already filed a PR for this but until the next release comes out, I will have to leave it there. This PR addresses issue #2546.

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by theopolis** [comment]
Awesome, thanks for finding that updated PR. I can get this tested then merged ASAP, we're just waiting on your CLA acceptance. 👍

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Closes #2546.

Thanks @lnsp!

**Pull request merged**
