### PR TITLE
website: Add initial osquery.io redesign

### PR DESCRIPTION
**Pull request by theopolis**
This is a Jekyll-based homepage using the default Jekyll theme. The downloads and schema pages are ported from the existing https://osquery.io site. The packs browsing and community queries (these were old) have not been porting.

This will take some time to bring from "template" to running as a replacement website. I've added a TODO to the `/docs` readme to track the high-pri needs.

You can browse the render here: http://theopolis.github.io/osquery/

Once this is landed we can enable GitHub Pages builds and then eventually point our TLS proxy for osquery.io to that URL.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit dae41976cf1bbf06a7dac7cd7315fc3a65ff4297 (Job results: [1942](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1942/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit dae41976cf1bbf06a7dac7cd7315fc3a65ff4297 (Job results: [2486](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2486/)) failed the code audit or documentation test.

**Comment by theopolis** [comment]
LOL `Code Audit` job, no

**Comment by osqueryer** [comment]
:no_good: The commit 8b102f35d6de5f3294cab3ed0e8cf222d165af15 (Job results: [2493](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2493/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit 87c03c09e86858be023dfffdbfb010f4f6a72dc3 (Job results: [2494](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2494/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 87c03c09e86858be023dfffdbfb010f4f6a72dc3 (Job results: [764](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/764/)) failed one or more tests (**FreeBSD**).

**Comment by osqueryer** [comment]
:-1: The commit 87c03c09e86858be023dfffdbfb010f4f6a72dc3 (Job results: [1951](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1951/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 87c03c09e86858be023dfffdbfb010f4f6a72dc3 (Job results: [1952](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1952/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 87c03c09e86858be023dfffdbfb010f4f6a72dc3 (Job results: [765](https://jenkins.osquery.io/job/osqueryPullRequestFreeBSD/765/)) failed one or more tests (**FreeBSD**).

**Comment by theopolis** [comment]
Ok you can now view this from https://beta.osquery.io

**Comment by osqueryer** [comment]
:-1: The commit 87c03c09e86858be023dfffdbfb010f4f6a72dc3 (Job results: [2721](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2721/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 87c03c09e86858be023dfffdbfb010f4f6a72dc3 (Job results: [2723](https://jenkins.osquery.io/job/osqueryPullRequestWindows/2723/)) failed one or more tests (**Windows**).

**Pull request merged**
