### PR TITLE
deps: Update thrift to 0.10.0

### PR DESCRIPTION
**Pull request by theopolis**
Thrift 0.10.0 includes a fix for a memory leak in `gethostbyaddr`.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit c7c6f61de56deb8e6f543ef51ef12d8428cdfbcb (Job results: [4368](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4368/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit c7c6f61de56deb8e6f543ef51ef12d8428cdfbcb (Job results: [571](https://jenkins.osquery.io/job/osqueryPullRequestOSX/571/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit c7c6f61de56deb8e6f543ef51ef12d8428cdfbcb (Job results: [4369](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4369/)) failed one or more tests (**Linux**).

**Comment by theopolis** [comment]
For OS X:
```
[FAILURE:generation:1] Error: unknown option cpp:dense

make[3]: *** [generated/gen-cpp/Extension.cpp] Error 1
make[2]: *** [osquery/extensions/CMakeFiles/osquery_extensions.dir/all] Error 2
```

For Linux:
```
==> Downloading http://www-us.apache.org/dist/thrift/0.10.0/thrift-0.10.0.tar.gz
Already downloaded: /usr/local/osquery/.cache/thrift-0.10.0.tar.gz
==> Patching
patching file lib/cpp/src/thrift/transport/TServerSocket.cpp
Hello from osquery setup: thrift
==> ./configure --prefix=/usr/local/osquery/Cellar/thrift/0.10.0 --libdir=/usr/local/osquery/Cellar/thrift/0.10.0/lib --without-ruby --disable-tests --without-php_extension --without-haskell --without-java --without-perl --without-php --without-erlang --without-go --without-qt --without-qt4 --without-nodejs --without-python --with-cpp --with-openssl=/usr/local/osquery
Last 15 lines from /home/centos/.cache/Homebrew/Logs/thrift/01.configure:
checking for ld used by /usr/local/osquery/bin/clang++ -std=c++11... /usr/local/osquery/bin/ld -m elf_x86_64
checking if the linker (/usr/local/osquery/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the /usr/local/osquery/bin/clang++ -std=c++11 linker (/usr/local/osquery/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for /usr/local/osquery/bin/clang++ -std=c++11 option to produce PIC... -fPIC -DPIC
checking if /usr/local/osquery/bin/clang++ -std=c++11 PIC flag -fPIC -DPIC works... yes
checking if /usr/local/osquery/bin/clang++ -std=c++11 static flag -static works... yes
checking if /usr/local/osquery/bin/clang++ -std=c++11 supports -c -o file.o... yes
checking if /usr/local/osquery/bin/clang++ -std=c++11 supports -c -o file.o... (cached) yes
checking whether the /usr/local/osquery/bin/clang++ -std=c++11 linker (/usr/local/osquery/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether make sets $(MAKE)... (cached) yes
checking for bison... yes
checking for bison version >= 2.5... no
configure: error: Bison version 2.5 or higher must be installed on the system!
```

We have installed `bison` > 2.5 in the osquery runtime directories, but the configuration is not finding it.

**Comment by ilovezfs** [comment]
@theopolis is
```
diff --git a/lib/cpp/src/thrift/transport/TServerSocket.cpp b/lib/cpp/src/thrift/transport/TServerSocket.cpp
index 87b6383..447c89d 100644
--- a/lib/cpp/src/thrift/transport/TServerSocket.cpp
+++ b/lib/cpp/src/thrift/transport/TServerSocket.cpp
@@ -584,6 +584,12 @@ shared_ptr<TTransport> TServerSocket::acceptImpl() {
         // a certain number
         continue;
       }
+
+      // Special case because we expect setuid syscalls in other threads.
+      if (THRIFT_GET_SOCKET_ERROR == EINTR) {
+        continue;
+      }
+
       int errno_copy = THRIFT_GET_SOCKET_ERROR;
       GlobalOutput.perror("TServerSocket::acceptImpl() THRIFT_POLL() ", errno_copy);
       throw TTransportException(TTransportException::UNKNOWN, "Unknown", errno_copy);
```
something that would be appropriate to get upstreamed to thrift or is it specific to osquery?

**Pull request merged**
