### PR TITLE
Update flaky test for ASL table

### PR DESCRIPTION
**Pull request by zwass**
Previously, this test relied on there being console messages available
to query for. Now, it actually writes a message to ASL, then verifies
that the message can be found. It also exercises a more complicated
query than previously.

Fixes issue #1975

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Ok, this will work.

I have continued reservations about:
```sql
select * from asl limit 10
```

On the build hosts this runs for about ~5minutes. We should figure out a way to make this query smarter. I could have sworn there was an SQLite data structure revealing the `LIMIT` clause, but cannot find it :/

**Comment by theopolis** [comment]
We can come up with a solution similar to the "optimize" logic in the events system. It appear this table, when executing in a schedule, could issue a stateful "time" to the ASL query. Then diffing results between two query executions will make more sense and not spin extra cycles.

**Comment by osqueryer** [comment]
Build origin/pr/1982/merge (Job: 2534) is good! :+1:

**Comment by zwass** [comment]
We wouldn't really lose anything if we removed the above query from the test. The other queries are checking more specific stuff and would certainly fail if that query fails. They are also much faster.

As you describe, if time is passed into the query, it will limit things on the ASL side and be much more efficient.

**Comment by zwass** [comment]
But 5 minutes sounds really crazy. Even with hundreds of thousands of logs due to runaway log spam the query only takes about 10 seconds on a modern Mac laptop. What's the `count(*)` on that?

**Comment by theopolis** [comment]
The hosts aren't special because they have lots of logs, they are very slow. It's the relative time-- normal tests become exacerbated to 10seconds (normally finish in less than one).

**Comment by osqueryer** [comment]
Build origin/pr/1982/merge (Job: 2535) is good! :+1:

**Comment by zwass** [comment]
Understood. With my most recent push, we are only doing a query that should be very efficient. It looks like the tests are back to being in the ~10s range now.

**Pull request merged**
