### PR TITLE
Add GID to PrivilegeDropper

### PR DESCRIPTION
**Pull request by theopolis**
The previous privilege dropping logic was incorrect w.r.t to dropping group privilege. This switches the order and drops the effective group before the user.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
By default (meaning no capabilities configuration), dropping privileges temporarily (0 to non-0 GID/UID) will stop the udev monitor socket and thrift UNIX domain socket. This applies to `setfsuid(2)` and `setfsgid(2)` too. Using thrift 0.9.3, the `TServerSocket::acceptImpl` does not restore the connection when the process regains privileged credentials.

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Comment by theopolis** [comment]
This fixes #1638 too!

**Pull request merged**
