### PR TITLE
add support for amazon linux 2015.03 

### PR DESCRIPTION
**Pull request by blakefrantz**
per issue #1124

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by theopolis** [comment]
@osqueryer, ok to test!

Looks great! Are there any Vagrant boxes available for Amazon Linux? 

@javuto might need those extra 6 boxes now. Where did @jedi22 go, we need more minis! &lt;/InsideJoke&gt;

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Hey @blakefrantz, since this is looking GTG as a community/unsupported build I don't mind merging the provision script. If/when you're happy with a Vagrant plugin to build on AWS we can open another PR and debate how we might accomplish a "supported" EC2 build from future git PRs.

**Comment by blakefrantz** [comment]
@theopolis - sounds like a plan. The commits I made yesterday clean up the last few known issues with the amazon linux provision scripts so merging sounds great.  I've stuffed the resultant rpms in s3 if others want to give them a spin: 
https://s3.amazonaws.com/public.blafra.io/scratch/osquery-latest-1.4.5-58-g4262dd5.rpm

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
