### PR TITLE
PEP8  && Python 3.x

### PR DESCRIPTION
**Pull request by pathcl**
Attempt to have osquery working on Python 3.X. Tested on Python 3.4.3 and 3.6.0a0

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by marpaia** [comment]
You're a saint. How did you do this? Did you use an automated tool to do the linting/conversion? If so, it would be awesome if we could hook up a cmake command like `make lint` or something that wrapped this, to make sure we don't regress.

**Comment by pathcl** [comment]
@marpaia I used https://pypi.python.org/pypi/pep8 great idea to have into a cmake! I noticed there're more suggestions (most of them are E111)

tarro:osquery lsanmartin$ find . -name '*.py'|xargs pep8
./tools/codegen/amalgamate.py:28:9: E128 continuation line under-indented for visual indent
./tools/codegen/amalgamate.py:63:13: E128 continuation line under-indented for visual indent
./tools/codegen/genapi.py:28:1: E402 module level import not at top of file
./tools/codegen/genapi.py:150:21: E128 continuation line under-indented for visual indent
./tools/codegen/genapi.py:160:21: E128 continuation line under-indented for visual indent
./tools/codegen/genapi.py:165:14: E211 whitespace before '('
./tools/codegen/genapi.py:169:14: E211 whitespace before '('
./tools/codegen/genapi.py:169:80: E501 line too long (80 > 79 characters)
./tools/codegen/genapi.py:170:13: E128 continuation line under-indented for visual indent
./tools/codegen/genapi.py:173:14: E211 whitespace before '('
./tools/codegen/genapi.py:177:14: E211 whitespace before '('
./tools/codegen/genapi.py:178:13: E128 continuation line under-indented for visual indent
./tools/codegen/genapi.py:213:1: E302 expected 2 blank lines, found 1
./tools/codegen/genapi.py:270:80: E501 line too long (80 > 79 characters)
./tools/codegen/genapi.py:275:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:276:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:277:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:280:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:281:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:282:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:284:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:287:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:289:7: E111 indentation is not a multiple of four
./tools/codegen/genapi.py:291:7: E111 indentation is not a multiple of four
./tools/codegen/gentable.py:24:1: E402 module level import not at top of file
./tools/codegen/gentable.py:39:1: E302 expected 2 blank lines, found 1
./tools/codegen/gentable.py:66:1: E302 expected 2 blank lines, found 1
./tools/codegen/gentable.py:117:80: E501 line too long (80 > 79 characters)
./tools/codegen/gentable.py:119:18: E211 whitespace before '('
./tools/codegen/gentable.py:183:18: E211 whitespace before '('
./tools/codegen/gentable.py:189:22: E211 whitespace before '('
./tools/codegen/gentable.py:210:14: E211 whitespace before '('
./tools/codegen/gentable.py:273:13: E711 comparison to None should be 'if cond is None:'
./tools/codegen/gentable.py:328:80: E501 line too long (80 > 79 characters)
./tools/codegen/gentable.py:334:9: E128 continuation line under-indented for visual indent
./tools/codegen/gentargets.py:14:1: E302 expected 2 blank lines, found 1
./tools/formatting/git-clang-format.py:3:1: E265 block comment should start with '# '
./tools/formatting/git-clang-format.py:3:80: E501 line too long (80 > 79 characters)
./tools/formatting/git-clang-format.py:10:1: E265 block comment should start with '# '
./tools/formatting/git-clang-format.py:10:80: E501 line too long (80 > 79 characters)
./tools/formatting/git-clang-format.py:58:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:60:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:61:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:62:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:63:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:64:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:66:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:68:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:72:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:83:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:86:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:89:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:92:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:94:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:99:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:101:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:103:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:105:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:108:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:110:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:111:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:112:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:113:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:115:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:117:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:119:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:120:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:122:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:123:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:124:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:126:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:127:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:130:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:131:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:134:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:135:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:137:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:140:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:141:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:142:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:143:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:144:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:147:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:150:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:152:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:153:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:155:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:159:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:160:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:165:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:167:80: E501 line too long (80 > 79 characters)
./tools/formatting/git-clang-format.py:170:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:172:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:173:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:175:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:176:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:178:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:179:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:183:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:192:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:194:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:196:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:198:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:201:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:203:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:206:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:208:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:209:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:211:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:212:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:213:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:216:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:220:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:221:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:222:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:223:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:224:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:225:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:227:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:229:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:234:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:236:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:237:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:238:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:239:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:241:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:245:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:246:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:247:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:248:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:249:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:250:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:253:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:257:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:262:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:263:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:264:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:265:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:266:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:270:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:278:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:279:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:282:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:285:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:286:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:287:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:289:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:291:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:295:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:299:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:300:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:303:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:307:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:308:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:309:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:313:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:316:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:321:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:324:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:326:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:327:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:329:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:330:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:334:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:340:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:341:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:342:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:345:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:348:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:355:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:358:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:359:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:361:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:364:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:367:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:369:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:371:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:372:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:373:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:374:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:376:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:377:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:378:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:380:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:382:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:387:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:389:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:390:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:391:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:392:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:394:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:396:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:398:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:403:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:407:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:408:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:409:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:411:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:412:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:416:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:417:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:418:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:419:3: E114 indentation is not a multiple of four (comment)
./tools/formatting/git-clang-format.py:420:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:424:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:428:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:430:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:433:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:435:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:436:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:437:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:438:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:446:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:448:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:450:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:451:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:455:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:456:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:457:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:458:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:460:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:462:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:463:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:465:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:467:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:469:7: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:471:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:473:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:475:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:479:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:480:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:484:3: E111 indentation is not a multiple of four
./tools/formatting/git-clang-format.py:485:1: W391 blank line at end of file
./tools/profile.py:18:10: E211 whitespace before '('
./tools/profile.py:29:1: E402 module level import not at top of file
./tools/profile.py:57:14: E211 whitespace before '('
./tools/profile.py:79:18: E211 whitespace before '('
./tools/profile.py:85:18: E211 whitespace before '('
./tools/profile.py:86:18: E211 whitespace before '('
./tools/profile.py:94:80: E501 line too long (80 > 79 characters)
./tools/profile.py:100:14: E211 whitespace before '('
./tools/profile.py:117:14: E211 whitespace before '('
./tools/profile.py:142:18: E211 whitespace before '('
./tools/profile.py:145:17: E128 continuation line under-indented for visual indent
./tools/profile.py:146:14: E211 whitespace before '('
./tools/profile.py:147:10: E211 whitespace before '('
./tools/profile.py:149:14: E211 whitespace before '('
./tools/profile.py:150:10: E211 whitespace before '('
./tools/profile.py:174:21: E128 continuation line under-indented for visual indent
./tools/profile.py:184:14: E211 whitespace before '('
./tools/profile.py:220:22: E211 whitespace before '('
./tools/profile.py:221:21: E128 continuation line under-indented for visual indent
./tools/profile.py:224:14: E211 whitespace before '('
./tools/profile.py:314:14: E211 whitespace before '('
./tools/profile.py:317:14: E211 whitespace before '('
./tools/profile.py:323:18: E211 whitespace before '('
./tools/profile.py:354:14: E211 whitespace before '('
./tools/tests/stress.py:26:10: E211 whitespace before '('
./tools/tests/stress.py:33:1: E302 expected 2 blank lines, found 1
./tools/tests/stress.py:43:18: E211 whitespace before '('
./tools/tests/stress.py:96:14: E211 whitespace before '('
./tools/tests/stress.py:97:14: E211 whitespace before '('
./tools/tests/stress.py:98:14: E211 whitespace before '('
./tools/tests/stress.py:103:1: E302 expected 2 blank lines, found 1
./tools/tests/stress.py:113:18: E211 whitespace before '('
./tools/tests/stress.py:115:18: E211 whitespace before '('
./tools/tests/test_additional.py:24:1: E302 expected 2 blank lines, found 1
./tools/tests/test_base.py:14:1: E265 block comment should start with '# '
./tools/tests/test_base.py:42:10: E211 whitespace before '('
./tools/tests/test_base.py:51:10: E211 whitespace before '('
./tools/tests/test_base.py:75:1: E402 module level import not at top of file
./tools/tests/test_base.py:82:1: E302 expected 2 blank lines, found 1
./tools/tests/test_base.py:105:13: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:169:21: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:175:18: E211 whitespace before '('
./tools/tests/test_base.py:176:18: E211 whitespace before '('
./tools/tests/test_base.py:220:5: E303 too many blank lines (2)
./tools/tests/test_base.py:283:13: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:288:80: E501 line too long (81 > 79 characters)
./tools/tests/test_base.py:308:80: E501 line too long (81 > 79 characters)
./tools/tests/test_base.py:313:13: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:314:13: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:412:1: E302 expected 2 blank lines, found 1
./tools/tests/test_base.py:417:13: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:418:13: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:419:13: E128 continuation line under-indented for visual indent
./tools/tests/test_base.py:420:9: E731 do not assign a lambda expression, use a def
./tools/tests/test_base.py:426:1: E302 expected 2 blank lines, found 1
./tools/tests/test_base.py:449:18: E211 whitespace before '('
./tools/tests/test_base.py:450:18: E211 whitespace before '('
./tools/tests/test_base.py:482:18: E211 whitespace before '('
./tools/tests/test_base.py:498:80: E501 line too long (81 > 79 characters)
./tools/tests/test_base.py:550:14: E211 whitespace before '('
./tools/tests/test_base.py:551:14: E211 whitespace before '('
./tools/tests/test_base.py:551:80: E501 line too long (80 > 79 characters)
./tools/tests/test_base.py:564:14: E211 whitespace before '('
./tools/tests/test_base.py:565:14: E211 whitespace before '('
./tools/tests/test_base.py:566:14: E211 whitespace before '('
./tools/tests/test_example_queries.py:26:1: E302 expected 2 blank lines, found 1
./tools/tests/test_extensions.py:31:1: E302 expected 2 blank lines, found 1
./tools/tests/test_extensions.py:56:14: E211 whitespace before '('
./tools/tests/test_extensions.py:108:13: E128 continuation line under-indented for visual indent
./tools/tests/test_extensions.py:116:14: E211 whitespace before '('
./tools/tests/test_extensions.py:117:14: E211 whitespace before '('
./tools/tests/test_extensions.py:125:14: E211 whitespace before '('
./tools/tests/test_extensions.py:134:14: E211 whitespace before '('
./tools/tests/test_extensions.py:185:14: E211 whitespace before '('
./tools/tests/test_extensions.py:310:13: E128 continuation line under-indented for visual indent
./tools/tests/test_http_server.py:56:1: E302 expected 2 blank lines, found 1
./tools/tests/test_http_server.py:59:1: E302 expected 2 blank lines, found 1
./tools/tests/test_http_server.py:104:80: E501 line too long (80 > 79 characters)
./tools/tests/test_http_server.py:146:1: E302 expected 2 blank lines, found 1
./tools/tests/test_http_server.py:148:9: E128 continuation line under-indented for visual indent
./tools/tests/test_http_server.py:223:27: E222 multiple spaces after operator
./tools/tests/test_http_server.py:227:17: E128 continuation line under-indented for visual indent
./tools/tests/test_http_server.py:228:17: E128 continuation line under-indented for visual indent
./tools/tests/test_http_server.py:229:17: E128 continuation line under-indented for visual indent
./tools/tests/test_http_server.py:230:17: E128 continuation line under-indented for visual indent
./tools/tests/test_http_server.py:231:17: E128 continuation line under-indented for visual indent
./tools/tests/test_modules.py:7:79: W291 trailing whitespace
./tools/tests/test_modules.py:14:1: E265 block comment should start with '# '
./tools/tests/test_modules.py:24:1: E302 expected 2 blank lines, found 1
./tools/tests/test_modules.py:31:13: E128 continuation line under-indented for visual indent
./tools/tests/test_modules.py:53:13: E128 continuation line under-indented for visual indent
./tools/tests/test_modules.py:61:13: E128 continuation line under-indented for visual indent
./tools/tests/test_modules.py:67:13: E128 continuation line under-indented for visual indent
./tools/tests/test_modules.py:70:13: E128 continuation line under-indented for visual indent
./tools/tests/test_osqueryd.py:24:1: E302 expected 2 blank lines, found 1
./tools/tests/test_osqueryd.py:41:9: E122 continuation line missing indentation or outdented
./tools/tests/test_osqueryd.py:54:1: W293 blank line contains whitespace
./tools/tests/test_osqueryi.py:7:79: W291 trailing whitespace
./tools/tests/test_osqueryi.py:14:1: E265 block comment should start with '# '
./tools/tests/test_osqueryi.py:25:1: E302 expected 2 blank lines, found 1
./tools/tests/test_osqueryi.py:37:13: E128 continuation line under-indented for visual indent
./tools/tests/test_osqueryi.py:49:14: E211 whitespace before '('
./tools/tests/test_osqueryi.py:50:14: E211 whitespace before '('
./tools/tests/test_osqueryi.py:57:17: E131 continuation line unaligned for hanging indent
./tools/tests/test_osqueryi.py:63:14: E211 whitespace before '('
./tools/tests/test_osqueryi.py:64:14: E211 whitespace before '('
./tools/tests/test_osqueryi.py:99:14: E211 whitespace before '('
./tools/tests/test_osqueryi.py:100:14: E211 whitespace before '('
./tools/tests/test_osqueryi.py:161:13: E128 continuation line under-indented for visual indent
./tools/tests/test_release.py:7:79: W291 trailing whitespace
./tools/tests/utils.py:23:1: E302 expected 2 blank lines, found 1
./tools/tests/utils.py:70:39: E231 missing whitespace after ','
./tools/tests/utils.py:73:14: E211 whitespace before '('
./tools/tests/utils.py:83:17: E231 missing whitespace after ','
./tools/tests/utils.py:86:47: E231 missing whitespace after ','
./tools/tests/utils.py:88:30: E231 missing whitespace after ','
./tools/tests/utils.py:92:9: E303 too many blank lines (2)
./tools/tests/utils.py:94:14: E211 whitespace before '('
./tools/tests/utils.py:183:1: W391 blank line at end of file

**Comment by pathcl** [comment]
@marpaia btw I also used autopep8 for automate linting https://pypi.python.org/pypi/autopep8/

**Comment by marpaia** [comment]
In osquery-python, we have pylint wired up to [`python setup.py lint`](https://github.com/osquery/osquery-python/blob/master/CONTRIBUTING.md#lint). That's implemented via a simple command class in the `setup.py`: 

```py
class LintCommand(Command):
    """Run pylint on implementation and test code"""

    description = "Run pylint on implementation and test code"
    user_options = []

    _pylint_options = [
        "--max-line-length 80",
        "--ignore-imports yes"
    ]

    _lint_paths = [
        "osquery/*.py",
        "tests/*.py",
    ]

    def initialize_options(self):
        """Set default values for options."""
        pass

    def finalize_options(self):
        """Post-process options."""
        pass

    def run(self):
        """Run the command"""
        system("pylint %s %s" % (
            " ".join(self._pylint_options),
            " ".join(self._lint_paths),
        ))
```

We obviously don't have a `setup.py`, so relevance is questionable, but it should be pretty simple to run a pylint command as a CMake command, similarly to `make format`:

```cmake
# make format
add_custom_target(
  format
  ${PYTHON_EXECUTABLE} "${CMAKE_SOURCE_DIR}/tools/formatting/git-clang-format.py"
  WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
  COMMENT "Formatting code staged code changes with clang-format" VERBATIM
)
```

We've talked about getting some linters set up for the C++ code as well, which I think would be the cooler thing here, as it would help us strongly codify our style guidelines that `clang-format` can't figure out. Getting this wired into cmake would definitely set the tone there for establishing a pattern and user experience. 

Internally, at Facebook, we have some pretty epic lint tooling that will show you a lint error and offer to auto-apply a fix. It would be neat if we could do that, but one step at a time I think :)

**Pull request closed without merging**
