### PR TITLE
Windows Daemon/Shell: Initial support for Windows tables

### PR DESCRIPTION
**Pull request by artemdinaburg**
Beginning a series of pull requests that gets the daemon building on Windows, provides basic service functionality, and allows for the osquery shell to build on Windows. 

This PR Moves existing specs into `posix`, and creates a new `specs/windows` directory which has a simple processes table. We need a basic processes table for the daemon to run  ( #2007 ).

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by osqueryer** [comment]
Build origin/pr/2182/merge (Job: 2768) failed :-1:

**Comment by osqueryer** [comment]
Build origin/pr/2182/merge (Job: 2772) is good! :+1:

**Pull request merged**
