### PR TITLE
Make sysctls work on FreeBSD

### PR DESCRIPTION
**Pull request by lxcode**
Adapted from Darwin, removed manual CTLTYPE definitions and switched "quad" to "s64" and long long instead of unsigned long long (Darwin uses unsigned, FreeBSD's is signed).

### CODE REVIEW

**Comment by theopolis** [comment]
test freebsd please

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 3b3a27b2d896bff9d8f002c7d4b2b70df751fdf5 (Job results: [1476](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1476/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 3b3a27b2d896bff9d8f002c7d4b2b70df751fdf5 (Job results: [4611](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4611/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 8da68081251cff7a76a0d0f75007ace287a4525c (Job results: [4612](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4612/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 8da68081251cff7a76a0d0f75007ace287a4525c (Job results: [4613](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4613/)) failed one or more tests (**Linux**).

**Comment by lxcode** [comment]
The CentOS 6 VM is out of disk space. :)

**Pull request merged**
