### PR TITLE
Remove /dev/null monitoring from fsevents

### LINKED ISSUE #4537: osqueryd CPU usage spikes when writes performed to /dev/null
### What version of `osquery` are you using? What operating system. Be specific.
3.2.6, MacOS 10.13.4

We are seeing a strange behavior where when many writes are performed to `/dev/null`, CPU usage of `osqueryd` spikes.

We have reproduced this on every MacOS box we've tested on by doing the following:

1) download and install OSQuery 3.2.6 from osquery.io
2) launch the process `sudo /usr/local/bin/osqueryd`
3) watch CPU usage of the `osqueryd` processes in Activity Monitor -- usage should be low
4) begin writing to `/dev/null`: `dd if=/dev/zero of=/dev/null`
5) watch CPU usage of the `osqueryd` processes in Activity Monitor -- one of them will spike to 100 and remain there
6) wait, observe, and see that CPU usage of `osqueryd` remains high
7) kill the `dd` process writing to `/dev/null`
8) observe CPU usage of `osqueryd` processes -- the process that was spiking will fall back down to very low levels

I believe this requires having the watchdog disabled, otherwise it should theoretically kill the `osqueryd` process.

### PR DESCRIPTION
**Pull request by fmanco**
Fix #4537.

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by guliashvili** [comment]
ok to test

**Comment by theopolis** [comment]
jenkins test windows

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
Sorry for the noise here, I was trying to improve the whitelisting for people sending PRs but I failed. For posterity, I created T30437153 to ask for help. My hypothesis is the token the `osqueryer` account is using does not allow organization enumeration.

**Pull request merged**
