### PR TITLE
[Fix #2599] Read from Linux SMI sysfs node for SMBIOS

### LINKED ISSUE #2599: Xenial kernel 4.4.0-38 smbios and platform table errors
I'm seeing:
```
I1007 11:50:35.417464 14995 smbios_tables.cpp:64] Invalid EFI provided SMBIOS start address: 3485454336
osquery planner: Scanning rows for cursor (6)
I1007 11:50:35.417950 14995 smbios_tables.cpp:64] Invalid EFI provided SMBIOS start address: 3485454336
I1007 11:50:35.417992 14995 smbios_tables.cpp:120] Could not read SMBIOS memory
```

When querying `smbios_tables` and `platform_info`.

### PR DESCRIPTION
**Pull request by theopolis**
This also fixes odd behavior in Linux when reading a 'regular' file from /sys that only returns a max of a page-read in bytes.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit 2de8d1b5165b8be5d3cf3347559f41ee9f548e68 (Job results: [455](https://jenkins.osquery.io/job/osqueryPullRequestAudit/455/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit cc43a1cda0cd608e7f8dba4b34bea8e140cefc2d (Job results: [3474](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3474/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit cc43a1cda0cd608e7f8dba4b34bea8e140cefc2d (Job results: [478](https://jenkins.osquery.io/job/osqueryPullRequestBuild/478/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit b6cff47c2fb86fbade53cade04cf5e43b6e5fe7a (Job results: [482](https://jenkins.osquery.io/job/osqueryPullRequestBuild/482/)) failed one or more tests (**Windows**).

**Pull request merged**
