### PR TITLE
Generate random Kinesis partition keys per-record

### PR DESCRIPTION
**Pull request by zwass**
New information from AWS indicates that throughput will be maximized if each
record in a batch request has a different partition key. Previously we were
generating one random key for each batch.

### CODE REVIEW

**Comment by zwass** [comment]
cc @hackgnar

**Comment by hackgnar** [comment]
@zwass this may be bad.... I had this functionality when I first implemented it but saw tons of failed partial uploads.  When I switched it to batch mode, it fixed the issue.

I did a lot of testing with this.  When I want to test failed partial uploads, I implement the random partition key per event.

**Comment by zwass** [comment]
(Note this is being discussed in Slack)

**Comment by PoppySeedPlehzr** [comment]
ok to test

**Comment by zwass** [comment]
Please see @hackgnar's comment above and  **do not merge** until we get signoff from all concerned parties.

**Comment by hackgnar** [comment]
ya, so it seems @coffee is right and we should merge this PR and put it back to the way I had it before (https://github.com/facebook/osquery/pull/2662) with random partition keys per event.  It can be clarified in the documentation http://docs.aws.amazon.com/streams/latest/dev/developing-producers-with-sdk.html and http://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html.  

My tests ended up being a very strange corner case which proved random partition keys per batch being oddly better.  The following scenario sums it up my odd corner case:

- Assume you had a stream with 2 shards (shard1 & shard2).
- Assume you have 2 apps sending data to your stream where one app is using static partition keys (app_w_static_key) and other other is using random partition keys (app_w_random_key)
- Assume app_w_static_key is sending tons of data which saturates shard1 constantly

When app_w_random_key sends data it will split its load across shard1 & shard2.  Any data that app_w_random_key sends to shard1 will fail to upload.  This will cause a partial failed upload due to rate limits on shard1.  This will cause partial failed uploads to happen at a high interval for app_w_random_key.

As osquery used to resend all data when a partial failed upload happened (before PR https://github.com/facebook/osquery/pull/2703), this was once a major issue which caused very large amounts of duplicate data.  However, now that we handle resending of only failed data, we should go with sending data with random partition keys per event as its the most optimal solution.

**Pull request merged**
