### PR TITLE
Add a SQLiteDBManager

### PR DESCRIPTION
**Pull request by theopolis**
This is an attempt to make `sqlite3` safer. Access is now arbitrated and applies an RAII model.

### CODE REVIEW

**Comment by theopolis** [comment]
As an aside, there might be way to speed up:
```cpp
int queryDataCallback(void* argument, int argc, char* argv[], char* column[]) {
  if (argument == nullptr) {
    LOG(ERROR) << "queryDataCallback received nullptr as data argument";
    return SQLITE_MISUSE;
  }

  QueryData* qData = (QueryData*)argument;
  Row r;
  for (int i = 0; i < argc; i++) {
    r[column[i]] = argv[i];
  }
  (*qData).push_back(r);
  return 0;
}
```

Not sure if that's a micro-optimization, but moving the data from arguments into the results would be nice.

**Comment by theopolis** [comment]
This improves OSX performance with osqueryd:
Syscalls per 4 seconds: 3,500 to 70
Shared mem: 3.5M to 1.3M
Private mem: 2.3M to 1.5M
Real mem: 6.2M to 5.3M

**Comment by theopolis** [comment]
Profiling tests:
```
./tools/profile.py --query "select * from time" --count 100 --rounds 3
 Profiling query: select * from time
 D:2  C:1  M:0  F:0  U:3  manual (1/3): duration: 1.01023101807 cpu_time: 0.8 memory: 5554176 fds: 5 utilization: 79.9 
 D:2  C:1  M:0  F:0  U:3  manual (2/3): duration: 1.00965285301 cpu_time: 0.78 memory: 5554176 fds: 5 utilization: 77.9 
 D:2  C:1  M:0  F:0  U:3  manual (3/3): duration: 1.00837993622 cpu_time: 0.81 memory: 5554176 fds: 5 utilization: 79.9 
 D:2  C:1  M:0  F:0  U:3  manual   avg: duration: 1.0094212691 cpu_time: 0.796666666667 memory: 5554176.0 fds: 5.0 utilization: 79.2333333333 

./tools/profile.py --query "select * from time" --count 100 --rounds 3
 Profiling query: select * from time
 D:0  C:0  M:0  F:0  U:0  manual (1/3): duration: 0.50782585144 cpu_time: 0.02 memory: 5545984 fds: 7 utilization: 4.0 
 D:0  C:0  M:0  F:0  U:0  manual (2/3): duration: 0.508677959442 cpu_time: 0.02 memory: 5541888 fds: 7 utilization: 4.0 
 D:0  C:0  M:0  F:0  U:0  manual (3/3): duration: 0.508152008057 cpu_time: 0.02 memory: 5541888 fds: 7 utilization: 4.0 
 D:0  C:0  M:0  F:0  U:0  manual   avg: duration: 0.508218606313 cpu_time: 0.02 memory: 5543253.33333 fds: 7.0 utilization: 4.0
```

Performance profiling (syscalls) on linux:
```
 perf trace -s -- ./build/linux/osquery/run --query "select * from time" --iterations 100
 run (32280), 196407 events, 100.0%, 0.000 msec

   syscall            calls      min       avg       max      stddev
                               (msec)    (msec)    (msec)        (%)
   --------------- -------- --------- --------- ---------     ------
   read                  27     0.000     0.037     0.120     10.22%
   write              48100     0.000     0.043     7.246      0.46%
   open                 251     0.026     0.065     1.101      7.00%
   close                229     0.028     0.065     0.154      3.54%
   stat                 305     0.029     0.072     0.211      1.52%
   fstat                528     0.000     0.049     2.526      9.79%
   lseek              48001     0.000     0.047     4.222      0.42%
   mmap                  66     0.030     0.044     0.177      6.46%
   mprotect              43     0.032     0.041     0.144      6.51%
   munmap                 3     0.036     0.041     0.051     12.05%
   brk                    8     0.031     0.045     0.073     12.76%
   rt_sigaction           2     0.029     0.029     0.030      1.47%
   rt_sigprocmask         1     0.029     0.029     0.029      0.00%
   access               423     0.029     0.056     0.203      2.06%
   nanosleep              1     0.613     0.613     0.613      0.00%
   socket                 1     0.037     0.037     0.037      0.00%
   bind                   1     0.034     0.034     0.034      0.00%
   getsockname            1     0.029     0.029     0.029      0.00%
   setsockopt             1     0.030     0.030     0.030      0.00%
   execve                 1     0.000     0.000     0.000      0.00%
   unlink               200     0.033     0.046     0.180      3.30%
   getrlimit              1     0.043     0.043     0.043      0.00%
   arch_prctl             1     0.029     0.029     0.029      0.00%
   futex                  5     0.030     0.034     0.044      7.35%
   set_tid_address        1     0.030     0.030     0.030      0.00%
   inotify_init           1     0.052     0.052     0.052      0.00%
   inotify_add_watch        1     0.067     0.067     0.067      0.00%
   set_robust_list        1     0.030     0.030     0.030      0.00%

 perf trace -s -- ./build/linux/osquery/run --query "select * from time" --iterations 100
 run (13497), 2760 events, 99.1%, 0.000 msec

   syscall            calls      min       avg       max      stddev
                               (msec)    (msec)    (msec)        (%)
   --------------- -------- --------- --------- ---------     ------
   read                  27     0.027     0.036     0.064      5.68%
   write                480     0.026     0.047     0.127      1.54%
   open                  53     0.024     0.103     2.839     51.30%
   close                 31     0.028     0.041     0.150     10.07%
   stat                 107     0.029     0.082     0.937     10.84%
   fstat                 32     0.027     0.049     0.269     18.25%
   lseek                481     0.026     0.054     0.439      2.53%
   mmap                  65     0.028     0.039     0.073      3.49%
   mprotect              43     0.031     0.049     0.316     14.83%
   munmap                 3     0.041     0.042     0.043      0.98%
   brk                    9     0.033     0.080     0.304     35.60%
   rt_sigaction           2     0.029     0.030     0.031      1.82%
   rt_sigprocmask         1     0.049     0.049     0.049      0.00%
   access                27     0.028     0.054     0.217     13.67%
   nanosleep              1     0.635     0.635     0.635      0.00%
   socket                 1     0.328     0.328     0.328      0.00%
   bind                   1     0.038     0.038     0.038      0.00%
   getsockname            1     0.059     0.059     0.059      0.00%
   setsockopt             1     0.038     0.038     0.038      0.00%
   execve                 1     0.442     0.442     0.442      0.00%
   unlink                 2     0.037     0.038     0.039      2.90%
   getrlimit              1     0.031     0.031     0.031      0.00%
   arch_prctl             1     0.030     0.030     0.030      0.00%
   futex                  5     0.031     0.039     0.057     12.30%
   set_tid_address        1     0.050     0.050     0.050      0.00%
   inotify_init           1     0.062     0.062     0.062      0.00%
   inotify_add_watch        1     0.036     0.036     0.036      0.00%
   set_robust_list        1     0.030     0.030     0.030      0.00%
```

**Comment by mimeframe** [comment]
> Syscalls per 4 seconds: 3,500 to 70

Sick

**Pull request merged**
