### PR TITLE
added ctest after build

### PR DESCRIPTION
**Pull request by madduci**

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by mtmcgrew** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit b9cc92dac4cfee304c1e546551c1dfd95eee94ed (Job results: [403](https://jenkins.osquery.io/job/osqueryPullRequestBuild/403/)) failed one or more tests (**Windows**).

**Comment by PoppySeedPlehzr** [comment]
Hey @madduci !  Thanks for your PR. I just merged in #2563 which should get those windows tests passing. Would you mind rebasing your commit and we'll see if the tests pass?

**Comment by theopolis** [comment]
Here's the best way to rebase:
```
$ git pull --rebase origin master
```

Followed by a:
```
$ git push -f
```

**Comment by madduci** [comment]
I've done that, now it should work

**Comment by PoppySeedPlehzr** [comment]
Hey @madduci, it looks like what you've got still didn't quite pull down the gating that I added. What was your workflow for this? As @theopolis mentioned you'll want to run a `$ git pull --rebase origin master`, but only if your `origin` remote is Facebooks master branch. What does the output of running `$ git remote -v` look like?

**Comment by madduci** [comment]
I've fixed that :+1:

**Pull request merged**
