### PR TITLE
Set active distributed plugin within extensions

### PR DESCRIPTION
**Pull request by jedi22**
Adding a small line to fix an issues with a distributed query plugin

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

**Comment by jedi22** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
FYI: your commit title will live on forever in the history. It is sometimes used to discovery bugs/changes/blame. Consider adding more (but still succinct) context.

**Pull request merged**
