### PR TITLE
removal instructions for osquery on macOS

### PR DESCRIPTION
**Pull request by discentem**
As per https://github.com/facebook/osquery/issues/3548#issuecomment-338358744. 

I'm also thinking of writing uninstall.sh. Where in the project directories should I put such a script?

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by discentem** [comment]
@theopolis ?

**Comment by theopolis** [comment]
> @theopolis ?

hi!

**Comment by discentem** [comment]
Thanks for the merge @theopolis!

The question mark was because I didn't know what you meant by 
> okay to test

**Pull request merged**
