### PR TITLE
deps: Build linenoise locally (third-party)

### PR DESCRIPTION
**Pull request by theopolis**
This moves linenoise from an installed dependency to a locally-build third-party dependency. This library is not widely available so it makes more sense to include it in our third party repo.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [2495](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2495/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [2496](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2496/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
:no_good: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [3003](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3003/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [6415](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6415/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [6416](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6416/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [3290](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3290/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [3291](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3291/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [3292](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3292/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 329e2710e5f185cd9c2548f15879bece56ffc6fc (Job results: [3293](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3293/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
Fixes #4039.

**Comment by osqueryer** [comment]
:-1: The commit 6dce5e45e22616bc7f8085e69e4f4b6485e9e346 (Job results: [3295](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3295/)) failed one or more tests (**Windows**).

**Comment by theopolis** [comment]
Success!

**Pull request merged**
