### PR TITLE
Faster socket_events on Linux

### PR DESCRIPTION
**Pull request by theopolis**
The previous implementation of socket events (bind, connect) on Linux, is slow. It searches all of proc's network connection table after each syscall. We can for-go the complete netflow tuple by parsing the Audit `saddr` field to reduce searching to 0 cost.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
There's also an optimization to `users` to use UID. This is a massive perf win for production/OD/AD deployments when joining to grab username, default shell, or home.

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) is good! :+1:

**Comment by theopolis** [comment]
I need the `safeStrtol` methods! When I write safe, I just mean helpfully-error-checked. :dancer:

**Pull request merged**
