### PR TITLE
Adding getSystemRoot function and FS Formatting

### PR DESCRIPTION
**Pull request by PoppySeedPlehzr**
Add getSystemRoot fn to filesystem. Also ran clang format on filesystem.

### CODE REVIEW

**Comment by osqueryer** [comment]
:no_good: The commit a87c30a989ef6fde099644a1e71fe4b2f3b42530 (Job results: [75](https://jenkins.osquery.io/job/osqueryPullRequestAudit/75/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit a87c30a989ef6fde099644a1e71fe4b2f3b42530 (Job results: [3092](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3092/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit a87c30a989ef6fde099644a1e71fe4b2f3b42530 (Job results: [110](https://jenkins.osquery.io/job/osqueryPullRequestBuild/110/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit c64f56435d17afc327860de54f7b0b3cdb9b54fc (Job results: [3097](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3097/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:-1: The commit d77ab6cc2ca08054e12ce8771210207b063d71e0 (Job results: [116](https://jenkins.osquery.io/job/osqueryPullRequestBuild/116/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit d77ab6cc2ca08054e12ce8771210207b063d71e0 (Job results: [3098](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3098/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit b3f04b0706b7a4ef8b4e9db527ab4635003fe4fd (Job results: [83](https://jenkins.osquery.io/job/osqueryPullRequestAudit/83/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit b3f04b0706b7a4ef8b4e9db527ab4635003fe4fd (Job results: [3100](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3100/)) failed one or more tests (**OS X/Linux**).

**Comment by mtmcgrew** [comment]
retest this please

**Comment by osqueryer** [comment]
:no_good: The commit b3f04b0706b7a4ef8b4e9db527ab4635003fe4fd (Job results: [84](https://jenkins.osquery.io/job/osqueryPullRequestAudit/84/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit b3f04b0706b7a4ef8b4e9db527ab4635003fe4fd (Job results: [3101](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3101/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
ok to test

**Pull request merged**
