### PR TITLE
deps: Bumping windows glog to 0.3.5

### PR DESCRIPTION
**Pull request by muffins**
This bumps glog to 0.3.5 on Windows, as well as brings some of the aesthetic updates to the packaging we've got in other scripts.

### CODE REVIEW

**Comment by muffins** [comment]
This is going to fail, I forgot to upload the package to S3 📦

**Comment by osqueryer** [comment]
:-1: The commit dc2daa76dc6575b1700e77c3a65c56ecf66d5fee (Job results: [2046](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2046/)) failed one or more tests (**macOS/OS X**).

**Comment by osqueryer** [comment]
Build finished.

**Comment by muffins** [comment]
ok to test

**Pull request merged**
