### PR TITLE
sync: Fix sync to handle new fbthrift refactor

### PR DESCRIPTION
**Pull request by theopolis**
This updates the codegen for buck's `TARGET` file.

### CODE REVIEW

**Comment by theopolis** [comment]
h/t to @fmanco for pasting the TARGETs diff!

**Comment by osqueryer** [comment]
:-1: The commit 8b19c88bb336f4fc59f46e3ae132a484439d7ccd (Job results: [6975](https://jenkins.osquery.io/job/osqueryPullRequestLinux/6975/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 8b19c88bb336f4fc59f46e3ae132a484439d7ccd (Job results: [3858](https://jenkins.osquery.io/job/osqueryPullRequestWindows/3858/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit 8b19c88bb336f4fc59f46e3ae132a484439d7ccd (Job results: [2982](https://jenkins.osquery.io/job/osqueryPullRequestOSX/2982/)) failed one or more tests (**macOS/OS X**).

**Pull request merged**
