### PR TITLE
Remove SQLite3 from inline/third party build

### PR DESCRIPTION
**Pull request by theopolis**
SQLite3 should be on every supported system already. No need to build from the latest since we do not use any bleeding edge features.

### CODE REVIEW

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
Ubuntu 12;04:
```
/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/ubuntu12/osquery/sql/sqlite_util.cpp:281:3: error: use of undeclared identifier 'sqlite3_db_release_memory'; did you mean 'sqlite3_release_memory'?
  sqlite3_db_release_memory(db);
  ^~~~~~~~~~~~~~~~~~~~~~~~~
  sqlite3_release_memory
/usr/include/sqlite3.h:4529:16: note: 'sqlite3_release_memory' declared here
SQLITE_API int sqlite3_release_memory(int);
               ^
/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/ubuntu12/osquery/sql/sqlite_util.cpp:281:29: error: cannot initialize a parameter of type 'int' with an lvalue of type 'sqlite3 *'
  sqlite3_db_release_memory(db);
                            ^~
/usr/include/sqlite3.h:4529:42: note: passing argument to parameter here
SQLITE_API int sqlite3_release_memory(int);
```

RHEL6:
```
In file included from /home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/rhel6/osquery/dispatcher/scheduler.cpp:21:
/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/rhel6/osquery/sql/sqlite_util.h:112:5: error: use of undeclared identifier 'sqlite3_soft_heap_limit64'; did you mean 'sqlite3_soft_heap_limit'?
    sqlite3_soft_heap_limit64(SQLITE_SOFT_HEAP_LIMIT);
    ^~~~~~~~~~~~~~~~~~~~~~~~~
    sqlite3_soft_heap_limit
/usr/include/sqlite3.h:4044:17: note: 'sqlite3_soft_heap_limit' declared here
SQLITE_API void sqlite3_soft_heap_limit(int);
```

RHEL7, CentOS6, CentOS7: Could not find library: sqlite3

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by osqueryer** [comment]
Build (5d91076148758d306d08b2cbacc3a25ff8a26c3f) failed :-1:

**Comment by theopolis** [comment]
It seems there are too many SQLite API changes to account for across the support distributions. We could potentially support a `OSQUERY_BUILD_EXTERN_SQLITE` that implements this search for an sqlite shared library instead of building from third party.

**Pull request closed without merging**
