### PR TITLE
Remove OpenSSL and cpp-netlib old version exceptions

### PR DESCRIPTION
**Pull request by theopolis**
We're no longer supporting multiple OpenSSL and cpp-netlib versions. Let's remove the preprocessor defines.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit b0b12c917f4eaebe9d5d0e8681e88d3ded3b0154 (Job results: [152](https://jenkins.osquery.io/job/osqueryPullRequestBuild/152/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit b0b12c917f4eaebe9d5d0e8681e88d3ded3b0154 (Job results: [3137](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3137/)) failed one or more tests (**OS X/Linux**).

**Comment by theopolis** [comment]
For CentOS6:
```
[       OK ] DistributedTests.test_serialize_distributed_query_result (12247 ms)
[ RUN      ] DistributedTests.test_deserialize_distributed_query_result
Traceback (most recent call last):
  File "../../../tools/tests//test_http_server.py", line 253, in <module>
    server_side=True)
TypeError: wrap_socket() got an unexpected keyword argument 'ciphers'
```

**Comment by theopolis** [comment]
For OS X:
```
Traceback (most recent call last):
  File "../../../tools/tests//test_http_server.py", line 243, in <module>
    ctx.set_ciphers(ciphers)
ssl.SSLError: ('No cipher can be selected.',)
```

This is because the SSL module is using Apple's OpenSSL, which is a 0.9.8.

**Comment by osqueryer** [comment]
:-1: The commit e2ac160230f914f1c52f6f7f12571e05aa4da38b (Job results: [3147](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3147/)) failed one or more tests (**OS X/Linux**).

**Comment by osqueryer** [comment]
:no_good: The commit 76f470531c7e4bb8a0d044789eac911cef77a813 (Job results: [151](https://jenkins.osquery.io/job/osqueryPullRequestAudit/151/)) failed the code audit.

**Comment by osqueryer** [comment]
:-1: The commit 886c61b83944d5c91981284f97d739eeb04d561f (Job results: [3170](https://jenkins.osquery.io/job/osqueryPullRequestBuild/3170/)) failed one or more tests (**OS X/Linux**).

**Pull request merged**
